src/locales/help/en-CA.md
src/locales/help/fr-CA.md

Closes #1800
Synchronize  French help markdown version
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1808)

feat(help): add French text for help markdown

---

pull_request_template.md

Closes #1804
No
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1812)

feat(PR checklist): add additional check and muffin threat

---

src/content/styles/modules/_shell.scss

Closes #1814
No
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1818)

fix(ui): north arrow no longer overlaps panels

---

src/app/bootstrap.js
src/app/global-registry.js

Closes #1824
Yes
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1831)

feat(bootstrap): load dependencies via host page url scheme

---

src/app/focus-manager.js

Closes #1822
:eye: 
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1828)

fix(focus): details panel no longer opens spontaneously

---

bower.json
docs/developer/contributing_guide/geo_merging.md
package.json

- Changes geoApi version which fixes #1779
- Updates "Merging geoApi changes" docs to reflect changes in merging strategy
- Corrects fgpv version numbers from v1.6.0 to v1.7.0 (dev on v1.7.0)
Closes #1779
No
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1845)

chore(geoApi): Update geoApi version, docs, and correct fgpv version #

---

src/app/ui/common/state.directive.spec.js
src/app/ui/help/help-overlay.directive.spec.js

A poorly written karma test was causing Travis build to fail.
Travis build passes.
Not required.
- ~[ ] release notes have been updated~ Not required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1862)

fix(test): test for rvState 3

---

bower.json
src/app/core/constant.service.js
src/app/geo/geo-search.service.js
src/app/ui/appbar/appbar.html
src/app/ui/geosearch/geosearch-bar.directive.js
src/app/ui/geosearch/geosearch-bar.html
src/app/ui/geosearch/geosearch-bottom-filters.html
src/app/ui/geosearch/geosearch-top-filters.directive.js
src/app/ui/geosearch/geosearch-top-filters.html
src/app/ui/geosearch/geosearch.directive.js
src/app/ui/geosearch/geosearch.html
src/app/ui/geosearch/geosearch.service.js
src/content/styles/modules/_geosearch.scss

Close #1805
Enhancement for geosearch. The tooltip only shows for FF and Chrome. Need to see for IE and not working for Safari. For now there is only on focus woth the keyboard. If we like the tooltip idea, I can work on the hover as well.
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1850)

feat(geosearch): enhance geosearch

---

bower.json
src/app/core/config.class.js
src/app/geo/identify.service.js
src/app/geo/legend-block.class.js
src/app/geo/map.service.js
src/app/ui/details/details-content.html
src/app/ui/details/details-header.html
src/app/ui/details/details-modal.html
src/app/ui/details/details-record-esrifeature.directive.js
src/app/ui/details/details-record-esrifeature.html
src/app/ui/details/details.directive.js
src/app/ui/details/layer-list-slider.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/toc/symbology-stack.directive.js
src/content/styles/modules/_details.scss

Restores identify functionality.
Nope.
- ~~[ ] commits messages follow the guidelines~~ not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1888)

Geo4 identify

---

src/app/ui/toc/legend-element-factory.class.js

Debounce visibility, boundingbox, and datatable settings.
Nope.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1892)

feat(ui): debounce visibility, bbox, and datable

---

Vagrantfile
src/app/geo/geo-search.service.js
src/app/geo/geo.service.js
src/app/geo/map.service.js
src/app/ui/details/details-record-esrifeature-item.html
src/app/ui/ui-loader.js
src/content/samples/index-mobile.tpl
src/content/styles/modules/_geosearch.scss
webpack.common.js

Restores geo search after the structured legend refactor.
Also fixes search filter overflow in #1865.
Turns off the "lightbulb" button to rehighlight individual details records as its full expected behaviour is not clear at the moment.
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1899)

Geo4 search fix

---

src/app/geo/layer-blueprint-user-options.class.js
src/app/geo/legend-entry.service.js
src/app/ui/loader/layer-source-info.class.js
src/app/ui/loader/layer-source.service.js

The new version of RColor has a different call signature.
Nope.
Who needs it?
~~- [ ] release notes have been updated~~ not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1907)

Fixing some things broken by webpack

---

src/app/core/config.class.js
src/app/geo/legend.service.js
src/app/geo/map.service.js
src/app/ui/loader/layer-source.service.js

- fixes wms loading broken by refactor;
- always render wms symbology as images;
- fix help broken by refactor;
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1910)

Wp geo4 wms fixes

---

src/app/layout/layout.service.js
src/app/layout/shell.directive.js
src/content/styles/common/_all.scss
src/content/styles/modules/_app-menu.scss

Closes #1857
reduce logo size on small layouts when its height is less than 450px
Try change the height to less than 450px
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1909)

feat(ui): reduce logo size on small layouts

---

src/app/core/bookmark.service.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js

Fixing bookmark generation.
Not yet.
Some comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1917)

refactor(bookmark): fixing v2 bookmark generation

---

src/app/app.module.js
src/app/layout/shell.html
src/app/ui/loader/loader-file.html
src/app/ui/sidenav/sidenav.html
src/app/ui/toc/templates/legend-group.html
src/locales/translations.csv

#1700 
Fix the warnings from aria-label
No, it is on console
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1912)

Fix warnings from aria-label

---

scripts/translations_plugin.js
src/locales/translations.csv

#1921 
Add the dirty bit columns in the translation file and ignore it when converting to JSON
No, because it was mostly editing data
translations.csv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1930)

Add dirty bit columns for English and French in the translation file

---

package.json
src/app/core/config.class.js
src/app/core/config.service.js
src/app/core/constant.service.js
src/app/core/reload.service.js
src/app/geo/geo.service.js
src/app/geo/init-map.directive.js
src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/app/layout/storage.service.js
src/app/ui/basemap/basemap.directive.js
src/app/ui/common/full-screen.service.js
src/app/ui/geosearch/geosearch-filters.service.js
src/app/ui/sidenav/sidenav.service.js
src/content/samples/index-mobile.tpl
webpack.common.js

- restores loading with initial bookmark
- fixes language switching problem (#1932)
- fixes a race condition between basemap and data layers (#1886)
- move ie polyfill loading before the main file, so polyfills are applied in time (#1905)
Close #1932, #1886, #1905
Some eyeballing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1938)

Bookmark v2

---

src/content/samples/blank.tpl

Injects css/js files for geoApi page testing
:eye: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1964)

fix(ui): inject css and js files into tpl

---

src/app/core/config.class.js
src/app/core/schema-upgrade.service.js
src/app/focus-manager.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/layout/shell.directive.js
src/app/ui/common/stepper/stepper-item.directive.js
src/app/ui/common/stepper/stepper.class.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/loader/loader-service.html
src/app/ui/toc/legend-block.directive.js
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.html
src/content/samples/config-mobile-2.json
src/content/samples/schema.json
src/content/styles/modules/_stepper.scss
src/content/styles/modules/_toc.scss
src/locales/translations.csv

Three PRs in one:
- add Feature layers as single dynamic
- option to disallow layer import
- option to hide layer from the legend UI, but still be displayed on the map
Involves changes to the schema.
Closes #1967, #1493 
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1968)

1493 feature as single dynamic + two more changes

---

package.json
src/content/samples/blank.tpl
src/content/samples/index-fgp-en.tpl
src/content/samples/index-fgp-fr.tpl
src/content/samples/index-mobile.tpl
webpack.common.js

Closes #1796
WOMM on prod builds and dev serve
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1975)

feat(build): add subresource integrity hashes to sample pages

---

package.json
src/app/app-loader.js
src/app/core/config.class.js
src/app/core/core.run.js
src/app/core/plugin.service.js
src/app/geo/map-tools.service.js
src/content/samples/index-fgp-en.tpl
src/content/samples/index-fgp-fr.tpl
src/content/samples/index-mobile.tpl
src/plugins/core/coord-info.js

Closes #1792
Add a plugin to get information about coordinates. In the same time solve a problem with DMS longitude coordinate
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1880)

feat(plugin) add coordinates info plugin

---

src/app/geo/legend-block.class.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/templates/legend-group.html
src/app/ui/toc/templates/legend-node.html
src/app/ui/toc/toc.html
src/content/samples/config-mobile-2.json
src/content/styles/modules/_toc.scss

- out-of-scale layers can now be zoomed to
- such layers behave well in visibility sets as well
Relates #1959
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1994)

Out-of-scale flags and controls

---

src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/ui/loader/layer-source.service.js

Used added flag is added to the layer defintion state.
Closes #1989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1995)

fix(ui): userAdded flag was missing on dynamic children

---

src/app/bootstrap.js
src/polyfill/ie-outer.HTML.js
webpack.common.js

IE limps on for another day...
Closes #1987
In ie, regrettably
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1996)

fix(ie): viewer now loads in IE11

---

src/app/geo/geo-search.service.js

#1855 Did option 2 for the time being.
Manually but no unit tests because unit testing on webpack is not working.
none.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1997)

Check for presence of serviceUrl and disable geosearch if absent

---

.eslintrc.yml
docs/developer/function.md
docs/developer/function/index.json
docs/developer/function/layer_import.md
src/app/core/bookmark.service.js
src/app/core/config.class.js
src/app/core/debounce.service.js
src/app/core/reload.service.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-block.class.js
src/app/ui/common/select-header.directive.js
src/app/ui/common/stepper/stepper.class.js
src/app/ui/common/svg.directive.js
src/app/ui/export/export-legend.service.js
src/app/ui/export/export.service.js
src/app/ui/loader/layer-source.service.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/panels/panel.directive.js
src/app/ui/sidenav/menulink.directive.js
src/app/ui/sidenav/sidenav.service.js
src/app/ui/toc/legend-block.directive.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toolbox/toolbox.directive.js
src/app/ui/tooltip/tooltip.directive.js
src/content/samples/config-mobile-2.json

Adds a new page to the docs and a bit of jsdoc comments.
Closes #1093
Nothing to test.
Yes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1982)

chore(docs): add docs for layer import and other comments

---

src/content/samples/config-sample-11-structured-legend-opacity-disable.json
src/content/samples/config-sample-12-structured-legend-opacity-locked.json
src/content/samples/config-sample-13-structured-legend-visibility-disable-locked.json
src/content/samples/config-sample-14-structured-legend-visibility-disable.json
src/content/samples/config-sample-15-structured-legend-visibility-locked.json
src/content/samples/index-samples.tpl

Change some of the wordings to let testers understand better their meanings
Visually
Some of the config files and `index-samples.tpl`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2013)

Change some of the wordings to let testers understand better their meanings

---

src/app/core/config.class.js
src/app/core/constant.service.js
src/app/ui/filters/filters-default-menu.directive.js
src/app/ui/filters/filters-default.directive.js

Closes #1974.
Also stores layers previous datatable size and reloads to that size instead of default size.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2006)

Correctly update datatable header and size

---

src/app/core/config.class.js
src/app/geo/geo-search.service.js
src/app/ui/appbar/appbar.directive.js
src/app/ui/appbar/appbar.html
src/app/ui/geosearch/geosearch-bar.directive.js
src/app/ui/geosearch/geosearch-filters.service.js
src/content/samples/index-samples.tpl
src/content/samples/schema.json

#2005, Fix console error relating to suggestions when Geo-search was disabled
Manually
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2012)

Fix console error relating to suggestions when Geo-search was disabled 

---

pull_request_template.md
src/app/core/config.class.js
src/app/layout/shell.directive.js
src/app/layout/shell.html
src/content/samples/config-mobile-2.json
src/content/samples/schema.json
src/locales/help/default/en-CA.md
src/locales/help/default/fr-CA.md

- set fullscreen config property so that focus pop up does not occur for `index-mobile.html`
- added ui -> fullscreen config entry
- corrected focus manager pop up translations issue
- updated PR template
Closes #2021, #1920, #1953
womm
:+1: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2025)

fix(ui): update docs and focus manager update

---

.travis.yml
package.json
protractor_tests/base-page.js
protractor_tests/conf.js
protractor_tests/sidePanel-page.js
protractor_tests/sidePanel-spec.js
scripts/protractor/killports.bat
scripts/protractor/run.js

Runs basic side panel test in chrome. Runs selenium server and webpack dev server concurrently for tests.
Will expand this to include IE and FF concurrent testing, as well as review chromes new headless state.
No
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1963)

feat(test): add initial protractor test support

---

src/content/samples/config-sample-17.json
src/content/samples/config-sample-18.json
src/content/samples/config-sample-19.json
src/content/samples/config-sample-20.json
src/content/samples/config-sample-21.json
src/content/samples/config-sample-22.json
src/content/samples/config-sample-23.json
src/content/samples/config-sample-24.json
src/content/samples/config-sample-25.json
src/content/samples/config-sample-26.json
src/content/samples/config-sample-27.json
src/content/samples/config-sample-28.json
src/content/samples/index-samples.tpl

#1786, add some of the samples that QA requested as well as a clear button for clearing the entered bookmark.
Manually.
`index-samples.tpl` and the required config files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2070)

Add samples

---

src/app/ui/filters/filters-default.directive.js
src/content/samples/config-mobile-2.json

Closes #2010 
Yep
Nope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2068)

fix(grid): Sort from config file not applied

---

src/app/ui/toc/legend-element-factory.class.js

Closes #2076, #2077.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2080)

fix(legend): datatable icon appearing for basemaps

---

package.json
src/app/core/constant.service.js
src/app/geo/init-map.directive.js
src/app/geo/map.service.js

Closes #2022, #2072
:eyes: and :keyboard: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2079)

fix(ui): re-enable custom key bindings

---

src/content/samples/config-sample-17.json
src/content/samples/config-sample-23.json
src/content/samples/config-sample-29.json
src/content/samples/config-sample-30.json
src/content/samples/config-sample-31.json
src/content/samples/config-sample-32.json
src/content/samples/config-sample-33.json
src/content/samples/index-samples.tpl

#1786 and fixes #2024.  Add more samples and fix the metadata not loading problem.
Manually 
`index-samples` and more config files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2091)

Add more samples and modify some config files

---

src/app/core/config.class.js
src/app/ui/sidenav/sidenav.service.js
src/content/samples/config-mobile-2.json

#2089, fix entry `about` on the sidenav.  If the required attributes were not given for `about`, the about panel would be blank.
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2100)

Fix entry-about on the side navigation

---

package.json
src/polyfill/polyfill-loader.js

Closes #2053
in ie with happy.json
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2103)

fix(polyfills): added TextDecoder to window in ie-polyfills.js

---

src/app/geo/legend.service.js

Closes #2102
:eye: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2110)

fix(ui): bounding box no longer permanent after reload

---

src/app/core/config.class.js
src/app/ui/sidenav/sidenav.html
src/content/samples/config/config-sample-01-structured-visibility-sets.json
src/content/samples/schema.json

Closes #2109
:eye: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2114)

feat(config): add option to specify app title

---

src/app/core/core.config.js

Closes #2124, #2125 .
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2127)

fix(filter): valid identifiers for datatable

---

src/content/styles/modules/_shell.scss

Closes #2063.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2130)

fix(bug): coordinates displaying in full screen

---

src/app/ui/filters/filters-default.directive.js

Closes #2135.
In-line comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2138)

fix(bug): export datatable with accented characters

---

src/content/samples/config/config-sample-41.json
src/content/samples/config/config-sample-42.json
src/content/samples/config/config-sample-43.json
src/content/samples/config/config-sample-44.json
src/content/samples/index-samples.tpl

#1786 Add samples as requested from the testers
Manually
`samples-index.tpl` and add more config files for samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2142)

Add samples for QA

---

src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/ui/filters/filters.service.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/toc.service.js

Closes #2036, #2017
Safari, Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2093)

fix(grids): Filter by extent doesn't work after refactor

---

src/app/core/common.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2154)

fix(common.service): add back $q and $timeout

---

src/content/styles/modules/_filters.scss
src/content/styles/vendor/_angularmaterial.scss

Closes #2098 
Fix when filter got truncated in IE
Manually
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2147)

Fix when filter got truncated in IE

---

src/app/ui/toc/legend-block.directive.js
src/app/ui/toc/templates/legend-node.html
src/content/samples/config/config-sample-01-structured-visibility-sets.json

Closes #2126
:eyes: on chrome
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2148)

fix(legend): menu can no longer be opened if empty

---

src/content/samples/config/config-sample-45.json
src/content/samples/index-samples.tpl

Adding page to allow testing when Lambert Basemaps go down
I did loadeth the page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2159)

Test Page - Mercator Only

---

src/content/samples/config.rcs.en-CA.json
src/content/samples/config.rcs.fr-CA.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2163
Tried out some prints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2164)

Full map export for fgp page

---

src/locales/translations.csv

Closes #2144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2180)

fix(export): wrong label for scale inside export setting

---

src/app/ui/table/setting-cluster.html
src/app/ui/table/table.service.js

Closes #2106 
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2179)

fix(table): apply on map for server user added layer

---

src/app/core/bookmark.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2161
Did some bookmarks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2185)

Bookmark with no layers

---

src/app/ui/table/table-definition.directive.js

Closes #2019 and any related parsing problems that may occur.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2166)

fix(datatable): parsing column names and filters

---

src/app/bootstrap.js
src/polyfill/ie-outer.HTML.js
src/polyfill/polyfill-loader.js

Close #2060 fix map export in IE by adding a poly fill module for `outerHtml`.
Manually
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2165)

Fix map export in IE

---

src/app/ui/table/table-default.directive.js

Closes #2141
:eyes: on chrome and FF
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2149)

fix(datatable): column headings scroll with body

---

schema.json
src/app/core/config.class.js
src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json

Closes #2050
`index-samples.html` with config #6 - Power Plants, nuclear has a custom title
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2158)

fix(grid): moved filters to children for dynamic layers

---

src/app/ui/table/table-default.directive.js
src/content/samples/config/config-sample-37.json
src/content/styles/modules/_table.scss
webpack.prod.js

No longer overflows its container. Test on config 37
Closes #2151
:eyes: on chrome
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2173)

fix(datatable): truncate long column headings

---

scripts/docdeploy.sh
webpack.prod.js

Fixes issue where build fails on tag push caused by doc deployment
Detached tag testing on travis
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2192)

chore(build): fix doc generation error on travis

---

src/app/core/core.config.js
src/app/ui/table/table.service.js

Closes #2199.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2204)

fix(datatable): parse date in filter correctly

---

src/app/ui/table/default-menu.html

Closes #2207.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2211)

fix(datatable): morph value displayed

---

src/app/core/config.class.js
src/app/ui/table/table-default.directive.js

Closes #2203
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2212)

fix(table): filters are applied more then once

---

src/app/ui/table/table-default.directive.js

As title and relating to #2084 
Manually 
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2208)

Fix filter setting not loading in IE

---

src/app/layout/layout.service.js
src/app/ui/table/table-default-menu.directive.js

Closes #2209.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2216)

fix(datatable): show and hide filters when appropriate

---

schema.json
src/app/core/config.class.js
src/app/geo/map.service.js
src/content/samples/config-mobile-2.json

Add customization to overview map component. Set expandFactor, disable/enable and set the layer to use. For the expand factor and layer to use work will have to be done inside geoApi
Chrome
Inline
- [] ~release notes have been updated~ no release page created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2206)

feat(overview): Add customization to overview component

---

src/app/ui/table/table.service.js

Closes #2205.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2221)

fix(filter): filtering by extent

---

src/content/styles/modules/_setting-controls.scss

Closes #2020 as title
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2220)

Add space between heading and slider in the opacity setting block

---

src/app/ui/table/table-default.directive.js

Closes #2201, #2217.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2223)

fix(datatable): column width readjusting

---

src/app/geo/legend-block.class.js

Visibility sets remember last selection when made visible by its parent.
Closes #2224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2228)

feat(ui): visibility sets remember last selection

---

src/content/samples/config.rcs.en-CA.json
src/content/samples/config.rcs.fr-CA.json
src/content/samples/index-fgp-en.tpl
src/content/samples/index-fgp-fr.tpl
src/content/samples/index-samples.tpl

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2231
Add B2C and a few other things to the FGP pages at test team's request
I tested the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2240)

Add Back2Cart Plugin to FGP Page

---

package.json

Updates geoApi to support temporary fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2234
Doing now so forest-fire team can utilze
Loaded layers with problem projections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2241)

geoApi update to support ESRI projections

---

src/app/ui/common/stepper/stepper.class.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/table/default.html
src/locales/translations.csv

fix(import): cancel when importing service issue resolved
fix(ui): space in datagrid title + geosearch option rename
Closes #2232, #2215, #1745
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2244)

Bug roundup

---

src/app/layout/layout.service.js
src/app/ui/table/table-default-menu.directive.js
src/app/ui/table/table.service.js
src/app/ui/toc/toc.service.js

Closes #2248 and #2249.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2251)

Datatable "Show Filters" functionality

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2255)

chore(build): disable protractor until tests are available

---

src/content/styles/modules/_geosearch.scss

Closes #1877 as title
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2256)

Make hovered Geo-location Search readable in IE

---

src/content/styles/modules/_table.scss

Closes #2222.
Visually tested on Chrome, FF, IE.
In-line comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2269)

fix(table): header scrolling with body

---

src/content/styles/modules/_table.scss

Closes #2276 
In-line comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2277)

fix(ui): remove clear button rendered in IE

---

CONTRIBUTING.md

Closes #2267 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2278)

chore(file): add back CONTRIBUTING.md file lost on v2.0.0

---

package.json
src/app/ui/loader/layer-source-info.class.js
src/app/ui/loader/loader-file.html

As title, and please see https://github.com/fgpv-vpgf/geoApi/pull/250 for the geoApi portion of this PR
Closes #2254, #2230 
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2270)

Strengthen CSV validation when importing as a layer

---

docs/user/working_examples.md
src/content/samples/iframe-map.tpl
src/content/samples/index-fgp-en.tpl
src/content/samples/index-iframe.tpl

- fullscreen is working with `allowfullscreen` property
- `index-fgp-en.html` used as a demo
- documentation updated
Closes #2264
jsdoc update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2283)

chore(demo): show viewer in an iframe

---

src/app/ui/panels/table-panel.html
src/app/ui/table/default.html
src/app/ui/table/setting-cluster.html
src/app/ui/table/setting-panel.html
src/app/ui/table/table-setting-panel.directive.js
src/app/ui/table/table.service.js
src/content/styles/modules/_table.scss
src/locales/translations.csv

Table settings is now its own panel. Flex style improvements.
Closes #2235
Chrome and IE
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2275)

fix(table): styling enhancements

---

src/app/core/formatters.filter.js

Adds a more robust checking to picture formatter.
Closes #2239
Eyeballs.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2290)

fix(core): fix null/undefined errors in picture formatter

---

package.json
src/app/geo/geo.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2214
I loaded a map and did things
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2295)

Fit map to extent

---

src/app/layout/shell.directive.js
src/app/ui/loader/loader-file.directive.js

Closes #2229.
Also fixes a small typo.
In-line comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2302)

fix(loader): display error message when importing json file

---

package.json

As title
This is used to test the changes made in geoApi
package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2301)

Update geoApi version that is being used in 2.1

---

schema.json
src/app/core/config.class.js
src/app/layout/shell.directive.js
src/app/layout/shell.html
src/app/ui/appbar/appbar.directive.js
src/app/ui/appbar/appbar.html
src/app/ui/geosearch/geosearch-bar.directive.js
src/app/ui/geosearch/geosearch-bar.html
src/app/ui/mapnav/mapnav.service.js
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/app/ui/sidenav/sidenav.service.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/samples/config/config-sample-46.json
src/content/samples/index-samples.tpl
src/content/styles/layout/_main.scss
src/content/styles/modules/_appbar.scss
src/content/styles/modules/_geosearch.scss
src/locales/translations.csv

For details, see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2246#issuecomment-320059569.
Closes #2246 
Inline comments in some places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2303)

2246 hide appbar

---

src/app/ui/table/table-default.directive.js
src/app/ui/table/table-setting-panel.directive.js

Closes #2119 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2309)

fix(table): reset table to original state when clearing sort

---

src/app/core/displaymanager.service.js

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2292
Manually 
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2310)

Remove error message when closing the data table from its own layer entry

---

src/app/ui/table/table-default.directive.js
src/content/styles/modules/_table.scss

Closes #2320 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2325)

fix(table): disable focus inside second header of table

---

schema.json
src/app/core/config.class.js
src/app/geo/layer-registry.service.js
src/content/samples/config/config-sample-47.json
src/content/samples/index-samples.tpl

As title.  Modify schema and add a sample of hover tips being turned off
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2001
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2231
Sample\#47
Add Sample\#47 and modify `index-samples.html`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2332)

Make on/off of hover tips configurable

---

package.json
src/app/geo/legend-block.class.js
src/app/geo/map.service.js
src/app/ui/details/details-record-esrifeature.directive.js

Adjusts calls to work with changes made in https://github.com/fgpv-vpgf/geoApi/pull/260
Tested against layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2340)

adjust to use new fetchGraphic

---

src/content/samples/index-samples.tpl

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2339
Manually in `index-samples.html`
`sample-index.tpl`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2341)

Fix up the tool header in index-sample

---

src/app/geo/metadata.service.js
src/app/layout/shell.directive.js
src/app/ui/metadata/metadata-content.directive.js
src/app/ui/toc/toc.service.js
src/content/samples/config/config-sample-29.json

Closes #2351.
Closes #2336.
Use sample 29 to test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2357)

Fix metadata and remove empty mouse info box

---

src/app/geo/init-map.directive.js
src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toc/templates/symbology-stack.html

Closes #2356 
Closes #2316 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2358)

2356 legend symbology and 2316 key binding

---

package.json
schema.json
src/app/core/config.class.js
src/app/geo/layer-blueprint.class.js
src/app/geo/legend.service.js
src/app/ui/table/table-default.directive.js
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.service.js
src/content/samples/config/config-sample-46.json
src/content/samples/index-samples.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2120, as title
Manually, try No. 46 in `index-samples`
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2354)

Apply filter to layers on the map on load

---

src/app/ui/export/export-legend.service.js
src/content/samples/config-mobile-2.json

Closes #2236 
Closes #2361 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2370)

2236 2361 legend export

---

package.json
src/app/geo/legend-block.class.js
src/content/samples/config/config-sample-03-structured-legend-one-child.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2364
Use the default name for the top level dynamic legend entry if the name is not provided in the config
Yes, see sample No. 3 in `index-samples`
No. 3 in `index-samples`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2371)

fix(legend): give a default name if not provided

---

docs/developer/technical/legend.md
package.json
src/app/geo/legend-block.class.js
src/app/ui/export/export-legend.service.js
src/app/ui/toc/templates/visibility-menu.directive.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/samples/config/config-sample-42.json

Closes #2327
To test you can use sample 42.
Legend documentation and in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2373)

2327 - Order of hidden legend blocks enforced

---

src/app/ui/toc/toc.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2379
Check whether config table exists before altering it.
Manually 
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2381)

Fix reload layer failing due to table config not being loaded

---

src/content/samples/config-mobile-3.json
src/content/samples/config-mobile.json
src/content/samples/config.en-CA.json
src/content/samples/config.fr-CA.json
src/content/samples/config.rcs.en-CA.json
src/content/samples/config.rcs.fr-CA.json
src/content/samples/config/config-sample-01-structured-visibility-sets.json
src/content/samples/config/config-sample-03-structured-legend-one-child.json
src/content/samples/config/config-sample-04-structured-legend-one-group.json
src/content/samples/config/config-sample-05-structured-nested-visibility-sets.json
src/content/samples/config/config-sample-06-structured-legend-dynamic-children-split-layers.json
src/content/samples/config/config-sample-07-structured-legend-one-group-proper-subset.json
src/content/samples/config/config-sample-08-structured-legend-one-layer-muti-legends.json
src/content/samples/config/config-sample-09-structured-legend-opacity-visibility-disable-locked.json
src/content/samples/config/config-sample-10-structured-legend-opacity-disable-locked.json
src/content/samples/config/config-sample-11-structured-legend-opacity-disable.json
src/content/samples/config/config-sample-12-structured-legend-opacity-locked.json
src/content/samples/config/config-sample-13-structured-legend-visibility-disable-locked.json
src/content/samples/config/config-sample-14-structured-legend-visibility-disable.json
src/content/samples/config/config-sample-15-structured-legend-visibility-locked.json
src/content/samples/config/config-sample-16-structured-legend-tile-layer-only-valid-one-proj.json
src/content/samples/config/config-sample-21.json
src/content/samples/config/config-sample-22.json
src/content/samples/config/config-sample-23.json
src/content/samples/config/config-sample-24.json
src/content/samples/config/config-sample-25.json
src/content/samples/config/config-sample-26.json
src/content/samples/config/config-sample-27.json
src/content/samples/config/config-sample-28.json
src/content/samples/config/config-sample-47.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2385
As title, done it for all the configuration files in the `samples` folder
Visually
Configuration files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2386)

Update config for legend initialization setting

---

src/app/ui/toc/toc.service.js
src/content/samples/config/config-sample-50.json
src/content/samples/index-samples.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2407
Relates https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2415
Add Sample No.50 for testers and the following
**Before**
**After**
Manually
`config-sample-50.json`, `index-samples.tpl`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2417)

Set 'isSelected' of legendBlock to false when removing and add samples

---

src/app/geo/map.service.js
src/content/samples/config/config-sample-01-structured-visibility-sets.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2397
As title
Visually using sample No.1 in index-samples
sample No.1 in index-samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2411)

Ensure attributions being shown

---

package.json
src/app/core/config.class.js
src/app/geo/legend.service.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/settings/settings-content.directive.js
src/app/ui/settings/settings-content.html
src/content/styles/modules/_setting-controls.scss
src/locales/translations.csv

Closes #332 
:eyes: 
To test, add any WMS layer and open the settings panel to change styles (Styles are only shown if there is more than 1 style available, otherwise the subheading is not shown)
This can be used: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities
Comments, JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2416)

Support for WMS additional styles

---

src/app/ui/export/export-legend.service.js

Closes #2392
Many :eyes: 's on chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2402)

feat(export): allow markdown in generated legend

---

src/app/core/config.service.js
src/app/ui/toc/templates/expand-menu.directive.js
src/app/ui/toc/templates/visibility-menu.directive.js
src/content/samples/index-samples.tpl

Follows `Proposal 2: Only Load Config Information For Current Language` from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/498
Closes #498
`index-sample.html` with and without RCS
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2414)

feat(config): only load config and RCS as needed.

---

src/content/samples/index-fgp-en.tpl
src/content/samples/index-fgp-fr.tpl
src/content/samples/index-mobile.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2434
Fix samples affected by #2424
Manually 
`index-sample`, `index-fgp-fr`, `index-fgp-en`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2435)

Fix samples safter PR 2424

---

webpack.common.js

Fixes IE
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2447)

apply babel to typescript loader

---

src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toc/templates/symbology-stack.html

Closes #2439
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2451)

symbology toggles for feature and dynamics only

---

src/app/layout/layout.service.js
src/app/layout/reference.service.js
src/app/layout/shell.directive.js
src/app/ui/geosearch/geosearch.directive.js
src/app/ui/table/table-default.directive.js

Closes #2446
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2459)

fix(layout): zoom to feature working with table maximized

---

src/app/ui/toc/symbology-stack.directive.js

Closes #2454
Chrome
inline
- [] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2462)

sync symbol alignment with symbol generation

---

src/content/samples/config/config-sample-52.json
src/content/samples/index-samples.tpl

Relates https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2478
This is a test
`index-samples`, `config-sample-52`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2480)

Add sample of disabled overview map

---

src/app/core/config.service.js

As title.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2442
http://fgpv.cloudapp.net/demo/users/barryytm/2.1.0-2442/dev/samples/index-samples.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2483)

Fix config switching

---

src/app/ui/lightbox/lightbox.directive.js

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2489
Test Layer: http://section917.cloudapp.net/arcgis/rest/services/JOSM/Oilsands/MapServer/0
Page to test: http://fgpv.cloudapp.net/demo/users/barryytm/2.1.x-2489/dev/samples/index-samples.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2490)

Enable URLs to open on feature details 

---

src/app/ui/export/export-legend.service.js

As title
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2393
http://fgpv.cloudapp.net/demo/users/barryytm/2.1.x-2393/dev/samples/index-mobile.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2495)

Resize Info section images on export 

---

src/app/ui/toc/symbology-stack.directive.js

Closes #2477
IE, Chrome
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2484)

fix(symbology): corrected vertical alignment for IE

---

docs/user/custom_attributes.md
src/app/ui/common/full-screen.service.js
src/app/ui/mapnav/mapnav.service.js
src/app/ui/sidenav/sidenav.service.js

Closes #2499 - worked with @barryytm to vaildate config loading and updated documentation for the supported config types
Also fixes small bug that didn't display the checkmark icon when in fullscreen
Updated `custom_attributes.md`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2508)

2499 config docs and small fullscreen update

---

src/locales/help/default/en-CA.md

As title, English fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2479
NA
`src/locales/help/default/en-CA.md`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2503)

Help file English update

---

src/app/ui/toc/templates/symbology-stack.html
src/locales/translations.csv

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2517
Add the missing aria-labels and tool-tips for legend stacks (i.e. legends of a legend)
http://fgpv.cloudapp.net/demo/users/barryytm/2.1.1-2517/dev/samples/index-samples.html sample 2
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2520)

Add aria-label and tool-tips for legend stacks 

---

src/app/ui/sidenav/sidenav.service.js

Fix the issue with bookmark link not showing up on `SHARE`.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2497
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2509)

Fix share link

---

src/app/ui/export/export-component.class.js

Remove options with no value in the export settings
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2501
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2506)

Remove options in export settings with no value

---

src/content/styles/modules/_table.scss

As title and increase the maximum height allowance.
Closes #2460 
http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/happyEnhance.json
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2516)

Make height of cells in DataTable more flexible

---

src/locales/help/default/fr-CA.md

Improve French quality in French help file
Link to #2479 
Tested in chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2502)

Help file French update

---

api/src/events.ts
api/src/map.ts
api/src/ui.ts
package-lock.json
package.json
scripts/webpack/schema_validation_plugin.js
src/app/core/statemanager.service.js
src/app/geo/init-map.directive.js
src/app/geo/layer-registry.service.js
src/app/ui/panels/panel.directive.js
src/app/ui/tooltip/tooltip.service.js

- adds api support for panels: open/close, node content replacement, and event streams (opening/closing/opened/closed).
- adds api support for tool tips: allows hover tool tips to be modified in flight with new `attribs` property from geoApi. Also allows any number of tool tips to be placed on the map with custom content.
- Need to add support for swapping context map (mini map) contents with custom code (for cip highcharts). Ability to open/close among others. 
- UI anchor points need to be defined
- Enable support for stoppable panel events (on opening/closing). Some code is in but not enabled.
- Popup (modal) window support
- More panels (?) - Current support the major three (main, side, table)
- Legend manipulation. This is likely a lot of work and would need extensive analysis on its …

API: add UI support for panels and tooltips

---

api/src/map.ts
src/app/ui/export/export.service.js

CIP Task 35976
Exposes function `export` on the API `Map` class to trigger the export screen.
Tested using the API in the browser.
WOIE11™
API docs via docstrings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2552)

API - trigger export window

---

api/src/events.ts
api/src/map.ts
api/src/ui.ts
api/theme/assets/js/custom.js
src/app/geo/identify.service.js
src/app/geo/map.service.js

```js
mapInstance.identify = false;
```
```js
RZ.mapInstances[0].click.subscribe(a => {
a.features.subscribe(featureList => {...});
});
```
Yes, definitely 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2550)

API-04: Enable/disable identify & add ability to observe map click features

---

src/content/samples/api-export.tpl
src/content/samples/config.api.basic.en-CA.json

Sample page for Export API
Worth discussing: 
Will probably be first of many sample pages for API. 
* Worth making a subfolder for them? (Would require updates to the build process)
* How robust to make these? Should I add french config? Full cleanup of unused code from previous sample I copied?
Tested page in browser (one click).
WOIE11™
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2556)

Sample page for export

---

README.md
api/src/events.ts
api/src/geometry.ts
api/src/index.d.ts
api/src/map.ts
api/src/ui.ts
api/welcome.md
package-lock.json
package.json
src/app/app-loader.js
src/app/app-seed.ts
src/app/bootstrap.js
webpack.common.js
webpack.config.js

- fixes import ordering issue between `bootstrap` and `app-seed`
- adds warning to all new API files - only use core devs should be using it now
- Implements webpack tooling to help identify code and dependencies we can remove/change to decrease overall bundle size. See the readme for instructions.
WOMM
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2564)

fix(bootstrap): loading in correct order

---

schema.json
src/app/core/config.class.js
src/app/ui/common/north-arrow.directive.js
src/content/samples/config/config-sample-55.json
src/content/samples/index-samples.tpl

Closes #2541 
Make north arrow configurable and support both url and base64 data.
sample 55
http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2541/dev/samples/index-samples.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2570)

Make north arrow configurable

---

src/app/ui/toc/symbology-stack.directive.js

Closes #2567 
Get rid of the layer record undefined error simply by checking its existence.
Manually by clicking on symbols on the map.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2573)

Get rid of the layer record undefined error

---

src/locales/translations.csv

Closes #2560 
Add French translations.  All words/sentences were translated by [Translation Bureau](https://portage-preprod.pwgsc.gc.ca/index-eng.php).
NA
`translations.csv`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2572)

Add French translations

---

api/src/geometry.ts
api/src/map.ts
src/app/focus-manager.js
src/app/geo/init-map.directive.js
src/content/samples/api/self-loading/self-loader.js

Change timing of api event calling.
Closes #2577, #2575, #2561
`samples/api.html`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2576)

fix(api): change event timing

---

api/src/layers.ts
api/src/map.ts
package.json
src/app/api-loader.ts
src/app/geo/layer-registry.service.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/ui/settings/settings-content.directive.js
src/app/ui/settings/settings-content.html
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js

Starts implementation of #2571:
- Adding layers using JSON snippet, removing layers through API. 
- Adding / removing observables 
- Attribute observables
- Layer click in legend observable
- Other small functions
NOTE: Still need to implement adding of layers by other methods (GeoJSON, url, etc.)
```js
RZ.mapInstances[0].layers.layerAdded.subscribe(layer => console.log(layer));
RZ.mapInstances[0].layers.addLayer(<JSONSnippet>);
RZ.mapInstances[0].layers.allLayers; // array of all layers
RZ.mapInstances[0].layers.getLayersById('<layerId>').forEach(...);
RZ.mapInstances[0].layers.attributesAdded.subscribe(attrib => console.log(attrib));
RZ.mapInstances[0].layers.click.subscribe(layer => console.log(layer)); // click on layer in legend
// So on and so forth
``` …

Api 05 - Layer Group

---

src/content/styles/modules/_table.scss

Override any template styles of text in data grid
Closes #2515
Visually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2582)

Increase visibility of texts in data grid

---

api/src/layers.ts
api/src/map.ts
package-lock.json
src/app/geo/identify.service.js
src/app/geo/map.service.js

Specifies four different identify modes: details, highlight, silent and none. See #2595 for more details.
Setting identify mode to `none` can disable the identify functionality at runtime as described in #1985.
1. load `index-samples` page
2. type `RZ.mapInstances[0].identifyMode` in the console // identify mode defaults to 'details'
3. click on things, see them get highlighted and displayed in the details panel
4. type the following in the console (this will remove all but one result from each sublayer)
```ts
RZ.mapInstances[0].identify.subscribe(identifyResults =>
identifyResults.forEach(result => {
if (result.data.length > 0) {
result.data.splice(1);
}
})
);
```
5. click on things, see only one feature get highlighted and displayed in the details panel
6. type …

feat(identify): improvements to identify flow

---

api/src/map.ts
src/app/core/config.class.js
src/app/geo/init-map.directive.js
src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js
src/app/ui/toc/toc.directive.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2616.
Layers added through the API will not be automatically added to the legend for structured legends.
For auto, they will be added as they normally would.
The existing structured legends can now be updated through a setter on the API map Instance by providing the JSON for the layer definitions to be added to the legend.
Any layer that is no longer in the legend will be removed from the map as well (this can be changed if required).
Basic examples below;
```js
EXAMPLE 1
var mapInstance = RZ.mapInstances[0];
var sLegend = [];
sLegend.push({"layerId": "crops"}); // adds to the end
sLegend.unshift( // adds a group to the top of the legend
{
"name": "A Group with a Visibility Set",
"expanded": true,
"controls": ["visibility"],
"children": …
```

Api 10 (Structured Legends)

---

package-lock.json
src/app/layout/shell.html
src/app/ui/common/dialog.decorator.js
src/content/styles/modules/_shell.scss

Wraps map components in an inner shell to help with positioning them in a specified region while allowing the map to spill out and fill the map shell container.
CIP requirement.
Relates #2622
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2623)

feat(layout): add inner shell container

---

src/app/core/config.class.js
src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js
src/app/ui/export/export-sizes.service.js
src/app/ui/export/export.html
src/app/ui/export/export.service.js
src/app/ui/sidenav/sidenav.service.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/templates/legend-control-input.html
src/content/styles/modules/_toc.scss
src/plugins/core/coord-info.js

Closes #2619 - generate option enabled again on switch
Closes #2620 - refresh intervals fixed for dynamic single entry collapsed
Closes #2633 - removed outline
Closes #2636 - rcs keys loading correctly
Closes #2639 - tooltips for file-based layers
Closes #2643 - translate datepicker options
Closes #2645 - coords info pop-up window appears
:eyes: 
In-line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2646)

bugs galore

---

src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toc/templates/legend-info.html
src/app/ui/toc/templates/symbology-stack.html
src/content/samples/config-mobile-2.json
src/content/samples/index-mobile.tpl
src/content/styles/modules/_symbology.scss

Implements the cover image for symbology stacks.
Closes #2650
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2651)

feat(ui): implement symbology stack cover icon

---

package.json
src/app/core/constant.service.js
src/app/geo/map.service.js
src/app/geo/overview-toggle.directive.js
src/content/samples/config/config-sample-58.json
src/content/samples/index-samples.tpl
src/locales/translations.csv

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/497
Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/107
:eyes: - testing different features like importing files / services, changing languages, projections, etc.
Can be tested on Sample 58 - the initial basemap fails to load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2661)

fix(basemap): load app normally on initial basemap fail

---

src/content/samples/config/config-sample-02-structured-legend-controlled-layers.json
src/content/samples/config/config-sample-32.json
src/content/samples/config/config-sample-33.json

Closes #2687 
Fix samples with not working services.
Visually
Samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2688)

Fix samples with not working services.

---

package-lock.json
schema.json
src/app/geo/map.service.js
src/content/samples/config/config-sample-62.json
src/content/samples/index-samples.tpl
src/content/styles/modules/_core.scss
src/content/styles/vendor/_esri.scss

Closes #2695
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2696)

fix(map): fix unexpected behaviour with attribution

---

package-lock.json
package.json
src/app/geo/map-tools.service.js
src/app/layout/shell.html
src/app/ui/common/north-arrow.directive.js

Closes #2678 
Change flag to use geometry api.
Add ability to specify top offset for the north arrow. 
Tested manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2714)

North arrow top offset and flag to geometry api

---

src/app/bootstrap.js
src/app/core/bookmark.service.js
src/app/core/config.service.js
src/app/core/core.run.js
src/app/core/displaymanager.service.js
src/app/focus-manager.js
src/app/geo/gapi.service.js
src/app/geo/geo.service.js
src/app/geo/identify.service.js
src/app/ui/common/dragula.directive.js
src/app/ui/common/stepper/stepper.class.js
src/app/ui/export/export-generators.service.js
src/app/ui/geosearch/geosearch-filters.service.js
src/app/ui/help/help.service.js
src/app/ui/loader/layer-source.service.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/sidenav/sidenav.service.js
src/app/ui/table/table-default.directive.js
src/app/ui/toc/toc.service.js
src/app/ui/tooltip/tooltip.service.js
src/content/samples/extensions/extension.js
webpack.prod.js

Closes #2629 
Console output was verbose for production builds. 
Clean the production build so that the console only outputs errors and warnings. 
Tested manually. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2720)

Clean debug statements in production code

---

src/locales/translations.csv

Closes #2703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2731)

fix(translation): Fix bad French translation

---

src/app/core/config.service.js
src/app/ui/common/error.service.js

Closes #593
:eyes: 
in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2729)

fix RCS error messages not appearing/appearing twice 

---

docs/developer/technical/bookmark_formats.md

Brought bookmark guide to a whole new level of glory
Many unit tests added.
The file I changed is the documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2735)

Major update to bookmark guide

---

package.json
schema.json
src/app/core/config.class.js
src/content/samples/config/config-sample-65.json
src/content/samples/index-samples.tpl

Closes #2463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2728)

feat(basemap): Set opacity on layer of array of layers

---

src/app/core/config.class.js
src/app/core/config.service.js
src/content/samples/index-samples.tpl

Closes #754
:eyes:
Config `67. Map with no config provided` in index-samples
in-line commenting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2743)

Default behaviour when no config is provided 

---

src/app/ui/sidenav/sidenav.html

App would try to do the redirect in the iframe.
Now the app will redirect the parent page to the github source page.
Closes #2666 
:eyes:
using `index-iframe.html`
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2744)

fix(ui): fix github page hyperlink when in iframe

---

src/app/global-registry.js

Closes #1153, #2727
:eyes:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2746)

Update viewer to use ESRI JS API 3.24

---

src/app/geo/legend-block.class.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/templates/legend-control-slider.html
src/content/styles/modules/_setting-controls.scss
src/locales/translations.csv

Closes #2535
:eyes:
index-sample.html - Sample 4
In-line commenting 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2752)

Add label to show that child opacity values differ from parent

---

src/app/ui/tooltip/tooltip.service.js

Closes #2754
Hovertip would flicker for any point near the edges of the viewer. 
Now does not flicker and properly repositions itself.
:eyes: 
http://fgpv.cloudapp.net/demo/users/dane-thomas/hovertip-flicker/dev/samples/index-fgp-en.html?keys=JOSM
For geometry api points w/ hovertips: 
```javascript
const pointA = new RZ.GEO.Point(0, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-110, 43]);
const pointB = new RZ.GEO.Point(1, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-100, 43]);
const pointC = new RZ.GEO.Point(2, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-90, 43]);
const pointD = new RZ.GEO.Point(3, 'https://image.flaticon.com/icons/svg/17/17799.svg', [-80, 43]);
// create hovertip instances and add them to the different points
const hoverA = new …
```

fix(ui): flickering hovertip near edges

---

package-lock.json
schema.json
src/app/app-loader.js
src/app/core/config.class.js
src/app/core/core.run.js
src/app/core/plugin.service.js
src/content/samples/config/config-sample-64.json
src/content/samples/index-samples.tpl
src/content/styles/modules/_buttons.scss
src/plugins/core/area-of-interest.js

Closes #2709
Add the area of interest plugin
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2725)

feat(plugin): Add bookmark plugin

---

src/app/geo/map.service.js
src/content/samples/config/config-sample-66.json
src/content/samples/index-samples.tpl

Closes #1320
:eyes:
Config `66. Map with navigation restricted` in index-samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2742)

Allow viewer to have map extent restricted

---

src/plugins/core/area-of-interest.js

Closes #2759
Update CSS to display on mobile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2761)

fix(aoi): fix area of interest plugin display for mobile

---

src/app/global-registry.js

Issues occurring with layer loading (more specifically, file-based layers) in 3.23 and above.
:eyes: 
In-line comment explaining reasoning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2762)

Drop ESRI API version to 3.22

---

src/app/core/constant.service.js
src/app/core/reload.service.js
src/app/geo/layer-registry.service.js
src/app/ui/common/dragula.directive.js
src/app/ui/toc/toc.directive.js

Closes #2777 
Fix layer positioning error when switching projection or language by recreating and recompiling the dragular instance.
Tested Sample 59
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2782)

Fix layer positioning error when switching projection or language 

---

docs/index.html
package.json

Bump version tag in and update geoApi in package.json.  As well as update the link for JsDocs.
Sanity check
JsDocs link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2791)

Prepare for v2.4.0 relese

---

src/app/geo/identify.service.js
src/app/geo/map.service.js

Closes #2785
:eyes: 
in-line commenting 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2789)

Fix highlights not working for keyboard based identify

---

src/app/geo/map.service.js

Closes #2599
With the changes mentioned in #2599 this was pretty much already done in #2740. Just updated to use the `IdentifyMode` constant.
:eyes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2783)

refactor(map): don't change cursor to hand when identify mode is silent

---

docs/developer/release_tutorial.md
docs/index.html

Cloeses #2796 
Tutorial on how to do a release.
NA
`index.html`, `release_tutorial.md`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2802)

Release tutorial

---

src/app/ui/common/crosshairs.directive.js
webpack.config.js

The crosshairs image does not load quick enough and its size is returned as 24x24 pixels. Deffer getting the dimensions until the first keyboard-caused extent change.
Closes #2809
:eye: 
~~- [ ] Help files and documentation have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2810)

fix(ui): fix keyboard identify tooltip position

---

src/content/styles/modules/_appbar.scss
src/locales/translations.csv

Closes: #2467
:eyes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2811)

fix(ui): identify appbar title not being truncated

---

schema.json
src/app/core/config.class.js
src/app/core/config.service.js
src/app/core/core.run.js
src/app/geo/gapi.service.js
src/app/global-registry.js
src/content/samples/config/config-sample-71.json
src/content/samples/index-samples.tpl

Closes #2654
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2816)

feat(core): load esri api from custom location

---

schema.json
src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/ui/toc/symbology-stack.directive.js
src/content/samples/config/config-sample-72.json
src/content/samples/index-samples.tpl

Closes #2800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2822)

feat(legend): Expand symbology stack from config file

---

api/src/schema.d.ts
docs/user/details_templating.md
schema.json
src/app/core/config.class.js
src/app/ui/details/details-record-esrifeature-item.directive.js
src/app/ui/details/details-record-esrifeature-item.html
src/app/ui/details/details-record-html.directive.js
src/app/ui/details/details-record-html.html
src/app/ui/details/details-record-text.directive.js
src/app/ui/details/details-record-text.html
src/content/samples/config/config-sample-70.json

Relates https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2847
Sample 70, add something like `#/?abc` to the end of the url, click for identify, url should remain untouched.
Updated the details templating doc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2848)

fix(details): appease angular, rename templateUrl

---

api/src/schema.d.ts
package.json
schema.json
src/app/core/config.class.js
src/app/geo/layer-blueprint.class.js
src/app/geo/map.service.js
src/app/ui/loader/layer-source.service.js
src/content/samples/config/config-sample-73-corsEverywhere.json
src/content/samples/index-samples.tpl

#2833 
Remember, it is a *muffin offence* to open a PR with all of the above checklist items incomplete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2851)

Cors everywhere

---

src/app/ui/details/detail.service.js
src/app/ui/details/details-record-esrifeature-item.directive.js
src/app/ui/details/details-record-esrifeature-item.html
src/app/ui/details/details-record-html.directive.js
src/app/ui/details/details-record-html.html
src/app/ui/details/details-record-text.directive.js
src/app/ui/details/details-record-text.html
src/content/samples/templates/test-template.1.html
src/content/samples/templates/test-template.html
src/content/styles/modules/_appbar.scss

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2847
Turns out it wasnt `templateUrl` it was `ngInclude`.
We now manually compile the angular templates.
Sample 70 as before.
comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2852)

Details templates the third

---

src/app/ui/loader/layer-source.service.js

Retain url parameters when loading WFS data.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2855
Local testing with modified config.
NOTE: things break in auto-legend (different reason; will be adding new issue)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2856)

Retain url params on wfs load

---

package-lock.json

Update package-lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2868)

chore(build): update package-lock

---

src/app/geo/legend.service.js

Race-like situation where layers added via API would be ignored by legend blueprinter early on, but would be recognized later, and thus causing blueprints to be created twice, causing mayhem.
Added a check to prevent a 2nd creation.
Tested locally on RAMP.  Also tested on CCCS viewer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2869)

Prevent double blueprint race

---

src/app/geo/geo.service.js
src/content/samples/index-fgp-en.tpl
src/content/samples/index-fgp-fr.tpl

Closes #2842
:eyes: 
Updates to `index-fgp-en` and `index-fgp-fr`
Open either page with an RCS query (e.g. `?keys=JOSM`) and use the language switcher in the top right corner of the page. 
in-line documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2854)

fix(geo): RCS Layers disappear when using WET Language Toggle

---

src/app/ui/common/full-screen.service.js

Closes #2558
:eyes:
Follow instructions to reproduce in issue above. 
in-line commenting; JS docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2831)

fix(ui): fix fullscreen re-centering trap

---

src/app/ui/toc/symbology-stack.directive.js
src/content/samples/config/config-sample-72.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2857
sample 72 in
http://fgpv.cloudapp.net/demo/users/barryytm/v2.5.0-2857/dev/samples/index-samples.html 
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2882)

Increase symbol stack offset

---

api/src/schema.d.ts
package-lock.json
schema.json
src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/templates/legend-info.html
src/app/ui/toc/toc.html
src/content/samples/config/config-sample-74.json
src/content/samples/index-samples.tpl
src/content/styles/modules/_toc.scss

- adds `hidden` option to the `layerGroup` schema definition (the code assumed it is possible anyway)
- adds `content` option to the `unboundLayer` to replace `layerName` in the future #2894
- add `collapse` option to the `visiblitySet` to display only the currently selected entry #2896 
Closes #2894 #2896 
👓 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2897)

2894 2896 visibility set enhancements

---

api/src/schema.d.ts
package-lock.json
package.json
schema.json
src/app/core/config.class.js
src/app/ui/loader/loader-file.html
src/app/ui/loader/loader-service.html
src/app/ui/sidenav/sidenav.service.js
src/content/samples/config/config-sample-75.json
src/content/samples/index-samples.tpl
src/locales/translations.csv
webpack.common.js

Closes #2866 
May still need to do #2900 
Also re-fixes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2643
Note: Dev build broken, only prod working
:eyes: - Sample 75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2903)

Dynamic layer field name configuration 

---

src/app/core/config.class.js
src/app/geo/layer-blueprint.class.js

This is related to #2859.
As part of simplifying the `LayerBlueprint` logic to better accommodate WFS layers, the generating of table filter definitions code is moved from `layer-blueprint` to `config-class`.
👁 
Not required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2904)

refactor(config): move setting table filter definitions to config class 

---

src/app/ui/toc/legend-control.directive.js
src/app/ui/toc/templates/legend-control-body.html
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.html

Closes #2840
Check element `rv-legend-block` to see if it has `role = "button"`.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2892)

Move event from toc to legend control

---

api/src/map.ts
src/app/ui/help/help.service.js

Adds an API function to open the Help dialog (similar to the API call to open the Export dialog).
Closes #2914
:eye: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2915)

feat(api): add open help through API call

---

src/content/styles/layout/_main.scss

relates #2910 missed a couple z-indices
Needed for CCCS integrations (and is useful to have for future work)
CSS inspection in dev tools
Not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2916)

fix(styles): raise table panel properly

---

src/app/ui/toc/symbology-stack.directive.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2895.
Symbology stack with images would disappear upon clicking it. This PR allows it to expand properly.
Expand **"How to Catch Santa"** Symbology Stack
[current develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html) : legend entry disappears 
vs 
[this PR](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/unbound-disappear/dev/samples/index-mobile.html) : legend entry expands properly
--- …

fix(symbology): symbology stack with images expands

---

docs/api/user-documentation.md
docs/index.html

Closes #2641 
[:scroll: Docs Demo](https://dane-thomas.github.io/fgpv-vpgf/docs/#/api/user-documentation)
API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2913)

chore(docs): add user api documentaion

---

api/src/map.ts
src/content/samples/aoi-demo-nopics.html
src/content/samples/aoi-demo-pics.html
src/content/samples/config/config-sample-64.json
src/content/samples/config/config-sample-73.json
src/content/samples/extensions/areaOfInterest.js
src/content/samples/index-samples.tpl

Starts on #2787.  
***Note:*** This extension is not complete as of yet (not possible until all panels are moved to the Panel API).  For future features refer to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2881
***New Features:*** Areas of Interest Extension to replace the old plugin: 
- [Pictures Demo](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/areas-of-interest-extension/dev/samples/aoi-demo-pics.html)
- [No Pictures Demo](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/areas-of-interest-extension/dev/samples/aoi-demo-nopics.html)
**Changes in Extensions Repo**: [here](https://github.com/fgpv-vpgf/extensions/pull/4/files)
See above demos.
- Title should change on language switch
Remember, it is a *muffin offence* to open a PR with any of the above checklist …

feat(extension): fixes to config, schema, and new extension

---

api/src/schema.d.ts
package-lock.json
package.json
schema.json
src/app/core/config.class.js
src/content/samples/config/config-sample-76.json
src/content/samples/index-samples.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2878
Config support for custom renderers on Feature / WFS / File layers
Test file 76
Config schema doc strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2917)

Custom renderer support

---

api/src/schema.d.ts
schema.json
src/app/core/config.class.js
src/app/geo/layer-blueprint.class.ts
src/content/samples/config/config-sample-81.json
src/content/samples/index-samples.tpl

Config option to copy point co-ordinates in WFS layers into the attributes section
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2921
Test File 81
Config schema doc and lovely inline comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2940)

Option for wfs points in attributes

---

src/app/geo/layer-blueprint.class.ts

A line got deleted during the layer blueprint refactor.
Added in a fix that appears to be working.
Tested with specific failing config from CCCS viewer. 
Tested existing CORS test case and "all layers" test case for refactored blueprints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2947)

Re-added deleted cors support

---

src/content/samples/index-samples.tpl

Closes #2920 
Feature a key to specify which sample to load in `index-samples.html`.
http://fgpv.cloudapp.net/demo/users/barryytm/2920/dev/samples/index-samples.html
http://fgpv.cloudapp.net/demo/users/barryytm/2920/dev/samples/index-samples.html?sample=5
Tested on IE and Firefox as well
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2926)

Sample loading with a key

---

api/src/legend.ts
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/ui/toc/symbology-stack.directive.js

Starts on https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2932
:eyes: 
JSDoc, in-line comments
- ~~~[ ] Release notes have been updated~~~
- ~~~[ ] Help files and documentation have been updated~~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2948)

2932 LegendGroup API

---

api/src/layers.ts
api/src/legend.ts
api/src/map.ts
api/src/ui.ts
src/app/core/config.class.js
src/app/geo/init-map.directive.js
src/app/geo/legend.service.js
src/app/ui/toc/legend-control.directive.js
src/app/ui/toc/templates/expand-menu.directive.js
src/app/ui/toc/templates/visibility-menu.directive.js

Starts on #2934 #2933
:eyes:
TSDoc, in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2953)

feat(LegendAPI): added BaseLegend and ConfigLegend

---

api/src/legend.ts
api/src/map.ts
package-lock.json
src/app/core/config.class.js
src/app/geo/init-map.directive.js
src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js

Adds ability to reorder legend through the API
Index sample 57
in-line commenting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2956)

feat(legendAPI): layer reordering

---

api/src/legend.ts
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/ui/toc/symbology-stack.directive.js

Continues with https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2932 and related API legend work
:eyes: 
JSDoc, in-line comments
- ~~~[ ] Release notes have been updated~~~
- ~~~[ ] Help files and documentation have been updated~~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2959)

feat(legendAPI): fix loading of dynamic children

---

package-lock.json
src/app/focus-manager.js

Presents the page from snapping to the top when opening the Settings or Metadata panel, or expanding a symbology stack using a mouse.
Closes #2969
:eye: 
Not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2970)

fix(ui): prevent page jumping

---

api/src/legend.ts
src/app/geo/legend.service.js
src/app/ui/toc/toc.service.js

Add remove capabilities to the legend API
:eyes: - any sample!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2968)

feat(legendAPI): add remove capabilities

---

api/src/layers.ts
src/app/geo/identify.service.js
src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/app/ui/details/details-record-esrifeature.directive.js
src/app/ui/details/details-record-html.directive.js
src/app/ui/details/details-record-text.directive.js

Enhances identify mode. Read #2979 for details.
Closes #2979
:eyes: 
Use sample 75 - it has all layer types. Try examples of the identify mode from the issue linked or any other combination of options and click on map/features.
You can set the `identifyMode` like this:
```js
RZ.mapInstances[0].layers.identifyMode = ['query', 'marker', 'highlight']
```
--- …

feat(api): enhance identify mode

---

src/app/ui/toc/templates/symbology-stack.html
src/content/styles/modules/_symbology.scss

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2942
http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/halo-symbology/dev/samples/index-samples.html?keys=JOSM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2958)

fix(symbology): remove black halo from symbology stack

---

api/src/schema.d.ts
schema.json
src/app/core/config.class.js
src/app/geo/legend-block.class.js
src/app/ui/export/export-legend.service.js
src/content/samples/config/config-sample-77.json

#2989 
Sample 77
schema descriptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2990)

feat(ui): info sections can be omitted in export

---

api/src/schema.d.ts
schema.json
src/app/core/config.class.js
src/app/ui/common/failure-image.directive.js
src/app/ui/export/export-component.class.js
src/app/ui/export/export-components.service.js
src/app/ui/export/export-generators.service.js
src/app/ui/export/export.html
src/app/ui/export/export.service.js
src/content/samples/config/config-sample-01-structured-visibility-sets.json
src/locales/translations.csv

Adds a timeout to the map export generation.
Closes #2997
- open sample 01 (timeout is set to 5sec there) and throttle your network to slow:
- open export dialogue
- wait 5sec and observe the "timeout" error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2998)

feat(core): add export map timeout

---

api/src/legend.ts
src/app/geo/legend.service.js

Syncs viewer-side and API reloads in order to update corresponding `LegendGroups` or `LegendItems` in the legend.
Test multiple samples thoroughly! :eyes:
Hint: sample 75 is a particularly good sample to test on.
**Checklist:**
- Do the `children` lists in the Legend get updated properly?
- Do the `_sortGroups` get updated properly?
- Do all the `LegendItems`/`LegendGroups` match with their `_legendBlock` property?
- Does setting `configSnippets` update the map and reload the nodes successfully? i.e.
- no duplicate elements in `children` and `_sortGroup` lists
- `LegendGroups`/`LegendItems` should have new `ids` as if reloaded
- Does importing layers work properly?  [good layer](http://maps-cartes.ec.gc.ca/arcgis/rest/services/NPRI_FGP_All_Layers/MapServer/8) to test on
- Are dynamic …

Sync viewerside reloads with Legend API

---

src/locales/translations.csv

Official french received alongside CCCS strings
Looks like french
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3007)

Add more official french translations

---

src/app/ui/sidenav/about-dialog.html
src/app/ui/sidenav/sidenav.service.js

Closes #2964 
:eyes: index-mobile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3002)

fix(ui): about dialog no content image briefly shown

---

package-lock.json
src/app/geo/layer-blueprint.class.ts
src/app/geo/layer-registry.service.js
src/app/geo/legend-block.class.js
src/app/ui/sidenav/about-dialog.html
src/content/styles/modules/_about.scss
src/content/styles/modules/_all.scss
src/content/styles/modules/_side-nav.scss

Fixes out-of-memory crash.
Closes #3006
Open `index-mobiles`. If it loads and your browser didn't crash, it's working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3008)

3006 out of memory crash

---

src/app/ui/export/export-legend.service.js
src/content/samples/config/config-sample-77.json

#3012 
Sample 77, export and see info sections not being cut off. Output should look similar between browsers.
Comments, headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3013)

Export legend

---

src/app/geo/init-map.directive.js
src/app/tag-manager.js
src/app/ui/common/expand-image-dialog.html
src/app/ui/common/expand-image.directive.js

Expand image buttons were always appearing. Slightly altered how the legend panels width is being retrieved.
Also fixes a couple bugs when `rz-gtm` is not specified, some calls to google tag manager were still trying to get through.
Tested sample 67 to make sure the expand image button still appears when needed, testing in CCCS to make sure that bug goes away.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3024)

Expand image

---

src/locales/translations.csv

The label was not in label format
The b is capitalized
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3028)

chore(lang): capitalize b in Blank map

---

api/src/legend.ts
src/app/geo/legend.service.js
src/content/samples/config/config-sample-90-api.json
src/content/samples/index-samples.tpl

Refactor Legend API code
- Created `BaseItem` as a parent for `LegendItem` and `LegendGroup`
- Refactored `updateApiReloadedBlock` to fix reload issue 
- Updated some of the documentation and added a couple examples
:eyes:
TypeDocs and in line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3038)

Refactor Legend Api

---

src/app/ui/table/table.service.js
src/app/ui/toc/symbology-stack.directive.js

Closes #2438 
:eyes:
Can test with [JOSM](http://fgpv.cloudapp.net/demo/users/dane-thomas/symbol-grid-filter/dev/samples/index-fgp-en.html?keys=JOSM), [CESI](http://fgpv.cloudapp.net/demo/users/dane-thomas/symbol-grid-filter/dev/samples/index-fgp-en.html?keys=CESI_Other), [NPRI](http://fgpv.cloudapp.net/demo/users/dane-thomas/symbol-grid-filter/dev/samples/index-fgp-en.html?keys=NPRI_CO) 
Also sample 46
Basically any layer with toggle symbology and a datatable
--- …

feat(ui): synchronize grid and symbol filters on map

---

src/content/samples/api/legendTests/ConfigLegendTests/children-tests.html
src/content/samples/api/legendTests/ConfigLegendTests/children-tests.js
src/content/samples/api/legendTests/ConfigLegendTests/config-snippet-position.html
src/content/samples/api/legendTests/ConfigLegendTests/config-snippet-position.js
src/content/samples/api/legendTests/ConfigLegendTests/visibility-click-tests.html
src/content/samples/api/legendTests/ConfigLegendTests/visibility-click-tests.js
src/content/samples/api/legendTests/ItemAndGroupTests/get-basic-attributes.html
src/content/samples/api/legendTests/ItemAndGroupTests/get-basic-attributes.js
src/content/samples/api/legendTests/ItemAndGroupTests/reload-and-remove.html
src/content/samples/api/legendTests/ItemAndGroupTests/reload-and-remove.js
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-1.html
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-1.js
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-2.html
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-2.js
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-3.html
src/content/samples/api/legendTests/ItemAndGroupTests/toggle-tests-3.js
src/content/samples/api/legendTests/index.html
src/content/samples/api/legendTests/test-legend-four.json
src/content/samples/api/legendTests/test-legend-one.json
src/content/samples/api/legendTests/test-legend-three.json
src/content/samples/api/legendTests/test-legend-two.json

http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/test-pages/dev/samples/api/legendTests/index.html
inline comments 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3042)

test(legendAPI): add test pages for Legend API

---

src/app/core/constant.service.js
src/app/ui/table/table.service.js
src/app/ui/toc/symbology-stack.directive.js

Closes #3045
:eyes:
CESI, JOSM, sample 46, other layers with toggle symbology.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3050)

fix(ui): dynamic layer symbology toggles sibling layers queries in table

---

src/app/ui/loader/layer-source.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2871
WFS services should now load through the wizard.
Try and import these services through the wizard: 
http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?startindex=6000
http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items
The wizard will no longer crash.
**Note:** these occasionally fail due to a semicolon error in the console. This seems to be more of an error with these specific services and not the viewer (they have happened as early as `v2.5.0`, so simply refresh the page and try again!
Please …

fix(loader): wfs services properly loaded through wizard

---

src/content/styles/main.scss

Unbreaks v3
:eyes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3076)

chore(v3): remove jquery datatables css

---

src/app/ui/toc/symbology-stack.directive.js

Closes #3075
:eyes:
sample 1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3083)

fix(ui): hide symbology stack toggles for esriRaster layers

---

api/src/schema.d.ts
package-lock.json
schema.json
src/app/bootstrap.js
src/app/core/config.class.js
src/app/core/graphics.service.js
src/app/ui/export/export-components.service.ts
src/app/ui/export/export-generators.service.js
src/app/ui/export/export-legend.service.js
src/app/ui/export/export.html
src/app/ui/export/export.service.js
src/app/ui/sidenav/sidenav.service.js
src/app/ui/ui-loader.js
src/content/samples/config/config-sample-84.json
src/content/samples/index-samples.tpl
src/content/styles/modules/_export.scss
src/locales/translations.csv

#3044 #3067
Local printing, grabs images from the map and puts them in a canvas for exporting. Also fixes issues with column calculations when info sections are included in the legend.
Sample 84 is the easiest test, otherwise test by removing the export map url, setting or not setting the cleanCanvas option in the config, changing layer options and making sure the export image and legend looks right.
Comments and schema descriptions
--- …

Local printing

---

src/app/geo/layer-registry.service.js

As mentioned by @james-rae in the student chat:
on current `develop` when importing `happy.json` and `canada.json` (or similar file layers) on legends where reordering is permitted, layers will reorder in legend but not on map. This PR solves that issue.
:eyes: 
Use any samples where reordering legend is possible (e.g. `index-fgp-en.html` or `sample 57`). Files should reorder properly on map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv- …

fix(geo): file layers reorder properly on map

---

src/app/core/config.class.js
src/app/core/config.service.js
src/app/core/reload.service.js
src/app/geo/layer-blueprint.class.ts
src/app/geo/legend.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3118 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3114
Implements the following enhancements
* Removes the API Layer blueprint tracking inside the legend service. This was causing problems with RCS layers, as they were considered API layers but the internal tracking was not clearing when changing language or projection
* Removes redundant blueprint promises, which now eliminates some race conditions and simplifies legend loading code
* Adds extra sauce to ensure bookmark information for layers gets applied in the various loading paths. This part was accidentally removed during the great legend refactor of '18
Any alternate suggestions, in particular to the use of sneaky property `bookmarkData`, are welcome.
Things tested
- Regular …

Rcs and Bookmark bug fix

---

src/content/samples/index-help.tpl

Press the help button, the help dialog should pop up.
http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/help-popup/dev/samples/index-help.html
Press the help button, :eyes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3149)

test(api): add sample page for  help test

---

src/app/ui/table/table.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3127
Table would load indefinitely when you would try to open it for invisible file based layers.
:eyes:
Upload a CSV, GeoJSON or Shapefile. 
- Open the table when the corresponding layer is **visible**, does it work and make sense?
- Open the table when the corresponding layer is **invisible**, does it work and make sense?
- ~[ ] works with language change~ (file based layers disappear on language change even before this PR)
- ~[ ] works via config file~
- ~[ ] works via API~
- ~[ ] works via RCS~
- ~[ ] works via bookmark load~
Please keep the original issue up to date with …

fix(table): table loads for invisible file based layers

---

api/src/schema.d.ts
schema.json
src/app/core/config.class.js
src/app/geo/layer-blueprint.class.ts
src/content/samples/config/config-sample-85.json
src/content/samples/index-samples.tpl

Allows loading of file layers defined through the config
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2700
:eyes: on [sample 85](http://fgpv.cloudapp.net/demo/users/JahidAhmed/file-loading-through-config/dev/samples/index-samples.html?sample=85)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3133)

File loading through config

---

docs/developer/release_tutorial.md
pull_request_template.md

Minor adjustments based on following it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3145)

Update to release tutorial

---

src/app/ui/toc/templates/legend-control-input.html
src/app/ui/toc/templates/legend-control-slider.html
src/content/styles/modules/_setting-controls.scss
src/locales/translations.csv

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3125
:eyes:
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3174)

fix(settings): opacity and refresh in one footer

---

pull_request_template.md
src/locales/translations.csv

Change "Hide" to "Dismiss" in the slow loading layer alerts.
Close #3130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3176)

fix(lang): change hide to dismiss in slow layers

---

src/app/ui/export/export-generators.service.js

Adds enhancements to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2978
Tested with long and short titles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3181)

Export title wordwrap

---

src/app/geo/geo-search.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3178
Existing regexs were having difficulty recognizing most patterns.
Made them start matching, and added support for extra spaces between numbers and delimiters
Did searches for both formats.  Made sure result could be clicked and went to the correct spot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3182)

Lat long geosearch recognition

---

package-lock.json
package.json

bump
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3201)

version bump 2.6.0

---

src/app/core/core.run.js
src/app/ui/sidenav/sidenav.service.js
src/content/samples/index-enhanced-table.tpl
src/content/samples/index-mobile.tpl

#3151
#3106 
#3207
This fixes the missing bookmark functionality using the old API. We still have the issue of new API maps not being tied to the old API at all, That will come in a later PR (either new functions on the v3 API or integration between old and new API).
index-mobile
index-enhanced-table
Either of those should be fine to load bookmarks in, also any index should generate the bookmark properly after clicking the share button.
in-line
--- …

Bookmark fix

---

api/src/schema.d.ts
docs/contribute/release_tutorial.md
package-lock.json
pull_request_template.md
schema.json
src/app/core/config.class.js
src/app/geo/layer-blueprint.class.ts
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/ui/export/export-generators.service.js
src/app/ui/export/export.html
src/app/ui/export/export.service.js
src/app/ui/table/table.service.js
src/app/ui/toc/templates/legend-control-input.html
src/app/ui/toc/templates/legend-control-slider.html
src/content/samples/config/config-sample-21.json
src/content/samples/config/config-sample-85.json
src/content/samples/index-samples.tpl
src/content/styles/modules/_setting-controls.scss
src/locales/translations.csv
src/polyfills.js
webpack.common.js

`develop` rebased onto `v3` branch to add the fixes we added for `v2.6.0`
:eyes: 
None
- ~~[ ] original issue has been reviewed & updated to reflect the PR content~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3217)

Include v2.6.0 commits in v3

---

src/app/geo/legend-block.class.js

#3199 
Fixes the infinite digest cycle caused by changing a visibility sets... visibility.
Samples 1 and 72 mainly, check that everything's visibility works correctly. Any other samples can be used to verify things that aren't visibility sets are also still functional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3228)

fix(ui): fix visibilitySet infinite digest cycle

---

api/plugin-loader.ts
package-lock.json
src/app/core/core.run.js
src/app/core/global-registry.service.js
src/app/geo/geo.service.js
src/app/ui/sidenav/sidenav.service.js
src/legacy-api.ts

Plugin instances have access to a non proxied version of the legacy api via the `_RV` property - available once the `init` method is invoked:
```js
const myPlugin = {
init: function(api) {
console.log(this._RV.getCurrentLang()); // 'en-CA'
}
};
```
The `LEGACY_API` constant within ramp core is now also a non proxied version of the legacy api and is available regardless of `legacy_api.js` being present on the host page.
Added a console message when accessing the proxied api that it is deprecated.
Added a check to the plugin loader that prevents ramp from crashing when a plugin is registered on `rv-plugins` but is not defined.
Closes #3246, #3244
Chrome, Edge 15. Tested with demo plugin.
`_RV` is not officially supported and is intended for our own plugins - particularly pre-bundled ones. …

Add non proxied legacy api as _RV to plugin instances + user checks

---

package-lock.json
package.json
src/app/core/constant.service.js
src/app/geo/geo.constant.service.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/geo/map.service.js
src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toc/toc.directive.js

Implements the bulk of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3227
And closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3227
Starts using the new filter framework. Majority of updates is in the layer registry (registering/deregistering layers with filter events), and in the symbology stacks of the legend (their checkboxes need to respect the new framework).
Outstanding is integration with the new fancy-grid plugin system.
Numerous in-app tests with various layer types.
JS and Inline doc
---
This change is [<img src="https://reviewable.io/review_button.svg" …

New Filter Framework

---

docs/developer/datatables.md
docs/index.html

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3117
[Preview]( https://hackmd.io/yRI_A_VzRWK77QR-ACnx_w?both#Condition-4-Customize-the-table-through-the-config) though links aren't perfect because links refer to things within subfolders in RAMP
- ~[ ] Release notes have been updated~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3266)

chore(docs): add datatable docs

---

src/app/geo/map.service.js

Closes: #3272 
@dane-thomas thanks for more efficient solution
Turn on 'filter by extent' for any layer. 
- table shouldn't update for pans and zooms that are too close together
- let me know if delay to update table display is too long
- ~[ ] Release notes have been updated~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3282)

perf(enhancedTable): use extent debouncer when triggering filterChanged

---

api/src/legend.ts
docs/index.html

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3220
Completes docs for `LegendAPI` and fixes a broken link to `api_tech_docs`. 
- note certain parts in the demo look funny (like `BaseItem` get/set `visibility`) because the autogenerated docs render some bullet points as a code block. I have fixed it since the tag for the demo was pushed. Changes are reflected in this PR.
N/A
[View Docs Here](https://ramp-docs.fgpv-vpgf.com/docs-0212/developer/api_tech_docs/modules/_api_src_legend_.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" …

chore(docs): complete TSDocs for Legend API

---

docs/developer/intro.md
docs/developer/plugins.md
package-lock.json

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3279
:no_entry: 
:white_check_mark: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3296)

chore(docs): write plugin introduction

---

docs/developer/api-overview.md
docs/developer/intro.md

API intro documentation
Closes #3277
👁‍🗨 [Gist version of api-overview](https://gist.github.com/dane-thomas/3d8d4ebe8ed780731cc8115f94c1f7e6)
True
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3304)

chore(docs): api introduction

---

docs/developer/intro.md
docs/developer/legacy_api.md
docs/mapauthor/custom_attributes.md

Legacy API docs + intro on dev docs
**I'm not sure of the best way to organize the function list, advice is extremely welcome.**
:eyes: :point_right: [this fancy gist](https://gist.github.com/spencerwahl/6a5d1d604cc25bf78a32938ac412ecec)
Correct
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3310)

Legacy api docs

---

features/geosearch/geosearch.feature.ts
features/package.json
package.json
src/app/ui/geosearch/geosearch.service.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3303
Worked on by @JahidAhmed and myself.
Lat/Long queries now work with geosearch:
Relevant commits on `geosearch` repo: 
- https://github.com/RAMP-PCAR/geosearch/commit/ae9d69398c2e89c1641f586acbec1bf5db7be7be
- https://github.com/RAMP-PCAR/geosearch/commit/4d91c1a7e8b5f24c98677766e5aab17bd39b6cc6
- https://github.com/RAMP-PCAR/geosearch/commit/20f846da0f253248da4e91a7449a971ac3f88ff0
n/a
--- …

fix(geo): lat long geosearch recognition added back

---

api/src/layers.ts
api/src/map.ts
package-lock.json
package.json

Provides properties exposing inner esri classes to allow hardcore plugin developers do risky things to meet deadlines
Ran the app. Verified properties and functions returned valid objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3320)

esri backdoor properties

---

README.md
docs/README.md

#3249 
[Have a look at this gist](https://gist.github.com/spencerwahl/6d0f57e50fcb54e1b00a620585b4b410) :star: 
:memo: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3322)

Update to README

---

api/src/panel.ts
package-lock.json

#3318 
Coord info panel wouldn't update fully and was displaying uncompiled template text until the mouse was moved. Forced a digest after panel contents are compiled.
http://fgpv.cloudapp.net/demo/users/spencerwahl/panel-digest/prod/samples/plugins/coordInfo/coordinfo-index.html
Added a clarification comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3323)

fix(api): run digest cycle once panel compiles

---

src/app/ui/loader/layer-source.service.js

Closes part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3335
- note: does not resolve https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3335#issuecomment-470118252 because the consensus was that it was too complicated/not worth tackling right now
Non-service urls such as: 
- http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/happyEnhance.json
- http://fgpv.cloudapp.net/demo/__assets__/solazy.gif
are detected as non-services at the first step of `Service Wizard` and display an error message. This isn't the case in current `v3` (they go to step two before staying in loading state indefinitely)
Please keep the original issue up to date with the final solution, expected …

fix(ui): get service wizard to detect non-approved layers

---

docs/developer/api-overview.md

Adds doc content for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3341)

Custom esri properties doc

---

docs/technical/architecture.md

Putting some icing on the cake that is https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3258
Real docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3353)

docs - fancy hyperlinks to architecture library chart

---

src/app/ui/loader/layer-source.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3358
try loading this or any other non wfs layer 
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/30
try loading files as a service
http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/happy.json
http://fgpv.cloudapp.net/demo/__assets__/tenor.gif
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3361)

fix(loader): fix non wfs not loading bug

---

api/src/legend.ts
docs/developer/api-overview.md
src/app/geo/layer-registry.service.js

Minor style changes to source code, done while doing [a large review of the code](https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/6)
No changes to actual code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3371)

Minor cleanup

---

api/src/panel/header.ts
package-lock.json
package.json
src/content/styles/modules/_content-pane.scss

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3368
👀 any sample. Opening tables should work as they did before
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3376)

fix(enhancedTable): migrate table to panel api

---

api/src/map.ts
api/src/panel/button.close.ts
api/src/panel/button.toggle.ts
api/src/panel/button.ts
api/src/panel/element.ts
api/src/panel/header.ts
api/src/panel/index.ts
package-lock.json
package.json
src/app/geo/legend-block.class.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/toc.service.js

- Closes this: #3343 
- Seems to close: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3349 though a second pair of :eyes: appreciated
- removes forced digest cycle after compilation of each `PanelElem` and changes it to an optional parameter --> coords info calls it so that it is properly updated
- so please test coordInfo as well to see that it is working properly
- test with any sample for table loading
- test with samples that have coords info to see if that's working
- ~[ ] Release notes have been updated~
--- …

fix(enhancedTable): add loader screen, optional digest param

---

api/src/panel-registry.ts
api/src/panel/index.ts
features/table/PanelManager.ts
src/app/core/displaymanager.service.js
src/content/samples/plugins/panels.js

#3366 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3382)

Fix dialogs, move more panel opening out of stateManager

---

api/src/panel-registry.ts
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-menu.directive.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/panels/main-panel.html
src/content/styles/modules/_loader.scss
src/content/styles/modules/_toc.scss

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3365
:eyes: adding layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3383)

refactor(loader): migrate file and service loader to panel api

---

api/src/panel/header.ts
package-lock.json
src/app/ui/appbar/appbar.directive.js
src/app/ui/details/detail.service.js
src/app/ui/details/details.directive.js
src/app/ui/details/details.html
src/app/ui/panels/main-panel.html
src/content/styles/modules/_details.scss

Moves details panel to the panel API. 
TODO: need to set appbar title once that's in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3384)

feat(details): move to panel api

---

src/app/focus-manager.js

Fixes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3378
Go through different menus using `Tab` + `Enter` + `Up/Down Arrow Keys`. They should all work. Sample `6` has some menus with disabled first items.
even works for menus like this! 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3387)

fix(ui): make menus with disabled elements navigable

---

api/src/panel/header.ts
package-lock.json
package.json

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3368
:eyes: Table should open for any sample
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3388)

fix(enhancedTable): regressions from panel api changes

---

api/src/panel-registry.ts
api/src/panel/index.ts
package-lock.json
src/app/ui/appbar/appbar.html
src/app/ui/geosearch/geosearch.service.js
src/app/ui/toc/toc.service.js
src/content/styles/modules/_geosearch.scss

Migrates geoSearch to the new panel API.
Closes #3369
❌ 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3389)

fix(geosearch): move to new panel api

---

package-lock.json
package.json

Fixes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3396
Changes made on Sister PR: https://github.com/fgpv-vpgf/plugins/pull/70
I'm merging into `v3-panel-migration` even though this has nothing to do with migration because the current plugins builds were updated to sync with this `v3-panel-migration` (and don't work with `v3` anymore). 
Test if [sample 2](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/fix-details-zoom/dev/samples/index-samples.html?sample=2) details/zoom work. Double check using other samples as well.
n/a
Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes …

fix(enhancedTable):  detect OID fields accurately

---

api/src/panel/index.ts
src/app/ui/appbar/appbar.directive.js
src/app/ui/appbar/appbar.html
src/app/ui/details/detail.service.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-menu.directive.js
src/app/ui/loader/loader-service.directive.js
src/app/ui/toc/toc.service.js
src/content/styles/api/panel.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3390)

Appbar title manipulation, panel integration work

---

api/src/legend.ts
package-lock.json

Closes #3223  
:eyes: using API on Sample 67 for example
http://fgpv.cloudapp.net/demo/users/JahidAhmed/3223-legendapi-remove-info/dev/samples/index-samples.html?sample=67
```RZ.mapInstances[0].ui.configLegend.children[1].remove()``` (you can do this 3 straight times if you wish)
Minor JSDoc changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3406)

fix(legendAPI): allow infosections to be removed through API

---

scripts/pluginSamples.sh

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3411
http://fgpv.cloudapp.net/demo/users/dane-thomas/source-urls/dev/samples/plugins/
Check to see all plugin samples work 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3417)

fix(build): fix RAMP source js and css urls

---

package-lock.json
package.json

Re-includes plugin repo fixes. Table should open properly again.
any sample
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3420)

chore(build): plugins v3.0.0-3

---

docs/developer/api-overview.md
docs/developer/panels.md
docs/samples.md

#3416 
This also includes a fix for the sample image urls (the path was correct for local builds but were wrong on the docs site)
I looked at the docs.
You got it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3424)

Panel docs

---

src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_details.scss

closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3422
Details panel and add layer panels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3423)

fix(ui): panel button alignment

---

docs/developer/datatables.md
docs/developer/plugins.md
schema.json

Not explicit to, but will link to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3386 as this does enhance documentation.
Local docute test
tada
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3426)

Datatables doc update

---

src/app/ui/toc/toc.service.js
src/content/styles/modules/_content-pane.scss

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3427
:eyes:
sample 81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3429)

fix(toc): fix layer remove undo toast

---

package-lock.json
package.json

Supports https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3430
Sample 76.
Open the table for the layer.
Type `101` in the filter box for column `identifier__identifiant`
Should only see rows that begin with `101`.
Click the "Apply Filters to Map" button.
Map should only show corresponding rows.  Should not see any points on map that have `101` in the middle of their identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3431)

geoApi version bump

---

package.json
src/content/samples/index-fgp-fr.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3303
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3434
:eyes:
Sample coords to try:
43.7417, -79.3733
54.54,-91.45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3438)

fix(geosearch): version bump

---

api/src/panel/index.ts
package-lock.json
package.json
src/app/focus-manager.js
src/app/internals-focus-manager.ts
src/content/styles/api/panel.scss

- Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3294
- cell navigation is broken see: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3414
- This is basically this: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3418 with a couple fixes added in:  https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3418#issuecomment-483418517
- Sister PR: https://github.com/fgpv-vpgf/plugins/pull/78
- tab for list navigation, right and left arrows for item navigation, tab again for object navigation
- should highlight for items and have a border for lists
- should focus out to the parent element and remove any item highlights when tabbing is finished
Remember, it is a *muffin offence* to open a PR with any of the above checklist items …

fix(enhancedTable): enable accessible list navigation

---

package-lock.json
package.json
src/app/ui/details/details.directive.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3441
Adds the "no results" case to the code that watches as the identify process progresses.
Sample 6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3445)

Recognize no identify result

---

src/app/ui/geosearch/geosearch.service.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3448
Test using geosearch on any sample, look for the provinces and types filters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3451)

fix(geo): add back type and province filters

---

src/content/styles/modules/_symbology.scss

Adding the following layer or `keys=JOSM` (sometimes): http://geoportal.gc.ca/arcgis/services/Arctic_Voyage_Planning_Guide_ENG/MapServer/WmsServer
to a legend, and then collapsing the legend would have the legend floating on top of the map instead of being invisible. 
Add the above layer to a legend. Collapse the legend. Symbology stack should't float on top of the map because visibility of the stack is now inherited from parent's visibility.
--- …

fix(symbology): symbology stacks hidden with legend

---

package-lock.json
package.json
scripts/pluginSamples.sh

#3440 
PR on plugins repo: https://github.com/fgpv-vpgf/plugins/pull/82
Areas of interest samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3462)

Fix plugin build, update plugins w/ AoI fixes

---

src/content/samples/config/config-sample-01.json
src/content/styles/api/panel.scss

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3470
:eyes:
Checkout instructions in issue above ☝️ 
Also check wfs layer with long name in sample 1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3471)

fix(ui): close button pushed aside setting panel

---

package-lock.json
package.json

#3469
plugins PR; https://github.com/fgpv-vpgf/plugins/pull/89
index-samples works fine, click on the layer to open the panel, click again and it should close.
Table header should also look as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3474)

chore(build): update plugins for table fixes

---

.travis.yml

Add keys for `RyanCoulsonCA/fgpv-vpgf` and `yileifeng/fgpv-vpgf` to travis.
Nope.
Not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3478)

chore: add keys for ryan and yilei

---

api/src/legend.ts
api/src/map.ts
package-lock.json
package.json
src/app/geo/legend.service.js
src/app/ui/toc/toc.service.js

Closes #3447, #2547
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/91
3447 - you can open a table for a layer and remove through API or add a dynamic layer with multiple children through importer and then try removing a child whose table was open
2547 - `RAMP.mapInstances[0].getExtent()` and `RAMP.mapInstances[0].setExtent()` with 2 parameters, 1st one is extent in JSON format and 2nd is optional `fit`
In-line comments and documentation added for API extent functions
--- …

3447 legend remove observable

---

README.md
api/src/events.ts
api/src/geometry.ts
api/src/index.d.ts
api/src/layers.ts
api/src/legend.ts
api/src/ui.ts
package.json

Various minor doc changes
- added troubleshooting section to readme (capturing recent new student experiences)
- removed warning comments from API source
- turned off jekyll to allow API tech doc autogeneration
- updated package name
Not code.  Jekyll test will reveal itself after pull
I Am Documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3482)

Readme troubleshoot, no jekyll, remove warnings

---

docs/developer/api-overview.md
docs/index.html

Updated url to api tech docs, disabled dynamic url composing for now.
`npm run docute` womm
I Am Documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3486)

Api tech docs url update

---

package.json

Boost version for test build
Travis was happy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3488)

plugin version bump

---

package-lock.json
package.json
src/content/samples/config/config-sample-37.json

closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3193
**Note:** If the map author decides to use an unreasonably small column width there's strange overlap between the sort arrow and the reorder buttons.  
related https://github.com/fgpv-vpgf/plugins/pull/94
sample 37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3490)

fix(enhancedTable): respect config column widths

---

package-lock.json
package.json
src/content/samples/config/config-sample-88.json
src/content/samples/index-samples.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3477, sister PR to https://github.com/fgpv-vpgf/plugins/pull/92
Fixes the following previous issues: 
- on tables linked to  `layerEntries`, columns that should be hidden (according to config) are not hidden
- on tables NOT linked to `layerEntries`  columns that should be hidden (according to config) ARE hidden (with exception of columns that have filters)
- on tables linked to  `layerEntries` with column filters, column filters don't show
- when adding a column filter to tables linked to `layerEntries` the filter doesn't show up
- `sample 88`
- PR-ing here because the plugins link doesn't work for whatever reason. 
n/a
Please keep the …

fix(enhancedTable): config properties read for layerEntries

---

src/app/core/config.class.js

Fix for #3197 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3498)

fix(samples): enable snapshot for file based layers

---

src/app/core/bookmark.service.js

Fixes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3504)

fix(bookmark): damaged URL does not break viewer

---

api/src/layers.ts
src/content/samples/api/layerTests/configLayerTests/config-layer-3.html
src/content/samples/api/layerTests/configLayerTests/config-layer-3.js
src/content/samples/api/layerTests/index.html

Implements https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3510
Test cases can be found under /samples/api/layerTests/configLayerTests/config-layer-3.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3513)

feat(layers): add sql filter function

---

package-lock.json
package.json

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3506
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/97
- Rationale for fix explained on sister PR
Test by putting in values in global filter for tables on  `sample 76`. Compare console with current develop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3508)

fix(enhancedTable): fix global filter console errors

---

package-lock.json
package.json

Version Bump
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/96
Closes: fgpv-vpgf/fgpv-vpgf#3475
Headers were disappearing in IE when navigating thru tables. 
- some issues are going to be solved here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3502 so double check
Test on `Liquids Pipline` or `Natural Gas` or any other table with offscreen columns
**Please Check the following in All Three Browsers because these were recurring issues when I was trying to solve this:**
- when you forward and backtab and use arrow keys to move through table cells, headers don't disappear
- when you tab through the header buttons and press enter the columns switch
- when you press backtab when in a cell should focus on filter row
- if you enter into grid cells you can navigate properly using arrow …

fix(enhancedTable): fix headers disappearing in IE

---

package-lock.json
package.json

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3477
Plugins Version bump. 
Sister PR:  https://github.com/fgpv-vpgf/plugins/pull/100
Testing instructions on sister PR.
- ~[ ] works with projection change~
- ~[ ] works with language change~
- ~[ ] works via wizard~
- ~[ ] works via API~
- ~[ ] works via bookmark load~
- ~[ ] works in auto-legend~
- ~[ ] works in structured legend~
- ~[ ] identify works~
inline comments on sister PR
- ~[ ] Release notes have been updated~ issues that cropped up DURING v3 development not updatex
Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for …

fix(enhancedTable): hide invisible columns

---

package-lock.json
package.json

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3494
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/99
Test with `Liquids Pipeline` on `sample 88`
- **Test 1**: does closing and opening retain the table filter? 
- **Test 2**: 
- Open table
- Apply to Map
- Clear Filter
- Apply to Map should be active
- **Test 3**: 
- Open Table
- Apply to Map, now Apply to Map should be disabled
- Close and reopen table
- Apply to map should still be disabled
- Clear filters
- Apply to Map should be enabled
- **Test 4**: 
- Open table
- Toggle Table visibility off
- Close and reopen the table. Clear filters and apply to map buttons should still be active
Not test things irrelevant to the PR
- ~[ ] works with projection change~
- ~[ ] works with language change~
- ~[ ] works via config file~
- …

fix(enhancedTable): fix table filter and apply to map

---

package-lock.json
package.json

Fix for fgpv-vpgf/fgpv-vpgf#3543
Connected to: https://github.com/fgpv-vpgf/plugins/pull/103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3546)

fix(enhancedTable): fix global search incorrectly applying to map

---

package-lock.json
package.json
schema.json
src/app/core/config.class.js

Fixes #3507 using CSS properties
`config-sample-37.json` and `config-sample-38.json` are good tests for this, but test for different column widths and titles in the configs to ensure arrows never overlap. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3519)

fix(enhancedTable): a solution for overlapping arrows

---

src/app/ui/toc/toc.service.js

fix for #3499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3512)

fix(symbology): fix table filters after layer reload

---

src/app/ui/toc/symbology-stack.directive.js
src/content/samples/config/config-sample-70.json

Fix for #3483 
Updated `sample test 70` to contain different tests for this issue. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3532)

fix(symbology): fix nested symbology stack not expanding by default 

---

src/app/ui/details/details.directive.js

Fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3520)

fix(details): details panel is properly populated

---

src/content/styles/modules/_details.scss

Fixes #3516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3521)

fix(details): minor fix for details panel correctly taking full height 

---

api/src/schema.d.ts
package-lock.json
package.json
src/app/ui/toc/toc.service.js

Closes #3509 
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/104
Tested with feature and dynamic layer tables
- ~~[ ] works with projection change~~
- ~~[ ] works with language change~~
- ~~[ ] works in auto-legend~~
- ~~[ ] identify works~~
JSDoc, In-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3567)

fix(table): build after reloading layer

---

docs/developer/release_tutorial.md
package-lock.json
package.json

Updating plugins version for QA build
Sneaking in doc update to doc that isn't on public site.
Will do sanity check on travis build prior to pulling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3572)

Version bump

---

api/src/layers.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3554
Can be tested at: `/samples/api/layerTests/simpleLayerTests/simple-layer-tests.html`
With the following code in console:
```
let map = RAMP.mapById("fgpmap");
let layer = map.layers.getLayersById("simpleLayer")[0];
layer.setFilterSql('a', '1=2');
layer.getFilterSql('a');
```
--- …

fix(layers): futureproof get/setFilterSql

---

api/src/panel/button.close.ts
api/src/panel/header.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3562)

fix(ui): close button does not get compressed

---

package-lock.json
package.json
src/app/ui/toc/templates/legend-group.html
src/app/ui/toc/templates/legend-node.html
src/locales/translations.csv

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3575
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3577)

fix(ui): add tooltip to options button

---

src/app/core/config.service.js
src/app/ui/sidenav/menulink.html
src/app/ui/sidenav/sidenav.html

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3573)

fix(ui): add language attribute to sidebar and map container

---

features/geosearch/geosearch.feature.ts
src/app/core/config.service.js
src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js
src/app/ui/geosearch/geosearch-filters.service.js
src/app/ui/geosearch/geosearch-top-filters.html
src/app/ui/geosearch/geosearch.service.js

Closes #3534 
Used `index-fgp-en.html?keys=JOSM` for testing. Changing languages should not produce the console errors mentioned in the original issue. However, if you test with a sample page from `index-samples`, then this error still appears when changing languages: 
--- …

fix(*): fix console errors when changing languages

---

package-lock.json
package.json
src/locales/translations.csv

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3570
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/107
To test:
1. Add a refresh interval to a layer
2. Open it's data table
3. Wait for refresh. The toast notification should now say `Dismiss` instead of `Close`.
--- …

fix(ui): improve permanent toast hide message

---

package-lock.json
package.json
src/content/samples/config/config-sample-88.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3588
Plugin PR https://github.com/fgpv-vpgf/plugins/pull/108
http://fgpv.cloudapp.net/demo/users/dane-thomas/html-column/dev/samples/index-samples.html?sample=88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3592)

fix(enhancedTable): html rendering as text in columns

---

package-lock.json
package.json

Closes: fgpv-vpgf/fgpv-vpgf#3589
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/109
`Sample 39` should now respect config order, it does not on current develop. Other samples that don't have columns defined in config still work.
Crossed out items are checks that are not applicable
- ~~[ ] works with projection change~~
- ~~[ ] works with language change~~
-  [x] works via config file
- ~~[ ] works in auto-legend~~
- ~~[ ] works in structured legend~~
-  [x] datagrid works
- ~~[ ] identify works~~
Please keep the original …

fix(enhancedTable): column order respects config

---

api/src/schema.d.ts
docs/developer/plugins.md
docs/index.html
features/geosearch/geosearch.feature.ts
package-lock.json
package.json
schema.json
src/app/core/config.class.js
src/app/ui/geosearch/geosearch.service.js
src/content/samples/config/config-sample-89.json
src/content/samples/index-samples.tpl

Closes #3307 
GeoSearch code updates here: https://github.com/RAMP-PCAR/geosearch/commit/9722897c4db60e8c2d90c4251642c098f01df022, https://github.com/RAMP-PCAR/geosearch/commit/269b7b116c25c21615652560f883c57b15ae172d
There are small documentation changes (fixing links mainly) still required for GeoSearch which I will do before merging this PR. Just waiting for reviews first to see if anything else requires changing on that side too.
Testing Link: http://fgpv.cloudapp.net/demo/users/JahidAhmed/3307-geosearch-sort/dev/samples/index-samples.html?sample=89
Couple examples you can try:
`Toronto`, `Mississauga`, `L6V`, `064D06`
- ~~[ ] works in …

 feat(geoSearch): allow the option to filter and sort results

---

api/src/panel/header.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3604)

fix(ui): fix cut off buttons in IE

---

package-lock.json
src/app/geo/legend-block.class.js
src/app/ui/toc/legend-element-factory.class.js
src/app/ui/toc/symbology-stack.directive.js
src/app/ui/toc/templates/legend-group.html
src/content/samples/config/config-sample-75.json

closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3152
sample 75 but also add `&keys=JOSM`
~~- [ ] works with projection change~~
~~- [ ] works with language change~~
~~- [ ] works via config file~~
~~- [ ] works via wizard~~
~~- [ ] works via API~~
~~- [ ] works via bookmark load~~
~~- [ ] works on layer reload~~
~~- [ ] datagrid works~~
~~- [ ] identify works~~
~~- [ ] Help files and documentation have been updated~~
--- …

feat(legend): parent/child and symbology toggle

---

src/content/samples/config/config-sample-88.json

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3494
http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/custom-symbologies/dev/samples/index-samples.html?sample=88
Layer `Keyword Search` should show up in edge
Things that are not checked off are irrelevant for testing 
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3612)

fix(sample): use production version of cam layer

---

docs/developer/accessibility_guidelines.md
docs/index.html

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3359
:eyes: ^ that's hosted on my github pages
added `accessibility_guidelines.md`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3583)

docs(ui): add accessibility guidelines

---

api/src/schema.d.ts
package-lock.json
package.json
schema.json
src/app/core/config.class.js
src/content/samples/config/config-sample-90.json
src/content/samples/index-samples.tpl

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3175
Adds schema support for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3175
Test no. 89 in `index-samples` contains a test for this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3 …

feat(schema): add support for field alias definitions

---

src/app/geo/identify.service.js
src/app/ui/details/details.directive.js
src/app/ui/toc/symbology-stack.directive.js

Closes #3523 
Use sample 2. Click on a few data points and make sure that the details panel still works as intended and no console errors pop up.  
- ~~[ ] works in auto-legend~~
- ~~[ ] datagrid works~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv- …

fix(details): fix errors when clicking on a data point

---

src/app/core/config.class.js

Closes #3617
- ~~[ ] works with projection change~~
- ~~[ ] works with language change~~
- ~~[ ] works in auto-legend~~
- ~~[ ] works in structured legend~~
- ~~[ ] works on layer reload~~
- ~~[ ] datagrid works~~
- ~~[ ] identify works~~
--- …

fix(core): fire zoomChanged observable on native zooming

---

api/src/events.ts
api/src/geometry.ts
api/src/map.ts
src/app/geo/identify.service.js
src/app/geo/init-map.directive.js
src/app/ui/toc/symbology-stack.directive.js

Additions:
- `identify` method on API map instance accepts `XY` or `XYLiteral` coordinates
- `identified` observable on API map instance which emits whenever an API or mouse/keyboard identify is initiated. The emit value contains the identify coordinates (in lat/lon 4326) and a feature observable
Fixes:
- API geometry `XY` `projectToPoint` and `projectFromPoint` returns ESRI approved spatial references
- Undefined object error in symbology stack when identify was executed
Notes:
- No breaking changes to existing mouse/keyboard identify operations - click emits still occur in addition to the `identified` emit.
- Does this need to be documented in dev docs?
Closes #3545 
```js
RAMP.mapInstances[0].identify([-79.347015, 42.651070]);
RAMP.mapInstances[0].identified.subscribe(console.log); …
```

feat(identify): add option to trigger via the API

---

docs/developer/accessibility_guidelines.md
package-lock.json
package.json
src/app/focus-manager.js
src/app/internals-focus-manager.ts
src/content/styles/api/panel.scss

Sister PR: fgpv-vpgf/plugins#113
Closes: #3620 
- Updated all instances of class `list` to `rv-focus-list` and all instances of `item` to `rv-focus-item`
- Updated accessibility docs
Test table to see if accessible navigation still works properly compared to develop :eyes: and that I didn't miss any comments
Things I didn't check off are n/a tests
--- …

fix(enhancedTable): update list and item classes

---

src/app/ui/details/details-record-esrifeature-item.directive.js
src/app/ui/details/details-record-esrifeature-item.html
src/content/styles/modules/_details.scss

Closes #3610
Use Sample 66. Click on a wfs data point and expand the information in the details panel - the links attribute should be properly formatted as a list and test that they work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3629)

fix(details): fix wfs layer links in details panel

---

package-lock.json
package.json
src/locales/translations.csv

Closes #3605 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3635)

fix(enhancedTable): add french translation to table status

---

package-lock.json
package.json

Version bump for QA build
I am the Test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3636)

chore(build): version bump

---

package-lock.json
package.json
src/app/core/graphics.service.js
src/app/ui/export/export-component.class.js
src/app/ui/export/export-components.service.ts
src/app/ui/export/export-generators.service.js
src/app/ui/export/export.service.js

Adds a custom export image generator which works of any arbitrary HTML markup using https://html2canvas.hertzen.com/ to convert it to canvas. For more details read the corresponding issue, specifically this comment: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3598#issuecomment-508772303.
This PR should not affect the visible, current behaviour of the export functionality. This is part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3563.
Closes #3598
👀 
Inline comments + some comments here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3598#issuecomment-508772303
--- …

Create an HTML/text export generator

---

package-lock.json
package.json

Closes #3632 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3641)

fix(enhancedTable): number filter displays empty value properly

---

src/app/ui/panels/content-pane.html

Closes #3642 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3644)

fix(ui): add French translation to close button tooltip

---

src/app/ui/details/detail.service.js

Closes #3643 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3645)

fix(details): add tooltip to expand button

---

package-lock.json
package.json

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3634
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3646)

fix(enhancedTable): fix broken table when row contains complex values

---

package-lock.json
src/app/ui/toc/symbology-stack.directive.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3630
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3637
:eyes: 
http://fgpv.cloudapp.net/demo/users/dane-thomas/update-symb-stack/dev/samples/index-fgp-en.html?keys=JOSM
Any other layers with symbology toggles
inline 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3648)

fix(symbology): update symbology on visibility change

---

docs/mapauthor/migration.md
package-lock.json
package.json
src/app/geo/geo.constant.service.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-block.class.js
src/app/geo/legend.service.js
src/app/global-registry.js
src/app/ui/toc/symbology-stack.directive.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3639
Uses new `initLoadDone` property to check when layer is first put on the map. Removes custom logic.
Enhances RAMP to use latest ESRI JS API 🎉 
Small removal of confusing item on docsite.
Is very good friends with https://github.com/fgpv-vpgf/geoApi/pull/354
Tested against
- ArcGIS Server layers
- ArcGIS Server layer initialized to invisible
- File based layers
- WFS Layers
- WMS Layers with baked capabilities
Ensured loading indicators on map and legend behaved as expected, and nothing weird was up.
Tested various loading scenarios (config, wizard, reload, langchange, projchange, rcs, bookmark)
Please keep the original issue up to date …

Use geoApi first load flag, Enhance ESRI API

---

src/app/ui/toc/templates/symbology-stack.html

Closes #3631 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3649)

fix(toc): fix overlapping magnifying glass and checkbox

---

package-lock.json
package.json

Closes #3647 
Plugins PR: fgpv-vpgf/plugins#120
GeoApi PR: fgpv-vpgf/geoApi#353
http://fgpv-app.azureedge.net/demo/users/yileifeng/special-chars-map-filters/dev/samples/index-samples.html?sample=2
Used two main layers for testing: 
http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer/6 
- filter `*%` for DESCRIPTION, 5 entries should be filtered in grid and for map 
[gridSpecialChars.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3427258/gridSpecialChars.xlsx)
- run some filter tests on the SPECIAL CHARS TEST column
--- …

fix(*): fix map and grid filtering for special chars

---

package-lock.json
package.json
schema.json
src/app/core/config.class.js
src/content/samples/config/config-sample-01.json
src/content/samples/config/config-sample-90.json

Implements a schema option in `tableNode` to disable `Show filters` and `Filter by extent` by default.
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/122
Closes #3665 
The layer `Liquids Pipeline` in [`sample 01`](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/configure-show-filter/dev/samples/index-samples.html?sample=1) has `showFilter` set to `false`.
The layer `Electric Transmission Line` in [`sample 90`](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/configure-show-filter/dev/samples/index-samples.html?sample=90) has `filterByExtent` set to `true`.
Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for …

feat(enhancedTable): add schema options to disable show filters by default

---

src/app/ui/export/export-generators.service.js
src/app/ui/export/export-legend.service.js
src/app/ui/export/export.service.js

Closes #3602 
Tested through console
In-line comments added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3673)

fix(legendGenerator): remove API layers and use legendBlocks

---

.prettierrc
api/src/schema.d.ts
package-lock.json
src/app/core/graphics.service.js
src/app/ui/export/export-components.service.ts
src/app/ui/export/export-generators.service.js
src/app/ui/export/export.service.js

Add a sample plugin which create a custom export image.  fgpv-vpgf/fgpv-vpgf#3603
👀
Inline comments in the `plugin` and `export-service` explaining what an export plugin is expected to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3676)

3603 export plugin sample

---

package-lock.json
package.json

Closes #3681 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3686)

fix(enhancedTable): allow cell contents to be selected

---

package-lock.json
package.json

Sister PR: https://github.com/fgpv-vpgf/plugins/pull/127
fgpv-vpgf/fgpv-vpgf#3614
Tooltips were needed for cells with overflowing cell text so that sighted keyboard users found the table accessible.
Focus on a cell with overflowing text (will have ellipsis): 
- click on the cell
- or navigate to the cell to using arrow keys 
-  for cells with ellipsis, a pop up tooltip should be displayed until the cell is unfocused (by navigating away from cell with arrow keys or by clicking on another table cell)
Actual (non-build) changes in: 
- `main.scss`
- `panel-manager.ts`
Unchecked items don't apply
Please keep the original issue up to date with the final solution, expected behaviour, …

fix(enhancedTable): add on-cell-focus tooltips

---

package-lock.json
package.json

Closes #3652
Plugins PR: fgpv-vpgf/plugins#130
[testLongLatZeroes.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3457038/testLongLatZeroes.xlsx)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3690)

fix(enhancedTable): fix coord zero values showing up as blanks in grid

---

src/app/ui/toc/templates/symbology-stack.html
src/content/samples/config/config-sample-07.json

Closes: #3695
@JahidAhmed noticed that https://indicators-map.dev.ec.gc.ca/App/CESI_ICDE symbology stack wasn't showing up when the legend was collapsed. 
Looks like a style of `visibility:hidden` or `visibility:visible` was being applied to [this](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/src/app/ui/toc/templates/symbology-stack.html#L8) element.
- I searched for modifications of it through `style.visibility = hidden` in the codebase
- I searched for `visibility:hidden` in the stylesheet
no results for either of the two so looks unintentional. Set `visibility` to `inherit` which seems to preserve style for other samples as well. 
n/a
Please keep the original issue up to date with …

fix(symbologyStack): stack icons visible with collapsed legend

---

src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/app/ui/loader/loader-menu.html
src/locales/translations.csv

This PR is one of the first changes towards implementing the wizard changes discussed in a previous Jamboree. This PR combines the file and service import wizards into one wizard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3692)

feat(wizard): combine file and service import wizards

---

src/app/geo/layer-registry.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3701
Two changes made.
- The "initial state check" had to be passed the actual layer state instead of `''`. The new load logic would not generate API ConfigLayers for any layers that were loaded but invisible at initial check time.
- After that change, found a race condition where a fast loading layer would complete its loading steps and unregister the state listener before the initial state check could occur. Added some magic flags to detect the situation and skip the initial check. 
Sample 1, using `RAMP.mapInstances[0].layers.allLayers` before setting WMS to visible.
Also checking console for unregistration errors.
Also did testing with RCS keys on index-fgp
Remember, it is a *muffin offence* to open a PR with any of the above …

Loading state edge cases

---

package-lock.json
package.json
src/content/samples/index-https.tpl

Closes #3679 
See `index-https.html`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3706)

fix(samples): fix https sample page

---

docs/ui-overview.md

Closes #3579 
Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete. What's up doc? 🐰 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3708)

docs(docs): correct links to jump to correct section

---

package-lock.json
package.json

Updating geoApi to appease the build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3710)

geoApi update

---

docs/ui-overview.md
src/locales/help/default/en-CA.md
src/locales/help/default/fr-CA.md

Closes #3696
Updated Figma docs can be found [here](https://www.figma.com/file/bzi7IhjNZVUksPlAUPZ46p/EnhancedTable-and-Import-Wizard?node-id=27%3A128)
[Docs](https://ryancoulsonca.github.io/docs/index.html#/)
`Section 5.1` in ui-overview.md
`Add Layer` under the help docs, both English and French
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3715)

docs(docs): update wizard documentation in help file and ui overview

---

docs/developer/release_tutorial.md
src/app/geo/identify.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3716
Detects if an incoming identify request is API based, and if so, reverse engineer the screen co-ordinates to make WMS layers happy
Tested with CCP app.
Can also add WMS via the wizard and test those (e.g. [a service](http://maps-cartes.ec.gc.ca/arcgis/services/LWBSF/LWBSF/MapServer/WMSServer))
Code to trigger identify on the console
`RAMP.mapInstances[0].identify([-127.82, 52.89])` (you can change the co-ords)
Also tested against other non-WMS layers just incase.
--- …

add screen point to api identify

---

package-lock.json
package.json

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3722
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/139
Try opening one of the tables in sample 1 in IE. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3723)

fix(enhancedTable): fix table not opening in IE

---

README.md

The "tagged" versions of the doc pages are not being built; possibly when cloudapp issues happened.  While this will be fixed, the current `master` version is up to date, so will point our readme to that for now.  Ideally a proper fix will happen before v3.2.0 and we can go back to versioned links then
Its a readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3725)

temporary patch to master docs

---

src/app/ui/loader/layer-source.service.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html

Removes service type prediction from the import wizard. The predictor was taking too long to load some types of services (WFS, for example). We made the decision to remove the predictor all together and have the user decide on the service type. 
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3432
PR also fixes some other issues, such as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2986 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2937.
Tested by importing different files directly, and using each of the service types.
--- …

feat(wizard): remove service prediction

---

src/app/ui/geosearch/geosearch.service.js

Closes #3638
Follow steps in original issue: 
1. Open geosearch type in `park`
2. Apply a `type` or `province` filter to produce no results (e.g. `International Waters` for province) 
3. Clear filters/apply other filters and loading time should not be an issue 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3727)

fix(geosearch): fix long geosearch loading times

---

README.md
docs/developer/release_tutorial.md
package-lock.json
package.json
pull_request_template.md

Fixes broken links in readme
Adds checkbox to respect accessibility guidelines
Fixes a terrible error in release tutorial
I trust the power of the docs
I am docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3731)

fix links, a18y pr check

---

src/content/styles/modules/_geosearch.scss

Closes #3734 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3735)

fix(geosearch): fix double scroll bar

---

package-lock.json
package.json

#3674 
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/142
Following same steps in original issue: 
1. Open `Natural Gas Pipeline`
2. Type `Mexico` in `Country` column
3. Toggle off `Show Filters` from the table menu, you'll notice filters are gone, but table is still filtered to show only `Mexico` values for `Country` Column
4. Close and reopen the table --> table should remain filtered (may take some longer time to load for certain layers) 
--- …

fix(enhancedTable): fix col filters on table reopen with Show Filters off

---

package-lock.json
package.json

Plugins version bump
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3742)

chore(build): plugins version bump

---

.travis.yml
scripts/travis/deploy-build-azure.sh

Fixes a Travis-CI configuration issue where two deployment steps were not being performed. 
Also suppressed the deploy to Azure log output as it was excessive and caused the Travis logs to hit max size.
Closes #3726
Pushed a test tag v0.00, docs built: http://fgpv-vpgf.github.io/fgpv-vpgf/v0.00/#/home
Build continues to deploy: http://fgpv-app.azureedge.net/?prefix=demo/tags/v0.00/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3741)

chore(build): fix doc deployment

---

package-lock.json
package.json

Closes #3737 
Sister PR: https://github.com/fgpv-vpgf/plugins/pull/144
Test [here](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3737/dev/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3747)

fix(enhancedTable): fix horizontal scroll not appearing in Chrome

---

package-lock.json
package.json

Closes #3736 
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/145
http://fgpv-app.azureedge.net/demo/users/yileifeng/lazy-filter-special-chars/dev/samples/index-samples.html?sample=88
1. Open `Keyword  search` 
2. Filtering any special chars should work for any column (`Program Contribution` was the original cause of issue) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3749)

fix(enhancedTable): fix filters for lazyFilter enabled

---

src/app/ui/loader/layer-source.service.js

Closes #3728 
http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3728/dev/samples/index-fgp-en.html
Open the Network tab of the chrome developer console.
Try to import any layer other than a WMS layer. There should no longer be a request ending in `?service=WMS&version=1.3&request=GetCapabilities`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3750)

fix(wizard): remove parseCapabilities call for non-WMS layers

---

docs/developer/release_tutorial.md
package-lock.json
package.json

Updating versions for QA build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3756)

version bump 3.2.0-b2

---

README.md
docs/developer/release_tutorial.md
package-lock.json
package.json

Version updates for v3.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3778)

chore(build): v3.2.0 prep

---

packages/ramp-core/src/app/ui/toc/templates/visibility-menu.directive.js

Closes #3707 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3766)

fix(legend): fix show all not working for some dynamic layers

---

packages/ramp-plugin-enhanced-table/src/panel-manager.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3754 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3762
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/148
For ESRI layers: used http://fgpv-app.azureedge.net/demo/users/yileifeng/global-search-filters/dev/samples/index-samples.html and the `Natural Gas Pipeline` layer 
For File-Based layers: used [gridSpecialChars.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3652807/gridSpecialChars.xlsx)
For testing: primarily test global search and apply filters to map against numeric columns and quick filter properties (e.g. search for multiple terms in a row separated by white space) 
Please keep the original issue up to date with the …

fix(enhancedTable): fix global search map filters

---

packages/ramp-plugin-enhanced-table/src/panel-manager.ts

Closes #3770 
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3774)

fix(enhancedTable): fix cutoff tooltip when using maximized table

---

packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js

Closes #3767
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3772)

fix(legend): fix symbol memory being wiped by show all

---

packages/ramp-core/src/content/styles/api/panel.scss
packages/ramp-plugin-enhanced-table/src/custom-floating-filters.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3550
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/152
http://fgpv-app.azureedge.net/demo/users/yileifeng/display-input-error/dev/samples/index-fgp-en.html?keys=JOSM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3779)

fix(enhancedTable): display wrong input error for table filters

---

packages/ramp-core/package-lock.json
packages/ramp-core/package.json

`v3.3.0-b1` for QA, donethanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3792)

chore(build): version bump for QA

---

packages/ramp-core/src/app/geo/identify.service.js
packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js
packages/ramp-geoapi/src/layer/layerRec/featureRecord.js
packages/ramp-geoapi/src/layer/layerRec/wmsRecord.js

Closes #3781 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3791)

feat(identify): add layerId and layerIdx to identify results object

---

packages/ramp-core/package-lock.json
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3797)

Version bump for QA

---

packages/ramp-core/api/src/map.ts
packages/ramp-core/src/app/api-loader.ts
packages/ramp-core/src/app/core/config.class.js
packages/ramp-core/src/app/core/constant.service.js
packages/ramp-core/src/app/geo/identify.service.js
packages/ramp-core/src/app/geo/map.service.js

Closes #3768 - `click` observable fired after every click now (not just only on identify)
Starts on #3760 - `Mouse example` in issue description now working, `General example` still needs some discussion - I simply added a console warning for the time being.
Test link: http://fgpv-app.azureedge.net/demo/users/JahidAhmed/3768-click-observable/dist/samples/index-samples.html
Console test (`i clicked` should log after every click and even after projection changes):
```
var mapInstance = RAMP.mapById('sample-map');
mapInstance.click.subscribe(function (mouseEvent) {
console.log('i clicked', mouseEvent);
});
```
No
Please keep the original issue up to date with the final solution, expected …

fix(api): click observable emitted on all clicks

---

packages/ramp-core/src/content/samples/index-fgp-en.tpl
packages/ramp-core/src/content/samples/index-fgp-fr.tpl

Closes #3794 
[Test URL](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3794/dist/samples/index-fgp-en.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3801)

fix(samples): correct crosshair help text display

---

packages/ramp-core/schema.json
packages/ramp-core/src/app/core/config.class.js
packages/ramp-core/src/app/geo/legend-block.class.js
packages/ramp-core/src/app/ui/toc/legend-element-factory.class.js
packages/ramp-core/src/content/samples/config/config-sample-27.json
packages/ramp-core/src/content/samples/index-samples.tpl

Closes #3785 
Added new config option to handle remove option for structured legends. 
See sample 27
[test link](http://fgpv-app.azureedge.net/demo/users/yileifeng/structured-legend-delete/dist/samples/index-samples.html?sample=27)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3802)

fix(toc): add config option to allow structured legends to delete layers

---

packages/ramp-core/api/src/layers.ts
packages/ramp-core/src/app/geo/layer-registry.service.js
packages/ramp-plugin-enhanced-table/src/panel-rows-manager.ts

Attempts to resolve https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3568
First cut of this PR has a big TODO comment that may result in more fixes.
Can test using steps in [this comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3568#issuecomment-530926814), and try to recreate other scenarios in the issue.
[test link](http://fgpv-app.azureedge.net/demo/users/james-rae/blankGrid/dist/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3804)

Blank Grid Fix

---

packages/ramp-core/src/app/focus-manager.js

Fixes #3810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3814)

Fix issue where a focused element which is hidden is not blurred in FF

---

packages/ramp-core/src/app/ui/common/menuItem.decorator.js
packages/ramp-core/src/app/ui/geosearch/geosearch-top-filters.html
packages/ramp-core/src/locales/translations.csv
packages/ramp-plugin-enhanced-table/src/index.ts
packages/ramp-plugin-enhanced-table/src/templates.ts

Closes #3811
Fixed `aria-label` for more options button. 
Inspect element
[test link](http://fgpv-app.azureedge.net/demo/users/yileifeng/WCAG-missing-names/dist/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3813)

fix(core): add aria-label to more-options button

---

packages/ramp-plugin-enhanced-table/src/grid-accessibility.ts
packages/ramp-plugin-enhanced-table/src/templates.ts

Closes #3805 
Adds `role="columnheader"` to table column headers, and adds a success message to the table when it opens successfully.
[Test Link](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/accessibility-table/dist/samples/index-samples.html?sample=92)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3815)

fix(enhancedTable): add column header aria role and status message on open

---

packages/ramp-core/package-lock.json
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3816)

version bump for qa v3.3-b3

---

packages/ramp-core/README.md
packages/ramp-core/package-lock.json
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3817)

updating versions for v3.3.0

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3830)

Release Prep: update readme

---

packages/ramp-core/docs/developer/release_tutorial.md
packages/ramp-core/package-lock.json
packages/ramp-core/package.json

Updating version numbers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3859)

v3.3.2 release prep

---

packages/ramp-core/src/app/ui/geosearch/geosearch.html

Closes #3874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3876)

Remove focus trap on the geosearch results panel

---

packages/ramp-core/src/locales/translations.csv

Donethankses #3883 
Also pulls in a minor update from another client project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3885)

lang string updates

---

packages/ramp-core/src/content/styles/modules/_basemap.scss

+ prettier auto formatting
Closes #3884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3887)

Fix extra margin issue

---

packages/ramp-core/package-lock.json
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3895)

version bump 3.3.3

---

packages/ramp-core/src/app/geo/map.service.js

Hack patch for #3899 
Our basemap integrity check is now getting a CORS error, assumes basemap is dead, and loads the map too fast.
This puts a delay that basically says "if the basemap doesn't load in 10 seconds it is probably actually down".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3907)

Skirt failing basemap web call

---

packages/ramp-core/schema.json
packages/ramp-core/src/locales/translations.csv

For #3837: update config schema and wizard select-format text
The schema update was slightly blind. Let me know if its totally wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3923)

Improve docs for WFS 3

---

packages/ramp-core/src/app/ui/basemap/basemap.html
packages/ramp-core/src/app/ui/basemap/basemap.service.js
packages/ramp-core/src/app/ui/sidenav/sidenav.service.js
packages/ramp-plugin-coordinate-info/src/index.ts

- The side panel now remains open whenever an item is activated (mouse or keyboard navigation)
- Focus returns to the button that activated a popup like export/share and the basemap selector
- Fixed keyboard navigation issue in the basemap side panel where focus could not return to the close button
- Code is linted
- When switching languages, focus moves to the side panel close button. This is caused by those buttons being destroyed and focus manager moving the focus before they are re-created. It _could_ be fixed with some timeOut nonsense if its really bothersome, left it for now.
[Demo](http://ramp4-app.azureedge.net/legacy/users/milespetrov/3918-hamburgers/samples/index-samples.html)
Closes #3918
--- …

WCAG updates to side panel (hamburger) behavior 

---

packages/ramp-core/src/app/core/constant.service.js
packages/ramp-core/src/app/geo/init-map.directive.js
packages/ramp-core/src/app/layout/shell.directive.js

Closes #3921
Adds a new event to update map coordinates on map panning using arrow keys (when map is focused). 
[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3921-WCAG-keyboard-coords/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3934)

WCAG: display lat/long coordinates on keyboard movement

---

README.md
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3988)

Version bump v3.3.4

---

README.md

apparently the build folder structure changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3990)

readme url correction

---

packages/ramp-core/docs/developer/release_tutorial.md
packages/ramp-core/package.json

Version bump for release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4013)

chore(build): version bump v3.3.5

---

LICENSE

pushing license through develop branch.
will be nuking the current commit on `master` (which doesn't exist in develop).
this is to avoid having a merge on the master branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4014)

reapply license change

---

README.md

Updating the legalese for prospective clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4021)

chore(docs): update legal statement

---

packages/ramp-core/src/app/core/core.run.js

Duplicate of https://github.com/fgpv-vpgf/fgpv-vpgf/pull/4053, targeting correct branch 🧠
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4058)

Bug in legacy centerAndZoom

---

README.md

Updating the RAMP4 info in the readme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4082)

ramp4 in readme

---

packages/ramp-core/src/app/ui/help/help.service.js
packages/ramp-core/src/locales/help/default/en-CA.md
packages/ramp-core/src/locales/help/default/fr-CA.md

Donethankses #4083
Adds alt text to images in the help file guts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4086)

Help image alt tags

---

packages/ramp-core/package.json

enhance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4090)

Version bump 3.3.7

---

common/config/rush/pnpm-lock.yaml
packages/ramp-core/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4100)

build: update file-saver library to fix swim bug

---

README.md
packages/ramp-core/package.json

Retirement party 🍰 🎈
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4135)

chore(build): version bump 3.3.8
