CONTRIBUTING.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/5)

Expand contributing guidelines

---

gulpfile.js

Makes it easier to demo the dev build.
Conflicts:
src/index-many.html
src/index-one.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/9)

chore(build): use relative paths for injected files

---

README.md

My first pull request
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/17)

docs(readme.md): fix broken ordered list in Running a local build list

---

gulp.config.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/21)

fix missing config in multi-map file

---

gulpfile.js

Closes #22
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/24)

chore(build): reloads js files and template cache correctly

---

gulp.config.js
gulpfile.js
package.json
src/content/styles/_error.css
src/index-many.html
src/index-one.html

fixes #25, #26;
Also adds an error message on the page on babel errors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/28)

chore(build): fixes #25, #26;

---

.travis.yml

Closes #30
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/31)

chore(build): update node version to 4.1

---

gulpfile.js
src/app/layout/layout.service.js
src/app/layout/shell.html
src/app/ui/mapnav/mapnav-button.directive.js
src/app/ui/mapnav/mapnav-button.html
src/app/ui/mapnav/mapnav.controller.js
src/app/ui/mapnav/mapnav.html
src/app/ui/mapnav/mapnav.module.js
src/app/ui/mapnav/mapnav.service.js
src/app/ui/sidenav/menulink.directive.js
src/app/ui/ui.module.js
src/content/styles/common/_all.scss
src/content/styles/modules/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_mapnav.scss

It doesn't do anything yet.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/32)

feat(ui): add map navigation ui component

---

gulp.config.js
gulpfile.js
karma.conf.js
package.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/33)

Combined reporting; expanded style checks

---

.travis.yml
devdeploy.sh

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/37)

Test if autodeploy triggers on PRs

---

bower.json
gulp.config.js
karma.conf.js
package.json
src/app/core/constant.service.js
src/app/core/core.run.js
src/app/layout/shell.controller.js
src/app/layout/shell.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/42)

Load geoapi

---

bower.json
src/app/core/core.module.js
src/app/ui/filters/filters-default.directive.js
src/app/ui/mapnav/mapnav-button.directive.js
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/filters-panel.directive.js
src/app/ui/panels/main-panel.directive.js
src/app/ui/panels/side-panel.directive.js
src/app/ui/sidenav/menulink.directive.js
src/app/ui/toc/layer-item.directive.js
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.controller.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.module.js
src/app/ui/toc/toc.service.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/43)

feat(ui): add rudimentary layer tree

---

src/app/app.module.js
src/app/core/core.run.js
src/app/geo/geo.module.js
src/app/geo/geo.service.js
src/app/geo/init-map.directive.js
src/app/layout/layout.module.js
src/app/layout/shell.html
src/content/styles/main.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/46)

geo module

---

.gitignore
src/app/ui/appbar/appbar.html
src/app/ui/common/morph.directive.js
src/app/ui/common/plug-slide.animation.js
src/app/ui/common/toggle-slide.animation.js
src/app/ui/mapnav/mapnav-button.html
src/app/ui/mapnav/mapnav.service.js
src/app/ui/toc/layer-group-toggle.directive.js
src/app/ui/toc/layer-group-toggle.html
src/app/ui/toc/toc.controller.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_toc.scss
src/index-many.html
src/index-one.html
src/index-protractor.html

adds layer group toggle directive;
adds animation to layer group toggle;
replaces font icons with svg ones;
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/53)

feat(ui): enhance layer tree

---

src/app/layout/shell.html
src/content/styles/main.scss
src/content/styles/modules/_all.scss
src/content/styles/modules/_esri-map.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/48)

feat(ui): de-puzzle esri-map image

---

.jscsrc
docs/app/js/app.js
docs/config/dgeni-conf.js
docs/config/file-readers/mddoc.js
docs/config/processor/apiRoute.js
docs/config/processor/contentRoute.js
docs/config/processor/docMergeProcessor.js
docs/config/processor/internalRouteUrlFilter.js
docs/config/processor/myApp.js
docs/config/processor/myLinkModifier.js
docs/config/processor/navMenu.js
gulp.config.js
gulpfile.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/47)

style clean up for docs code

---

gulp.config.js
gulpfile.js
package.json
src/app/core/core.run.js
src/app/layout/shell.controller.spec.js
src/app/ui/common/morph.directive.spec.js
src/app/ui/mapnav/mapnav.service.spec.js

Updated sample controller test.
Both source code and test specs are babeled, so you can use es6 in test scripts.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/61)

test: add sample karma directive and service tests

---

src/app/ui/common/plug-slide.animation.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/66)

Plug Slide Animation Fix

---

src/app/layout/shell.controller.spec.js
src/app/ui/common/morph.directive.spec.js
src/app/ui/mapnav/mapnav.service.spec.js
src/app/ui/panels/content-pane.html
src/app/ui/toc/layer-item-button.directive.js
src/app/ui/toc/layer-item-button.html
src/app/ui/toc/layer-item-flag.directive.js
src/app/ui/toc/layer-item-flag.html
src/app/ui/toc/layer-item.directive.js
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.controller.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/styles/common/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_toc.scss

Submitting PR before it gets too large:
- adds layer items
- adds templating (icons, tooltips, labels, and click actions) for layer toggles and flags
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/68)

feat(ui): layer tree updates

---

src/app/ui/common/plug-slide.animation.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/74)

Add fade animation, overhaul panel animation file

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/75)

Added Bower and Gulp links

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/78)

Master to dev fix

---

CONTRIBUTING.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/79)

Tell people to test code

---

src/app/geo/geo.module.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/80)

Doc updates from meeting notes

---

src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js

State manager service to be used as the UI-router replacement. @spencerwahl works on the directive part.
Tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/82)

State manager for UI-router replacement

---

gulp.config.js
src/app/app.module.js
src/app/layout/shell.controller.spec.js
src/app/ui/toc/layer-group-toggle-button.directive.js
src/app/ui/toc/layer-group-toggle-button.directive.spec.js
src/app/ui/toc/layer-group-toggle-button.html
src/app/ui/toc/layer-group-toggle.directive.js
src/app/ui/toc/layer-group-toggle.directive.spec.js
src/app/ui/toc/layer-group-toggle.html
src/app/ui/toc/layer-item-button.directive.spec.js
src/app/ui/toc/layer-item-flag.directive.spec.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_toc.scss
src/content/styles/vendor/_all.scss

Closes #70.
Some unit tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/81)

feat(ui): add visibility toggles to layer groups

---

src/app/ui/toc/layer-group-toggle-button.directive.spec.js
src/app/ui/toc/layer-group-toggle.directive.js
src/app/ui/toc/layer-group-toggle.directive.spec.js
src/app/ui/toc/layer-group-toggle.html
src/app/ui/toc/layer-item-button.directive.spec.js
src/app/ui/toc/layer-item.directive.js
src/app/ui/toc/layer-item.directive.spec.js
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.controller.js
src/app/ui/toc/toc.service.js
src/content/styles/common/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_toc.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/85)

feat(ui): add a button body to the layer items with data tables

---

src/app/layout/shell.html
src/content/styles/main.scss
src/content/styles/modules/_all.scss
src/content/styles/modules/_appbar.scss
src/content/styles/modules/_core.scss
src/content/styles/modules/_esri-map.scss
src/content/styles/modules/_loading.scss
src/content/styles/modules/_mapnav.scss
src/content/styles/modules/_panel-plug.scss
src/content/styles/modules/_rv-whiteframe.scss
src/content/styles/vendor/_all.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/86)

feat(ui): enhance loading splash

---

src/app/ui/metadata/metadata.html
src/app/ui/settings/settings.html
src/content/styles/modules/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_setting-controls.scss

No tests required
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/87)

feat(ui): add ui part of settings panel

---

src/app/ui/common/state.directive.js
src/app/ui/common/state.directive.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/88)

State Manager Directive

---

src/app/ui/appbar/appbar.directive.js
src/app/ui/metadata/metadata.directive.js
src/app/ui/panels/panel.directive.js
src/app/ui/settings/settings.directive.js
src/app/ui/toc/toc.directive.js
src/app/ui/toolbox/toolbox.directive.js

Most of these are just skeleton directives to wrap templates.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/89)

feat(ui): add new panel and content directives

---

src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/90)

Add panel modes to stateManager

---

src/app/layout/shell.html
src/app/ui/common/morph.directive.js
src/app/ui/common/morph.directive.spec.js
src/app/ui/toc/toc.controller.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/92)

Use the new state manager for morph

---

src/app/layout/shell.html
src/app/ui/appbar/appbar.html
src/app/ui/filters/filters-default.html
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/app/ui/panels/filters-panel.html
src/app/ui/panels/main-panel.html
src/app/ui/panels/side-panel.html
src/app/ui/settings/settings.html
src/app/ui/toc/layer-group-toggle-button.directive.spec.js
src/app/ui/toc/layer-group-toggle.directive.js
src/app/ui/toc/layer-group-toggle.directive.spec.js
src/app/ui/toc/layer-item-button.directive.spec.js
src/app/ui/toc/layer-item.directive.spec.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/app/ui/toolbox/toolbox.html
src/app/ui/ui.module.js
src/content/styles/layout/_main.scss
src/content/styles/modules/_panel-plug.scss

Switches the whole UI over to the new state manager. Affects a lot of files but almost all of the changes are small.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/93)

State Manager Switch

---

bower.json
src/app/ui/toc/layer-item-symbology.directive.js
src/app/ui/toc/layer-item-symbology.directive.spec.js
src/app/ui/toc/layer-item-symbology.html
src/app/ui/toc/layer-item.directive.js
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_toc.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/96)

feat(ui): add legend/symbology to toc

---

src/app/common/router/statemanager.service.js
src/app/layout/shell.html
src/app/ui/basemap/basemap-item.directive.js
src/app/ui/basemap/basemap-item.directive.spec.js
src/app/ui/basemap/basemap-item.html
src/app/ui/basemap/basemap.directive.js
src/app/ui/basemap/basemap.directive.spec.js
src/app/ui/basemap/basemap.html
src/app/ui/basemap/basemap.module.js
src/app/ui/common/morph.directive.js
src/app/ui/mapnav/mapnav-button.html
src/app/ui/mapnav/mapnav.html
src/app/ui/mapnav/mapnav.service.js
src/app/ui/mapnav/mapnav.service.spec.js
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/app/ui/panels/other-panel.html
src/app/ui/panels/panel.directive.js
src/app/ui/settings/settings.html
src/app/ui/ui.module.js
src/content/styles/common/_palette.scss
src/content/styles/layout/_main.scss
src/content/styles/modules/_all.scss
src/content/styles/modules/_basemap.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_lists.scss
src/content/styles/modules/_mapnav.scss
src/content/styles/modules/_toc.scss

Tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/103)

feat(ui): add basemap selector ui 

---

src/content/styles/main.scss

Closes #115
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/116)

fix(build): explicitly specify name of imported sass file

---

src/app/ui/common/plug-slide.animation.js
src/app/ui/common/state.directive.js
src/app/ui/common/state.directive.spec.js
src/app/ui/toc/toc.directive.js

tests included
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/120)

Change state directive to model ngShow instead of ngIf

---

src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js
src/app/ui/common/state.directive.js

Tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/127)

bug(ui): stateManager closing content before parent is closed 

---

src/app/ui/common/plug-slide.animation.js
src/app/ui/panels/main-panel.html
src/app/ui/panels/side-panel.html
src/content/styles/modules/_content-plug.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/129)

Switch css animations to js

---

src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/content/styles/modules/_content-pane.scss

No tests needed so far.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/133)

feat(ui): add loading indicator to content pane

---

.jscsrc
src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters-default.html
src/app/ui/metadata/metadata.directive.js
src/app/ui/metadata/metadata.html
src/app/ui/settings/settings.directive.js
src/app/ui/settings/settings.html
src/app/ui/toc/layer-item-button.html
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/app/ui/toc/toc.service.spec.js
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_toc.scss

Includes panel switching between settings, metadata and filters.
Some tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/138)

feat(ui): write panel switching logic

---

src/app/common/router/statemanager.service.js
src/app/layout/shell.controller.js
src/app/layout/shell.html
src/app/ui/appbar/appbar.directive.js
src/app/ui/appbar/appbar.html
src/app/ui/details/details.directive.js
src/app/ui/details/details.directive.spec.js
src/app/ui/details/details.html
src/app/ui/details/details.module.js
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/app/ui/panels/main-panel.html
src/app/ui/ui.module.js
src/content/styles/modules/_all.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_details.scss
src/content/styles/modules/_symbology.scss
src/content/styles/modules/_toc.scss
src/content/styles/modules/_typography.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/146)

feat(ui): add point/wms details pane to the main panel

---

src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.directive.spec.js
src/app/ui/panels/content-pane.html
src/app/ui/toc/toc.service.spec.js

Tests included.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/158)

feat(ui): add option to include extra controls in panel's header

---

bower.json
package.json

before the next iteration and since I forgot to do this earlier this week.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/192)

chore(release): bump version number to 0.1.3

---

src/app/geo/geo.service.js

Registration functions for layers and attributes. 
Change API url to ESRI to avoid frequent rebuilds of custom API during development phase
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/201)

feat(geo): register layers and attribs

---

bower.json
src/app/core/constant.service.js
src/app/geo/geo.service.js
src/app/geo/init-map.directive.js
src/configFeatures.json
src/index-one.html

- unit tests to follow in a separate PR
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/203)

Basic feature layer support

---

src/app/geo/geo.service.spec.js

Geo service unit tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/205)

test(geo): add geo service unit tests

---

src/app/common/router/statemanager.service.js
src/app/layout/shell.controller.js
src/app/layout/shell.html
src/app/ui/appbar/appbar.html
src/app/ui/help/help-overlay.directive.js
src/app/ui/help/help-overlay.directive.spec.js
src/app/ui/help/help-overlay.html
src/app/ui/help/help.directive.js
src/app/ui/help/help.directive.spec.js
src/app/ui/help/help.module.js
src/app/ui/help/help.service.js
src/app/ui/help/help.service.spec.js
src/app/ui/sidenav/menulink.html
src/app/ui/toc/layer-group-toggle-button.html
src/app/ui/toc/layer-group-toggle.html
src/app/ui/toc/layer-item-button.html
src/app/ui/toc/layer-item-flag.html
src/app/ui/toc/layer-item.html
src/app/ui/ui.module.js
src/content/styles/modules/_all.scss
src/content/styles/modules/_help.scss

Includes unit tests
_flag any poorly named variables/functions_
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/207)

Basic Help Screen

---

bower.json
src/app/core/config.service.js
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/geo/init-map.directive.js
src/configDemo.json
src/index-one.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/216)

Dynamic and WMS layers

---

src/app/core/constant.service.js
src/app/geo/geo.service.js
src/configDemo.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/222)

trivial implementation of image service support

---

src/app/geo/geo.service.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/221)

Basic map and layer tests

---

package.json
src/app/common/router/statemanager.constant.service.js
src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js
src/app/core/constant.service.js
src/app/layout/shell.html
src/app/ui/filters/filters-default-menu.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters-default.html
src/app/ui/metadata/metadata.directive.js
src/app/ui/panels/content-pane.html
src/app/ui/settings/settings.directive.js
src/app/ui/toc/toc.service.js
src/app/ui/toc/toc.service.spec.js
src/content/styles/modules/_filters.scss
src/content/styles/other/_all.scss
src/content/styles/vendor/_special.scss

Shows data for individual layers in the filters panel.
No tests included yet.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/226)

Interface for viewing per-layer datagrid

---

src/index-one.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/227)

IE, IE never changes

---

src/app/common/router/statemanager.constant.service.js
src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/233)

feat(core): add history to state items with children

---

bower.json
src/app/core/constant.service.js
src/app/geo/geo.constant.service.js
src/app/geo/geo.module.js
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/ui/basemap/basemap.directive.spec.js
src/app/ui/toc/layer-group-toggle-button.directive.spec.js
src/app/ui/toc/layer-group-toggle.directive.spec.js
src/app/ui/toc/layer-item-button.directive.spec.js
src/app/ui/toc/layer-item.directive.spec.js
src/app/ui/toc/toc.service.js
src/app/ui/toc/toc.service.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/232)

Layer attribute loading

---

src/app/ui/filters/filters-default-menu.html
src/app/ui/panels/content-pane.directive.js
src/app/ui/toc/layer-group-toggle.html
src/app/ui/toc/layer-item-button.directive.js
src/app/ui/toc/layer-item-menu-item.html
src/app/ui/toc/layer-item.directive.spec.js
src/app/ui/toc/layer-item.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_toc.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/234)

feat(ui): move layer toggles to a menu

---

src/app/ui/details/details.directive.js
src/app/ui/details/details.html
src/app/ui/filters/filters-default-menu.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters-default.html
src/app/ui/panels/content-pane.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_filters.scss
src/content/styles/vendor/_special.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/237)

fix(ui): make datatable header scrollable and more

---

bower.json
package.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/240)

chore(build): bump version to 0.3.0

---

src/content/styles/modules/_filters.scss

Closes #238
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/241)

fix(ui): bug(ui): datatable is not displayed correctly in Firefox

---

src/content/styles/modules/_toc.scss

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/244)

fix(ui): align selected layer indicator in firefox

---

.travis.yml
gulpfile.js
karma.conf.js
package.json
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/245)

Node 5.4 upgrade; EPSG code lookup; promise error handling fix

---

src/app/geo/geo.service.js
src/app/ui/toc/toc.service.js
src/content/styles/modules/_toc.scss

adds "null" as a return value to shut up jshint;
adds crazy nested layer group sample;
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/247)

Style change: indenting first ten levels in layer selector

---

bower.json
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/249)

Use geoApi event wrapping

---

bower.json
package.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/254)

chore(build): bump version to 0.4.0

---

bower.json
gulp.config.js
gulpfile.js
package.json
src/app/injector.js
src/index-many.html
src/index-one.html
src/index-protractor.html
src/index-wet.html

also fixes iso 8601 bug
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/248)

chore(build): remove hardcoded dependencies from sample html files

---

bower.json
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/index-wet.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/258)

two bug fixes

---

src/schema.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/261)

feat(core): update to basic layer schema (suggested)

---

src/configDemo.json
src/content/styles/vendor/_all.scss
src/content/styles/vendor/_esri.scss

Added scalebar entry to configDemo.json to display the scalebar dijit
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/263)

Add ESRI scalebar CSS to fgpv-vpgf

---

gulp.config.js
gulpfile.js
package.json
src/app/geo/geo.constant.service.js
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/configDemo.json
src/index-wet.html
src/schema.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/264)

Apply layer option defaults to layer config blocks + random changes too small for their own PRs

---

bower.json
src/app/geo/geo.constant.service.js
src/app/geo/geo.service.js
src/schema.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/266)

Tile Layers

---

README.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/267)

chore(readme): add more badges to readme.md

---

src/config.en.json
src/configDemo.json
src/schema.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/288)

Legend schema

---

src/app/ui/appbar/appbar.html
src/locales/translations.csv

Pretty simple commit, looking for feedback before I apply similar changes elsewhere
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/289)

feat(ui): appbar i18n support

---

bower.json
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/configDemo.json
src/content/styles/vendor/_all.scss
src/content/styles/vendor/_esri.scss

setup overview map using setting and geoAPI
* setup mapSettings for scalebar
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/291)

Overview map

---

bower.json
package.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/296)

Weekly sync

---

.gitignore
Vagrantfile
package.json
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/geo/identify.service.js

Starting PR for early feedback.  No tests yet.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/300)

Dynamic Layer Click Handler

---

src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/ui/toc/toc.service.js
src/content/styles/vendor/_esri.scss

Will need more work to toggle dynamic layers and their children, but good enough for now (I hope).
No tests yet.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/298)

feat(ui): toggle layers/groups (basic)

---

src/app/core/config.service.js
src/app/geo/geo.service.js
src/app/layout/shell.controller.js
src/app/layout/shell.html

Temporary buttons, will be replaced asap with a proper implementation along with multiple config support.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/306)

Language switching

---

bower.json
src/app/geo/geo.service.js
src/app/ui/mapnav/mapnav.service.js
src/configDemo.json

full extent with re-projection; when config settings has different spatial reference than the loaded map
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/299)

full extent

---

src/app/layout/shell.controller.js
src/app/ui/help/help-summary.html
src/app/ui/sidenav/menulink.html
src/content/styles/modules/_help.scss

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/312)

feat(ui): add simplistic help

---

src/app/geo/geo.constant.service.js
src/app/ui/toc/toc.service.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/313)

Use layer's actual data in the datagrid

---

src/app/geo/geo.service.js
src/app/ui/toc/toc.service.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/311)

feat(ui): add simple remove layer functionality

---

src/app/common/router/displaymanager.service.js
src/app/geo/identify.service.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/316)

togglePanel API

---

gulpfile.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/319)

Fix missing translations in demo builds

---

bower.json
package.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/321)

version 0.6.0

---

src/app/ui/toc/layer-item-symbology.directive.js
src/app/ui/toc/layer-item-symbology.html

Closes #150
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/320)

feat(ui): enhance symbology icon stack in layer selector on hover

---

CONTRIBUTING.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/326)

Fix commit scopes

---

src/app/geo/identify.service.js
src/schema.json

Supports configurable tolerance value to be used when clicking on features
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/337)

feat(geo): configurable identify tolerance

---

src/app/ui/metadata/metadata.html
src/app/ui/settings/settings.html
src/app/ui/sidenav/sidenav.html
src/app/ui/toc/layer-item.directive.spec.js
src/app/ui/toc/layer-item.html
src/locales/translations.csv

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/338)

feat(ui): i18n support for metadata, settings, appname, nav

---

src/app/ui/toc/layer-group-toggle-button.directive.spec.js
src/app/ui/toc/layer-group-toggle-button.html
src/app/ui/toc/layer-group-toggle.directive.spec.js
src/app/ui/toc/layer-item-button.directive.spec.js
src/app/ui/toc/layer-item-button.html
src/app/ui/toc/layer-item-flag.directive.spec.js
src/app/ui/toc/layer-item-flag.html
src/app/ui/toc/layer-item-menu-item.html
src/app/ui/toc/layer-item-symbology.directive.spec.js
src/app/ui/toc/layer-item-symbology.html
src/app/ui/toc/toc.service.js

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/340)

feat(ui): i18n support for toc

---

bower.json

Weekly build thing
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/345)

chore(build): version 0.7.0

---

package.json

I missed a file cuz i'm new here :pig2: :dash:
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/346)

chore(build): version 0.7.0 part II

---

src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/ui/basemap/basemap.directive.js
src/config-demo.json
src/schema.json

need geoApi review first, once the geoApi pull request is complete, will generate a new build and bump the bower.json.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/318)

part 2 of config update, please review geoApi first. Require new geoApi build.

---

src/app/ui/appbar/appbar.html
src/app/ui/common/stepper-item.directive.js
src/app/ui/common/stepper-item.html
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/app/ui/panels/content-pane.html
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_loader.scss
src/content/styles/modules/_stepper.scss

incremental update
no comments yet
no tests yet
more sass
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/348)

feat(ui): second part of the layer import ui component

---

bower.json
src/app/geo/geo.service.js
src/app/ui/filters/filters-default.directive.js
src/app/ui/toc/toc.service.js

closes #344
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/350)

Zoom to feature on select

---

bower.json
src/app/geo/identify.service.js

Apply aliases to feature layer click results.
Needs fix for proper formatting in detail pane
Tests Later™
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/349)

feat(geo): use aliases in identify results

---

bower.json
package.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/361)

chore(build): version 0.8.0

---

src/config-demo.json
src/config-sample-structure.json
src/config.en.json
src/schema.json

When accepted this should close #334 .
Will probably need some discussion, and the WMS layers won't work right away.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/363)

Schema changes

---

src/app/common/router/statemanager.service.js
src/app/ui/details/details.directive.js
src/app/ui/loader/loader-file.directive.js

Closes #366
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/369)

fix(ui): endless loop when closing layer loader after details panel

---

src/app/ui/filters/filters-default.directive.js
src/content/styles/modules/_filters.scss

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/373)

bug(ui): datatable is broken again

---

bower.json
gulpfile.js
package.json
src/app/core/config.service.js
src/config-demo.json
src/config.en.json
src/config.fr.json
src/index-many.html
src/index-one.html
src/index-protractor.html
src/index-wet.html

Should close #269 when approved (might want to have a split task for consumption of additional data from the RCS).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/375)

Basic RCS integration

---

gulp.config.js
gulpfile.js
package.json
src/app/core/constant.service.js
src/schema.json

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/379)

chore(build): add schema defaults to core constant service

---

src/app/geo/metadata.service.js
src/app/ui/toc/toc.service.js
src/app/ui/toc/toc.service.spec.js
src/config-demo.json
src/config.en.json
src/schema.json

1. unit test for metadata service to follow
2. need to update toc.service unit test related to metadata service
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/377)

Dataset metadata xsl transformation

---

src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/384)

fix(geo): removed layers stayed in layer registry

---

gulpfile.js
src/app/core/config.service.js
src/app/core/constant.service.js
src/app/geo/geo.constant.service.js
src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js

- Removed most hacky parts of configService
- applies layer defaults to all layers in the config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/386)

Enhance configService

---

src/app/core/config.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/387)

fix(core): actually apply layer defaults

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/388)

chore(build): version 0.10.0

---

.jscsrc
src/polyfill/object.entries.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/392)

Object.entries polyfill

---

src/app/layout/shell.directive.js
src/app/layout/shell.directive.spec.js
src/app/layout/shell.html
src/app/ui/filters/filters-default-menu.html
src/app/ui/mapnav/mapnav.service.js
src/app/ui/settings/settings.html
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_setting-controls.scss
src/content/styles/vendor/_esri.scss

- Deleted extra mapnav, sidenav and filters menu buttons
- Removed temp buttons on the main panel (layer loader, language switch)
- Re-enabled the extent on the overview map
- Fixed and enhanced settings panel controls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/395)

Small UI changes

---

src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js
src/app/ui/settings/settings.directive.js
src/app/ui/settings/settings.html
src/app/ui/toc/toc.service.js

Second checkbox for #193 
Wires up layer opacity slider to the actual layer.
Also makes preset transparency in configs work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/389)

Layer Opacity/Transparency

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/407)

Version 0.11.0

---

src/config-all.en.json
src/index-many.html

closes #390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/425)

chore(build): add config with all supported layers

---

src/app/geo/identify.service.js
src/app/geo/legend.service.js
src/app/ui/details/details.directive.js
src/app/ui/details/details.html
src/app/ui/toc/layer-item-symbology.directive.js
src/app/ui/toc/layer-item-symbology.html
src/content/styles/modules/_details.scss
src/content/styles/modules/_symbology.scss
src/content/styles/modules/_toc.scss

Now they do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/432)

Identify Results Not Using Layer Symbology

---

bower.json
src/app/geo/map.service.js
src/app/ui/filters/filters-default.directive.js

related to #417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/437)

Zoom to feature fixed

---

src/app/ui/basemap/basemap-item.html
src/app/ui/basemap/basemap.directive.js
src/config.en.json
src/config.fr.json

update config entry for base map name
add code to truncate long name to ensure "selected" check mark still visible.
stole code from James PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/441)

base map fixes (update configs, add truncate code for base map name)

---

src/app/ui/settings/settings.html

closes #429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/439)

fix(ui): opacity slider percent display

---

bower.json
src/app/core/constant.service.js
src/app/layout/shell.directive.spec.js
src/app/ui/filters/filters-default-menu.directive.js
src/app/ui/filters/filters-default-menu.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters-default.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/451)

Export Datagrid Data

---

src/app/ui/basemap/basemap-item.html
src/app/ui/basemap/basemap.directive.js
src/app/ui/basemap/basemap.html
src/content/styles/modules/_basemap.scss

add warning to projection header
add warning to hover tip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/447)

feat(ui): add map reload message warning (issue#111 for #173)

---

bower.json
package.json

Closes #453
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/460)

chore(build): version 0.12.0

---

bower.json
gulp.config.js
src/app/injector.js
src/index-wet.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/462)

Conditionally load jQuery

---

src/app/injector.js

Synchronously load jQuery first then all the other stuff
Closes #465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/470)

chore(build): synch loading for jquery

---

src/app/ui/filters/filters-default.directive.js
src/content/styles/vendor/_datatable.scss

Zoom to feature hyperlink implemented on datatable with a clickable icon. On select zoom to feature removed.
closes #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/471)

Zoom to feature hyperlink

---

gulpfile.js

Closes #463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/464)

fix(core): transpile injector, global registry to es5

---

src/app/geo/map.service.js
src/app/ui/basemap/basemap.directive.js

blank base map code
closes #285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/472)

blank base map

---

gulpfile.js
src/config-sample-structure.json
src/schema.json

…ayer entries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/474)

feat(core): update schema to use same style options for wms/dynamic layer entries

---

bower.json
gulp.config.js
src/app/injector.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/478)

Conditionally load DataTables

---

src/app/ui/basemap/basemap-item.html
src/app/ui/basemap/basemap.directive.js

closes #403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/475)

Base map description 

---

src/app/core/core.config.js
src/app/layout/shell.directive.spec.js
src/app/ui/common/menuItem.decorator.js
src/app/ui/filters/filters-default-menu.directive.js
src/app/ui/filters/filters-default-menu.html
src/content/images/iconsets/default-icons.svg
src/content/styles/vendor/_special.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/483)

feat(ui): add aria to data panel menu

---

gulp.config.js
gulpfile.js
src/e2e-test/scenarios.js
src/polyfill/array.find.js
src/polyfill/array.from.js
src/polyfill/object.entries.js
src/polyfill/promise.js
src/polyfill/string.endsWith.js
src/polyfill/string.startsWith.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/487)

Get the viewer to load in ie11

---

src/app/geo/geo.constant.service.js
src/app/geo/geo.service.spec.js
src/app/geo/layer-registry.spec.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js
src/app/ui/toc/entry-flag.directive.js
src/app/ui/toc/templates/entry-flag.html
src/app/ui/toc/templates/layer-entry.html
src/locales/translations.csv

Feature counts are set for feature layers and dynamic sublayers.
Feature count is incorrect in some instances. See #485
Geometry types for dynamic sublayers are not available. fgpv-vpgf/geoApi#98
Some questionable choices made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/488)

Feature Layer Details indicate Feature Counts

---

src/config.en-CA.json
src/config.fr-CA.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/494)

Config "fixes"

---

Vagrantfile
src/app/geo/geo.constant.service.js
src/app/geo/identify.service.js
src/app/geo/layer-registry.service.js
src/app/ui/details/details.html
src/config.en-CA.json

This PR doesn't completely address #283 or #271 but it does give people a chance to start complaining if they don't like the way it is written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/503)

WMS GetFeatureInfo Integration

---

src/app/core/config.service.js
src/content/styles/layout/_main.scss

- file-only config on RCS failure (down-time etc.) plus a notification for users
- handles response from RCS on bad small-key(s)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/506)

Keep RCS from breaking the viewer

---

src/app/geo/legend.service.js
src/config.en-CA.json
src/schema.json

Addresses the legend portion of #271 but some follow up UI tweaks will be required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/507)

WMS Legend Support

---

bower.json
package.json

Closes #454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/512)

chore(build): version 0.13.0

---

src/app/geo/geo.service.spec.js
src/app/geo/init-map.directive.js
src/app/geo/map.service.js
src/app/layout/storage.service.js
src/app/ui/appbar/appbar.directive.js
src/index-many.html

Closes #378 
Zoom to feature now centers at middle of visible map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/520)

Zoom to Feature offset

---

src/app/app-seed.js
src/app/core/core.run.js
src/app/global-registry.js
src/app/injector.js
src/app/layout/shell.directive.spec.js
src/index-wet.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/530)

Queue external api calls

---

src/app/ui/filters/filters-default.directive.js

Closes #495 
- OBJECTID no longer assumed to be first column in datatable.
- Created hidden last column to store OBJECTID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/532)

refactor(ui): remove objId dependency on column 0

---

src/app/ui/metadata/metadata.html
src/app/ui/settings/settings.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_toc.scss

Also adds the entry name to settings and metadata titles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/536)

Improve toc entry highlight

---

bower.json
gulp.config.js
src/app/geo/identify.service.js
src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js
src/app/ui/toc/templates/entry-symbology.html
src/config.en-CA.json

Made some changes to help testing fgpv-vpgf/fgpv-vpgf#510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/535)

Add GeoMet Sample

---

src/app/injector.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/543)

Make IE load the viewer

---

src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/app/ui/filters/filters-default.directive.js
src/app/ui/toc/toc.service.js
src/config.en-CA.json
src/content/styles/modules/_filters.scss
src/content/styles/vendor/_datatable.scss

Closes #174 and #533.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/548)

Populate Datagrid for Group Layers

---

src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js

Not a complete implementation, for discussion at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/547)

Reordering Utilities

---

src/app/layout/shell.directive.js
src/app/ui/help/help-summary.html
src/app/ui/help/help.directive.spec.js
src/app/ui/help/help.service.js
src/app/ui/help/help.service.spec.js
src/locales/translations.csv

This prompted a talk about translation file loading, the part concerning this PR: the `$http.get` will be replaced by a `translation` constant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/549)

Put the help in the viewer

---

src/index-fgp-en.html
src/index-fgp-fr.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/560)

Update index-fgp to use new api call

---

src/app/geo/legend-entry.service.js
src/app/ui/toc/templates/entry-control-button.html
src/app/ui/toc/toc.service.js
src/config-all.en.json
src/config-demo.json
src/config.en-CA.json
src/config.fr-CA.json
src/schema.json

Should close #509 when merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/563)

Change visibility to boolean

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/565)

Update to v0.14.0

---

src/app/geo/identify.service.js
src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js

Re-apply feature count to toc entries.
Close #518 and #537.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/569)

Integrate on demand attribute loading: Part II

---

bower.json
src/app/geo/identify.service.js
src/app/geo/layer-registry.service.js

Now converts date attribute to ISO format
closes #455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/571)

Support for esriFieldTypeDate

---

src/app/geo/map.service.js

closes #496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/575)

feat(geo): zoomToGraphic zooms to highest visible zoom

---

bower.json
src/app/geo/layer-registry.service.js
src/app/ui/settings/settings.directive.js
src/app/ui/settings/settings.html
src/config.en-CA.json
src/schema.json

Closes #413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/585)

Bounding box

---

src/app/layout/shell.directive.js
src/app/layout/shell.directive.spec.js
src/app/ui/sidenav/sidenav.html
src/config.en-CA.json
src/content/styles/modules/_app-menu.scss

Double chevron icon appears in top right corner of left-side menu. Moved marker image source to config file. Minor changes to styling for improved appearance; removed gradient and increased width to 320px.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/579)

feat(ui): add icon to close left-side menu

---

src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js
src/app/ui/toc/entry.directive.js
src/app/ui/toc/entry.directive.spec.js
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/templates/placeholder-entry.html
src/app/ui/toc/toc.html
src/app/ui/toc/toc.service.js
src/content/styles/modules/_toc.scss

issue #551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/587)

Add layer placeholders

---

src/app/ui/basemap/basemap-item.html
src/app/ui/basemap/basemap.directive.js
src/content/styles/layout/_main.scss
src/content/styles/modules/_basemap.scss

Replaces tooltip with a div element that appears over basemap on mouse hover.
Closes #583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/584)

bug(ui): expand basemap description under title 

---

src/app/geo/legend-entry.service.js

:see_no_evil:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/589)

Placeholder hotfix

---

src/app/ui/details/details.directive.js
src/app/ui/details/details.html
src/content/styles/modules/_details.scss

Issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/545
__________________
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/594)

Scrollbar for detail selector

---

bower.json
src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js
src/app/geo/legend.service.js

Closes #552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/596)

feat(geo): set scale flag for off-scale layers

---

src/app/geo/identify.service.js
src/app/ui/filters/filters-default.directive.js
src/content/styles/modules/_filters.scss
src/locales/translations.csv

Closes #416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/605)

Enable Point Information Display when viewing Datagrid 

---

bower.json
src/app/core/core.module.js
src/app/geo/geo.constant.service.js
src/app/geo/layer-registry.service.js
src/app/geo/layer-registry.spec.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js
src/app/ui/common/dragula.directive.js
src/app/ui/common/rvDragula.directive.js
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.html
src/config.en-CA.json
src/content/styles/main.scss
src/content/styles/modules/_toc.scss
src/content/styles/vendor/_all.scss
src/content/styles/vendor/_dragula.scss

Closes #272, #592.
I do apologize for sections of ugly code (especially related to legend entry, layer object and other "state" related checks). These should be cleared up after the refactor proposed by Aly.
Unit test for `layerRegistry` are turned off as well until the refactor is complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/600)

Reorder layers with Dragula (it's so easy it's painfull™)

---

src/app/geo/layer-registry.service.js
src/locales/translations.csv

Closes #553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/614)

Update Legend to Indicate Layer is Out of Scale

---

src/content/styles/modules/_toc.scss

Closes #482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/609)

fix(ui): remove scrollbar on collapsed group layer

---

src/app/ui/details/details.directive.js
src/app/ui/details/details.html

issue #598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/615)

fix(ui): fix broken layer selector

---

src/index-fgp-en.html
src/index-fgp-fr.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/621)

Update rcs endpoint for fgp pages

---

src/app/geo/legend-entry.service.js

Closes #490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/617)

fix(legend): show settings options only when settings is available

---

README.md

adds code climate badges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/624)

chore(readme): add more badges

---

src/app/geo/layer-registry.service.js
src/app/geo/legend.service.js
src/config.en-CA.json
src/locales/translations.csv

Closes #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/629)

fix(legend): set the legend service for esriTile layer

---

src/app/ui/metadata/metadata-expand.html
src/locales/translations.csv

Closes #590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/637)

fix(ui): (metadata) expand button needs a tooltip

---

src/app/ui/filters/filters-default.directive.js

Closes #416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/634)

fix(ui): add details icon to dynamic layers

---

src/app/geo/map.service.js

Also refactored the offset part out into a separate function
Closes #445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/628)

Zoom to Feature support for client side data

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/647)

update to v0.15.0

---

src/app/ui/basemap/basemap.html
src/locales/translations.csv

Closes #493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/641)

fix(ui): basemap french language support

---

src/app/ui/toc/entry-control.directive.js
src/app/ui/toc/templates/entry-control-button.html
src/app/ui/toc/toc.service.js

Closes #599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/642)

fix(ui): show visibility tooltip

---

src/app/geo/map.service.js

Closes #354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/655)

fix(ui): allow multiple zoom requests to succeed

---

src/app/injector.js

issue #448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/640)

Check jQuery and dataTable versions

---

src/app/ui/details/details-data.directive.js
src/app/ui/details/details.html

Closes #542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/657)

perf(ui): data panel content creation from ng-repeat to document frag

---

src/app/geo/identify.service.js

Closes #538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/659)

feat(ui): stop buffering queries for polygon layers

---

bower.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/674)

chore(build): pin angular to 1.4.11

---

src/app/core/core.run.js
src/app/geo/geo.service.js
src/app/geo/layer-blueprint.class.js
src/app/geo/layer-registry.service.js

In support of #112.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/658)

Unifies layer object generation

---

src/app/ui/filters/filters-default.directive.js

Closes #372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/672)

fix(ui): fix datagrid blank out afyter morph

---

bower.json
src/app/ui/basemap/basemap.directive.js
src/config-sample-structure.json

issue #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/683)

Remove holder-ipsum from build

---

.jshintrc
Vagrantfile
src/app/geo/geo.constant.service.js
src/app/geo/identify.service.js
src/app/geo/layer-blueprint.class.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js

Splitting #606 into parts for easier rebasing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/684)

Refactoring

---

src/app/ui/panels/filters-panel.html
src/app/ui/panels/main-panel.html
src/app/ui/panels/other-panel.html
src/app/ui/panels/side-panel.html
src/content/styles/base/_all.scss
src/content/styles/layout/_main.scss
src/content/styles/modules/_panel-plug.scss

Closes #250, #251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/673)

fix(ui): change class panel to rv-panel

---

src/app/ui/details/details-data.directive.js

issue #562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/688)

hide rvSymbol in details panel

---

src/locales/translations.csv

Closes #607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/691)

style(locales): complete French translation of translation.csv file

---

gulp.config.js
package.json
src/app/geo/layer-record.class.js

This adds the bulk of #606 and should unblock the bookmark tasks.  Docs to follow as the LayerRecord interface will probably change a bit as LayerBlueprint finalizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/696)

LayerRecord class preview

---

src/app/geo/identify.service.js
src/app/ui/details/details-content.directives.js
src/app/ui/details/details-content.html
src/app/ui/details/details-expand.directive.js
src/app/ui/details/details-expand.html
src/app/ui/details/details-modal.html
src/app/ui/details/details.directive.js
src/app/ui/details/details.html
src/app/ui/panels/content-pane.directive.js
src/app/ui/panels/content-pane.html
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_details.scss
src/locales/translations.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/697)

Expand detail

---

src/app/ui/mapnav/mapnav.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/701)

Close datagrid when basemap selector opens

---

src/config.en-CA.json
src/index-one.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/711)

chore(build): changes to index-one demo page

---

bower.json
src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/app/ui/filters/filters-default.directive.js

#635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/720)

Dynamic layer zoom and symbology

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/727)

chore(build): version 0.17.0-1

---

bower.json
src/app/geo/geo.constant.service.js
src/app/geo/identify.service.js
src/app/geo/layer-blueprint.class.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js
src/app/ui/filters/filters-default.directive.js

Closes #606 when complete.  Still missing some doc updates, but want to get the code sections merged up front.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/723)

LayerRecord integration

---

src/app/geo/geo.service.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/ui/toc/templates/group-entry.html
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/toc.service.js
src/schema.json

Closes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/731)

Layer Reloading

---

src/content/styles/layout/_main.scss

Closes #597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/741)

bug(ui): bottom toast notification blocks panels

---

src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/toc.service.js
src/config.en-CA.json
src/schema.json

Closes #625
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/744)

feat(ui): add zoom to control four out of scale layers

---

src/app/geo/layer-blueprint.class.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/743)

LayerRecord fixes

---

src/app/geo/geo.service.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/ui/settings/settings.directive.js
src/app/ui/settings/settings.html
src/schema.json

Closes #412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/747)

Snapshot Mode

---

src/app/geo/metadata.service.js

Closes #619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/761)

IE Metadata Fix

---

bower.json
src/app/geo/layer-blueprint-user-options.class.js
src/app/geo/layer-blueprint.class.js
src/app/ui/loader/loader-file.html
src/app/ui/loader/loader-service.directive.js
src/app/ui/loader/loader-service.html
src/content/styles/main.scss
src/content/styles/modules/_core.scss
src/content/styles/modules/_loader.scss
src/content/styles/vendor/_special.scss
src/locales/translations.csv

In support of #612
Notes:
- errors (like mismatch between detected and user selected file type) are not handled; no error messages (except for invalid urls and required fields)
- if a service url provided is some random url or a broken service, in some cases, the error is not immediately detected (it timeouts eventually) (the error message is not shown right away); this can be confusing as nothing seem to happen; one suggestion is to block the “continue” button so the user can’t click multiple times;
- the user can force a service into any type and there is no validation available right now; in some cases it looks that something is broken on our end;
- does not compute smart defaults
- no colour picker yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" …

Adds service-based layer import (with caveats)

---

src/app/geo/layer-registry.service.js

Trigger of onLoad was getting skipped and only onUpdateEnd was being fired.
Closes #758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/773)

Manually fire onLoad and onUpdateEnd

---

.travis.yml
docdeploy.sh
docs/config/templates/index.template.html
src/app/ui/common/menuItem.decorator.js
src/app/ui/common/stepper/stepper.class.js

Part of #767
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/774)

Automate docs publication on tag

---

src/app/geo/layer-registry.service.js

#734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/780)

fix(geo): remove bbox when layer removed

---

bower.json
src/app/geo/map.service.js
src/app/ui/filters/filters-default.directive.js
src/config.en-CA.json
src/content/styles/modules/_filters.scss
src/locales/translations.csv

#616
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/782)

Disablezoom

---

bower.json
src/app/geo/geo.service.js
src/app/geo/layer-blueprint.class.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/ui/loader/loader-service.directive.js

Closes #736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/785)

Add EPSG lookups for unknown WKIDs

---

package.json

Upgrade when tracker1/gulp-header#37 is fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/795)

chore(build): pin gulp-header to 1.8.2

---

src/locales/translations.csv

#746 
Requires French translations that will be handled by #764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/786)

feat(ui): update help text

---

gulp.config.js
gulpfile.js
src/app/core/bookmark.service.js
src/app/core/config.service.js
src/app/core/constant.service.js
src/app/core/core.run.js
src/app/geo/geo.service.js
src/app/geo/geo.service.spec.js
src/app/geo/layer-record.class.js
src/app/geo/legend-entry.service.js
src/app/geo/map.service.js
src/app/injector.js
src/app/ui/basemap/basemap.directive.js
src/index-fgp-en.html
src/index-fgp-fr.html
src/index-one.html
src/index-wet.html
src/schema.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/798)

Bookmarking

---

src/app/geo/layer-blueprint.class.js
src/app/geo/legend-entry.service.js
src/app/ui/common/stepper/stepper-item.directive.js
src/app/ui/common/stepper/stepper-item.html
src/app/ui/common/stepper/stepper.class.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/app/ui/loader/loader-service.directive.js
src/app/ui/loader/loader-service.html
src/locales/translations.csv

Provide better feedback to the user when actions are occurring behind the scenes (i.e. trying to connect to a service, loading a file, etc).
In support of #770;
__________
Fix for #800;
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/803)

Import service - better visual feedback

---

src/app/core/bookmark.service.js
src/app/core/core.run.js
src/app/core/reload.service.js
src/app/geo/layer-record.class.js
src/app/ui/basemap/basemap.directive.js
src/app/ui/toc/toc.html

issue #715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/809)

Keep state on projection switch

---

src/app/geo/layer-blueprint.class.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/app/ui/loader/loader-service.directive.js
src/app/ui/loader/loader-service.html
src/locales/translations.csv

Adds a check when the user selects a service type different from a predicted one.
In support of #770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/812)

Import service - service type checks

---

src/app/core/core.run.js

Resolves issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/814
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/817)

fix(core): pass epsg to rcs layers

---

src/app/ui/basemap/basemap.directive.js

issue #826
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/830)

Delay basemap selector until rvReady is fired

---

bower.json
src/app/geo/layer-blueprint-user-options.class.js
src/app/geo/layer-blueprint.class.js

In support of #770
Needs https://reviewable.io/reviews/fgpv-vpgf/geoApi/128 merged first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/838)

Import service - smart default for csv, geojson and shapefiles

---

src/app/core/config.service.js
src/app/ui/common/truncate.directive.js
src/app/ui/toc/templates/placeholder-entry.html
src/app/ui/toc/toc.service.js
src/locales/translations.csv

1- toast messages are now manage by translate service
2- use translate service inside placeholder-entry.html
3- add entries in translations.csv accordingly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/837)

feat(core,ui,locales): french toasts and french msg in toc

---

bower.json
src/app/geo/layer-blueprint.class.js

Needs https://github.com/fgpv-vpgf/geoApi/pull/131 merged first.
In support of #770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/845)

add primary field smart default to imported service-based feature layers

---

src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-service.directive.js

Closes #831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/849)

fix(ui): switch to TOC view on layer import success

---

src/app/layout/shell.directive.js
src/app/layout/shell.html
src/app/ui/toc/templates/entry-flag.html
src/app/ui/toc/toc.directive.js
src/content/styles/modules/_basemap.scss
src/content/styles/modules/_esri-map.scss
src/content/styles/modules/_toc.scss

The map is now the first focusable element. Legend entry flags and settings toggle are now focusable. Added highlighting to map and basemaps on focus.
Closes #52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/811)

feat(ui): tab order changes and decoration

---

src/index-fgp-en.html
src/index-fgp-fr.html

Arrow functions + ie = :boom: :computer:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/854)

fix(build): fix ie error for fgp pages

---

src/app/geo/layer-record.class.js
src/app/ui/common/error.service.js
src/app/ui/toc/toc.service.js

#685 
Toast disappears when successfully loaded
Can reload datagrid if errored the first time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/810)

Attrib reloading

---

src/app/geo/layer-registry.service.js
src/config.en-CA.json

#777 
Also fix the scale dependent layer endpoint URL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/856)

ENHANCE zoom to details for scale dependent layers

---

bower.json
src/app/core/core.module.js
src/app/geo/layer-blueprint-user-options.class.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/content/styles/main.scss
src/content/styles/vendor/_all.scss
src/content/styles/vendor/_minicolors.scss
src/locales/translations.csv

Adds a colour picker to file-based imports. Needs geoApi patch which would actually apply the supplied colour.
In support of #770.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/865)

Colourpicker

---

src/app/ui/details/details-content.html
src/app/ui/details/details-record-esrifeature.directive.js
src/app/ui/details/details-record-esrifeature.html

Closes #819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/871)

feat(ui): solo records in details panel expanded by default

---

src/app/geo/legend-entry.service.js
src/config.en-CA.json

#783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/872)

Scale Zoom Flags not working for Dynamics with Children

---

src/app/ui/details/details-record-esrifeature.directive.js

Closes #818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/881)

feat(ui): expanded point information consistent between panel and modal

---

bower.json

Updates app to use file symbol fix in geoApi
Very complex PR
Closes (in part) https://github.com/fgpv-vpgf/fgpv-vpgf/issues/867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/890)

File Symbology upgrades

---

src/app/geo/legend.service.js
src/config.en-CA.json

Closes #869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/885)

fix(geo): correct logic assigning feature layer symbology

---

src/app/geo/layer-blueprint.class.js

Closes #898
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/899)

fix(ui): fix indentation of sublayer list on import

---

src/app/geo/identify.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/897)

Alias in identify symbol lookup

---

gulpfile.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/875)

Add validate to gulp test

---

bower.json
src/app/ui/toc/toc.directive.js

Closes #750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/903)

fix(ui): add support for autoscrolling during layer drag-n-drop

---

src/app/bootstrap.js
src/app/core/bookmark.service.js
src/app/core/config.service.js
src/app/core/constant.service.js
src/app/core/core.run.js
src/app/core/reload.service.js
src/app/geo/map.service.js
src/index-fgp-en.html
src/index-fgp-fr.html

Bookmarking is now tied to the API, extent is kept on projection switch, API is paused while map is reloading
issues #799 , #833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/904)

Bookmark enhancements

---

src/content/styles/modules/_content-pane.scss

issues #877 , #678 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/906)

fix(ui): clip overflow on close buttons

---

src/app/ui/settings/settings.directive.js
src/locales/translations.csv

Closes #668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/905)

feat(ui): Add query off layer flag

---

src/polyfill/encoding.js

Closes #863
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/912)

TextDecoder polyfill

---

src/app/layout/shell.directive.js
src/app/ui/basemap/basemap.directive.js
src/app/ui/filters/filters-default.directive.js
src/app/ui/sidenav/menulink.html
src/locales/translations.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/921)

Datatable translations

---

src/app/core/bookmark.service.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-service.directive.js

issue #920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/923)

Fix projection switching after adding a layer

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/928)

chore(build): v1.0.0-rc3

---

src/app/geo/layer-registry.service.js
src/app/ui/toc/templates/group-entry.html
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/toc.service.js
src/locales/translations.csv
src/schema.json

#716 
toc.label.boundaryZoom and toc.tooltip.boundaryZoom needs french translation #765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/916)

Zoom to Layer Bounding Box

---

src/locales/translations.csv

issue #925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/927)

User added layer tooltip

---

src/app/layout/shell.directive.js

Keeping the section commented out as there are plans to use the button in the future
issue #934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/936)

refactor(layout): remove share button

---

src/app/ui/loader/loader-service.directive.js

Closes #886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/932)

fix(ui): reset service-based layer import dialog on close/completion

---

src/polyfill/array.fill.js

issue #935 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/938)

chore(build): add array.fill polyfill

---

bower.json

Very complex, please review thoroughly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/940)

Update geoApi reference

---

src/app/ui/details/details-record-esrifeature.directive.js

Closes #893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/945)

fix(ui): details panel shows data on every click

---

src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/ui/toc/toc.service.js
src/schema.json

#873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/950)

"Zoom to" control broken for dynamic layer children

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/991)

chore(build): version 1.0.1-rc1

---

bower.json

Links fixed geoApi for issue https://github.com/fgpv-vpgf/fgpv-vpgf/issues/951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/989)

geoApi fix for wms legend

---

src/app/geo/identify.service.js
src/app/geo/legend.service.js

A number of fixes to avoid errors when Dynamic Layers have Raster sublayers
* Identify will now display standard `No Results` instead of error mess
* Feature count will resolve and show `0 Features`
* Entry in legend will no longer be clickable, thus not opening any data grids
* Fixed additional bug where all identify workers were set to `Done` prior to actually being done
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/957)

Handle raster sublayers

---

src/app/geo/identify.service.js
src/app/geo/init-map.directive.js

Closes #808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/988)

feat(ui): Implement custom keyboard navigation

---

gulp.config.js
src/app/geo/layer-registry.service.js
src/app/geo/legend-entry.service.js
src/app/geo/legend.service.js
src/app/layout/shell.directive.js
src/app/ui/common/dragula.directive.js
src/app/ui/toc/entry-control.directive.js
src/app/ui/toc/templates/entry-control-button.html
src/app/ui/toc/templates/group-entry.html
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/templates/placeholder-entry.html
src/app/ui/toc/toc.directive.js
src/app/ui/toc/toc.service.js
src/content/styles/common/_all.scss
src/content/styles/layout/_all.scss
src/content/styles/layout/_main.scss
src/content/styles/modules/_toc.scss
src/content/styles/vendor/_dragula.scss
src/content/svgCache/editor.svg
src/locales/translations.csv

Closes #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/993)

Allow Layer Re-ordering to be performed using the Keyboard #511

---

src/app/ui/loader/loader-service.directive.js

Closes #952
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/997)

fix(ui): prevent layer import from breaking when immediately closed

---

src/app/geo/map.service.js
src/content/styles/modules/_app-menu.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_content-pane.scss

issues #942, #941
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/998)

IE - Blank basemap and sidenav close button

---

src/locales/translations.csv

It adds a string!
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1004)

Add import service error string

---

src/app/geo/layer-blueprint.class.js
src/app/geo/legend-entry.service.js
src/app/layout/shell.html
src/app/ui/filters/filters-default-menu.html
src/content/styles/base/_all.scss
src/index-fgp-en.html
src/index-fgp-fr.html

Closes #968 #1003 #1006 #1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1014)

Small ui fixes

---

src/app/geo/layer-record.class.js

Change to state transition flow to accommodate invisible and out-of-scale layers.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/980
Will probably want to wait for @alyec to review before pulling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1011)

State transistions for invisible layers

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1015)

chore(build): v1.0.1

---

src/app/ui/loader/loader-service.html

Will use field aliases in the name field list of the service import wizard
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/961
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1021)

Use alias on service import field list

---

src/app/layout/shell.html
src/content/styles/base/_all.scss
src/content/styles/modules/_basemap.scss
src/content/styles/vendor/_special.scss
src/content/styles/vendor/_wet.scss

No muffins.
Closes #1016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1017)

Fixes the colour of basemap names

---

src/content/styles/modules/_filters.scss
src/polyfill/object.entries.js

Closes #1025 #1005
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1026)

Fixes IE button overlap and polyfill pollution

---

src/index-fgp-en.html
src/index-fgp-fr.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1030)

feat(ui): update banner on index-fgp-en/fr.html to GcGeo

---

src/app/geo/layer-blueprint.class.js
src/app/geo/layer-record.class.js
src/app/ui/loader/loader-file.directive.js
src/app/ui/loader/loader-file.html
src/content/styles/modules/_loader.scss
src/locales/translations.csv

#933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1007)

fix(geo): throw error so faulty import dont silently fail

---

src/app/bootstrap.js
src/app/core/constant.service.js
src/app/core/core.run.js
src/app/geo/geo.service.js
src/app/geo/layer-registry.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1033)

feat(core): add debugging options to the bootstrap

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1037)

chore(build): version 1.0.2-rc1

---

src/app/ui/common/icon.decorator.js

Closes #1031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1034)

fix(ui): svg elements inside buttons no longer focusable in IE 11

---

src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js
src/app/geo/geo.service.spec.js
src/app/layout/focus.service.js
src/app/layout/shell.directive.js
src/app/ui/common/morph.directive.spec.js
src/app/ui/common/state.directive.spec.js
src/app/ui/details/details.directive.js
src/app/ui/details/layer-list-slider.directive.js
src/app/ui/filters/filters-default-menu.directive.js
src/app/ui/mapnav/mapnav.service.spec.js
src/app/ui/toc/entry-control.directive.spec.js
src/app/ui/toc/entry-flag.directive.spec.js
src/app/ui/toc/entry.directive.spec.js
src/content/styles/layout/_main.scss

Closes #876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/943)

feat(ui): add focus management support

---

bower.json
src/app/ui/filters/filters-default-menu.html
src/content/styles/modules/_all.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_mapnav.scss
src/content/styles/modules/_md-icon.scss
src/content/styles/vendor/_special.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1040)

chore(build): updated angular material to v1.1.0-rc.5

---

bower.json
src/app/geo/layer-blueprint.class.js
src/app/ui/loader/loader-service.html

#929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1044)

Add group layer import

---

src/app/ui/toc/toc.service.js

Closes #675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1047)

fix(ui): bounding box is hidden when layer is hidden

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1048)

chore(build): version 1.0.2

---

src/app/geo/legend-entry.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1050)

refactor(geo): remove entry name default

---

src/app/geo/legend.service.js

Closes #985
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1052)

fix(ui): layers no longer appear after their placeholders are removed

---

src/app/geo/identify.service.js
src/app/geo/legend-entry.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1008
Adjust buffer size based on projection and zoom level.
Numbers were obtained through trial and error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1055)

Mercator basemap point click buffer size fix

---

src/app/geo/layer-registry.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1057)

fix(geo): zoom to feature works for deeply nested layers

---

src/app/core/bookmark.service.js
src/app/ui/basemap/basemap.directive.js
src/app/ui/basemap/basemap.html
src/app/ui/basemap/basemap.service.js

Closes #913
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1056)

fix(ui): basemap updates on bookmark use

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1058)

chore(build): version 1.1.0

---

src/app/ui/mapnav/mapnav.service.js

Closes #813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1066)

fix(ui): basemap panel animation

---

src/app/core/bookmark.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1069
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1070)

Basemap projection switch zooms to Canada instead of Africa

---

src/app/geo/legend-entry.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1107)

fix(geo): dynamic init set flag

---

src/app/geo/map.service.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/784
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1073)

fix(config): maintain scale on language switch

---

gulp.config.js
src/bookmark-decode.html

Unlocks the power of bookmarks
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1113)

Bookmark decoder page

---

src/app/bootstrap.js
src/app/core/bookmark.service.js
src/app/core/config.service.js
src/app/core/core.run.js
src/app/core/reload.service.js
src/app/geo/layer-registry.service.js
src/index-fgp-en.html
src/index-fgp-fr.html

Issue #415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1118)

Back to cart

---

src/app/geo/legend-entry.service.js

#1046 fix for flags for nested dynamic layers allow zoom to scale to work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1119)

fix(ui): scale and user flags for deeper layers

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1121)

chore(build): version 1.2.0-rc1

---

bower.json
src/app/ui/common/menuItem.decorator.js
src/app/ui/filters/filters-default-menu.html
src/app/ui/loader/loader-menu.html
src/app/ui/toc/templates/entry-control-menu-item.html
src/app/ui/toc/toc.service.js
src/content/styles/layout/_main.scss
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_md-icon.scss
src/content/styles/vendor/_special.scss

Closes #1067, #1105, #1063, #1104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1114)

1067 1063 1105 1104 ui fixes

---

bower.json
src/app/geo/identify.service.js

Pass integer OID from identify to details pane. Prevents local feature search from breaking 
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1041
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1120)

Integer OID from Identify

---

src/app/core/bookmark.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1122)

fix(core): add bookmark rcs layers in all cases

---

src/app/geo/geo.service.js
src/app/ui/basemap/basemap.service.js

Closes #1062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1117)

fix(ui): update basemaps on map reload

---

gulp.config.js
gulpfile.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1129)

Update dist task to generate samples for distribution 

---

src/app/core/bookmark.service.js
src/app/geo/legend-entry.service.js
src/app/ui/toc/toc.service.js

Closes #824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1123)

fix(ui): using bookmark link persists top level visibility

---

src/content/styles/vendor/_special.scss

Closes #1106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1124)

fix(ui): apply correct fonts to dropdown controls

---

src/app/core/bookmark.service.js
src/app/core/reload.service.js
src/app/geo/map.service.js
src/bookmark-decode.html

Use scale instead of scale level in bookmarks. 
Add version key to bookmark. 
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1127)

Use scale in bookmark

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1141)

chore(build): version 1.2.0

---

src/app/core/debounce.service.js
src/app/ui/appbar/appbar.directive.js
src/app/ui/toc/entry-control.directive.spec.js
src/app/ui/toc/entry-flag.directive.spec.js
src/app/ui/toc/entry.directive.spec.js
src/app/ui/toc/toc.service.js

Use a debounce function like in #895
Closes #896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1154)

fix(ui): Datagrid breaks if rapidly opened and closed

---

src/app/ui/toc/toc.service.js

Closes #1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1165)

fix(ui): close filters when layer is removed

---

bower.json
src/app/geo/geo.constant.service.js
src/app/geo/geo.service.js
src/app/geo/layer-registry.service.js
src/app/ui/filters/filters-default-menu.directive.js
src/app/ui/filters/filters-default-menu.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters.service.js
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/toc.service.js
src/locales/translations.csv

Closes #822
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1136)

feat(ui): allow datagrid to be filtered by current extent

---

src/app/geo/layer-blueprint.class.js
src/app/ui/loader/loader-service.directive.js
src/locales/translations.csv

Closes #1109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1173)

fix(ui): allow import of raster layer

---

gulpfile.js
src/app/ui/help/help.directive.spec.js
src/app/ui/help/help.service.js
src/app/ui/help/help.service.spec.js

Closes #1187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1189)

1187 help files missing

---

src/app/ui/filters/filters-default.directive.js
src/app/ui/filters/filters.service.js
src/app/ui/toc/toc.service.js

Closes #1194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1198)

fix(core): adds symbol column to data attributes only once

---

src/index-fgp-en.html
src/index-fgp-fr.html
src/index-jso.html
src/index-many.html
src/index-one.html
src/index-wet.html

Closes #1152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1196)

fix(ui): basic text output when viewing sample pages in old browser

---

src/app/geo/init-map.directive.js
src/app/layout/focus.service.js

Closes #1191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1197)

fix(ui): "Enter" on waiting focus manager no longer triggers identify

---

src/app/layout/shell.html
src/locales/translations.csv

Closes #1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1183)

fix(ui): add map object description

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1201)

chore(build): version 1.3.0-rc1

---

src/app/geo/identify.service.js

Closes #1211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1214)

fix(ui): feature layer icons were missing in identify results

---

bower.json
src/app/core/bookmark.service.js
src/app/geo/legend-entry.service.js

Closes #1169 and #1206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1218)

1169 do not include removed layers in bookmar when removal can be still undone

---

src/app/layout/focus.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1216)

fix(ui): disable mouse focus support

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1219)

chore(build): version 1.3.0-rc2

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1225)

chore(build): version 1.3.0

---

src/app/geo/map.service.js

Closes #986, #1229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1247)

fix(ui): fix zoom in/out functionality error

---

src/app/ui/common/menuItem.decorator.js
src/app/ui/filters/filters-default-menu.html
src/content/styles/vendor/_special.scss

Closes #1195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1246)

feat(ui): Add filter icon and right align datatable options

---

src/app/geo/geo.service.spec.js
src/app/layout/shell.directive.js
src/app/layout/shell.html
src/app/ui/basemap/basemap.directive.js
src/app/ui/basemap/basemap.html
src/app/ui/basemap/basemap.service.js
src/app/ui/mapnav/mapnav.service.js
src/content/styles/layout/_main.scss
src/content/styles/modules/_app-menu.scss
src/content/styles/modules/_basemap.scss
src/content/styles/modules/_mapnav.scss
src/content/styles/modules/_panel-plug.scss

Closes #1244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1249)

feat(ui): basemap panel changed to $mdSideNav

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1257)

chore(build): version 1.4.0-rc1

---

bower.json
src/app/geo/identify.service.js

Closes #1262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1268)

fix(ui): layer names duplicated in the layer results pane

---

bower.json
src/app/bootstrap.js
src/index-fgp-en.html
src/index-fgp-fr.html
src/index-many.html
src/index-one.html
src/polyfill/ie-outer.HTML.js

Closes #1272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1286)

1271 - Fixing export legend appearance in IE

---

src/app/core/bookmark.service.js
src/app/core/constant.service.js
src/app/geo/layer-record.class.js
src/app/geo/legend-entry.service.js
src/app/geo/map.service.js
src/bookmark-decode.html
src/schema.json

Sibling PR of https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1266 , targeting `release-v1.4.0` instead of `develop`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1299)

Bookmark Version B for Release v1.4.0

---

src/app/geo/map.service.js
src/app/ui/filters/filters.service.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1311)

Add angular broadcasts for extentChange

---

bower.json
package.json
src/app/core/bookmark.service.js
src/app/core/constant.service.js
src/app/geo/layer-record.class.js
src/app/geo/legend-entry.service.js
src/app/geo/map.service.js
src/bookmark-decode.html
src/schema.json

1.4, 1.5, and 1.6 branches will be created from develop after this. All new PRs need to target their respective release branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1317)

Merging 1.4 back into develop

---

src/app/common/router/statemanager.constant.service.js
src/app/common/router/statemanager.service.spec.js
src/app/geo/geo-search.service.js
src/app/geo/geo.service.spec.js
src/app/geo/map.service.js
src/app/ui/appbar/appbar.html
src/app/ui/geosearch/geosearch-content.directive.js
src/app/ui/geosearch/geosearch-content.html
src/app/ui/geosearch/geosearch-filters.directive.js
src/app/ui/geosearch/geosearch-filters.html
src/app/ui/geosearch/geosearch.directive.js
src/app/ui/geosearch/geosearch.html
src/app/ui/geosearch/geosearch.module.js
src/app/ui/geosearch/geosearch.service.js
src/app/ui/panels/main-panel.html
src/app/ui/ui.module.js
src/config.rcs.en-CA.json
src/content/styles/modules/_all.scss
src/content/styles/modules/_appbar.scss
src/content/styles/modules/_geosearch.scss
src/locales/translations.csv

Closes #1175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1283)

feat(ui): Create UI for GeoSearch Component

---

src/app/ui/mapnav/mapnav.html
src/content/styles/modules/_mapnav.scss

Closes #1310.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1319)

fix(ui): prevent mapnav controls from overlapping

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1321)

chore(build): update version to 1.4.0-4

---

src/app/common/router/statemanager.service.js
src/app/ui/details/details-expand.html
src/app/ui/filters/filters-default-menu.html
src/app/ui/filters/filters-default.directive.js
src/app/ui/metadata/metadata-expand.html
src/app/ui/panels/content-pane.html
src/content/styles/common/_breakpoints.scss
src/content/styles/layout/_main.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_details.scss
src/content/styles/modules/_mapnav.scss
src/content/styles/modules/_toc.scss
src/content/styles/vendor/_esri.scss

For device widths <= 840
Closes #1243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1276)

feat(ui): add support for medium sized viewports

---

src/content/styles/vendor/_special.scss

Closes #1325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1327)

fix(ui): navcontrols misplaced in full-screen mode

---

pull_request_template.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1331)

chore(build): add a pull request template

---

src/app/ui/toc/toc.service.js

Before: when a layer is removed, corresponding displayed panel
(Settings or Metadata) is still displayed
After: when a layer is removed, corresponding displayed panel
(Settings or Metadata) is removed too. If the toast UNDO button is pushed,
the previously displayed info panel reappears with the layer entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1322)

fix(ui): remove displayed info panels when layer is removed

---

src/app/ui/geosearch/geosearch.service.js

Closes #1278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1329)

fix(ui): config ignore when switch language for geosearch

---

src/app/core/reload.service.js
src/app/geo/geo-search.service.js
src/app/geo/map.service.js
src/app/layout/shell.directive.js
src/config.fr-CA.json

Throw rvLangSwitch event for items to listen and react at a language switch
Closes #1278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1328)

fix(ui) Set map whit configuration file when language switch

---

bower.json
package.json

It's a weekly build. Using unpublished geoApi 1.1.0-1 since it has fixes for map export bugs.
Nope.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1349)

chore(build): weekly build weekly-1.4.0-5

---

devdeploy.sh

Remove the dev samples folder before unzipping dev samples.
Nope.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1350)

chore(build): clear dev sample pages folder on deploy

---

src/polyfill/ie-string.repeat.js

#1284 #1339 
It's a polyfill from MDN.  I hope they tested it.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1352)

fix(core): add string.repeat polyfill for IE

---

src/app/ui/export/export-legend.service.js
src/app/ui/export/export.service.js

Enables export legend optimization from https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1271.
Eyeballing tests. Unit tests for optimization logic are done in geoApi under https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1271.
Updated comments.
Closes #1371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1372)

feat(export): enable export legend optimization

---

bower.json
package.json

Correcting version number - weekly build automation reads `package.json` for this number.
None
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1375)

chore(build): correct version number

---

bower.json
package.json

Version 1.4.0-6 build
None
Pre-release notes to follow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1378)

chore(build): version 1.4.0-6

---

devdeploy.sh

Fixes an issue with stale builds remaining on the demo server
n/a - build related
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1387)

chore(build): fix deployment script for branches

---

bower.json
package.json
src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/schema.json

Option to have map extent restricted to maximum extent (as defined by the config).
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1320
There are unit tests in the geoApi part.
jsdoc, config schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1391)

Extent Restriction

---

src/app/ui/details/details-record-esrifeature.directive.js

Issues fgpv-vpgf/fgpv-vpgf#1379
Test it with service added layer, csv added layer and config file layer
none
Closes #1379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1400)

fix(bug): not able to zoom to in deteails panel for service added layer

---

src/app/app.module.js

Layer Reordering not working as expected in IE11 #1392
Manual testing with IE11
Closes #1392
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1407)

fix(ui): let IE11 in debug mode

---

src/app/ui/common/reverse.filter.js

Bandaid solution to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1397
Error no longer happens
None, thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1446)

Squish Reverse Filter Errors

---

bower.json
package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1451)

chore(build): version 1.4.0-8

---

src/content/styles/modules/_export.scss
src/locales/translations.csv

Fill in missing translations.
Fix a tiny bug with the title input field in the export dialog.
Eyeballing.
Not needed.
~- [ ] release notes have been updated~ not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1456)

chore(export): add missing translations

---

src/app/ui/help/help-summary.html
src/app/ui/help/help.service.js
src/content/styles/modules/_help.scss
src/content/styles/modules/_lists.scss

Add collapsible section to the help dialog. 
Eyeballing.
Not required.
Closes #1443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1467)

feat(ui): make help section collapsible

---

bower.json
package.json
src/app/geo/layer-registry.service.js
src/app/geo/map.service.js
src/app/ui/common/reverse.filter.js
src/app/ui/filters/filters-default.directive.js
src/app/ui/help/help-summary.html
src/app/ui/help/help.service.js
src/content/styles/modules/_help.scss
src/content/styles/modules/_lists.scss
src/schema.json

move develop from tracking 1.4 to 1.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1484)

v1.5 rebase

---

src/app/ui/help/help-search.directive.js
src/app/ui/help/help-search.html
src/app/ui/help/help-summary.html
src/app/ui/help/help.service.js
src/app/ui/panels/content-pane.directive.js
src/content/styles/modules/_buttons.scss
src/content/styles/modules/_content-pane.scss
src/content/styles/modules/_help.scss
src/locales/translations.csv

Adds a search box to the help dialog. Check the demo, it's cool.
Eyeballing.
Source code comments.
Closes #1444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1514)

1444 help search

---

src/config.fr-CA.json
src/config.rcs.fr-CA.json

French - Canada View going to scale of 1000km and including South America #1361
Manual testing with index-fgp-fr.html
Closes #1361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1524)

fix(test): scale to 400km on Canada view for index-fgp-fr.html

---

src/index-fgp-fr.html

Missing ENGLISH toggle button when loaded FGP Visualiser from index-fgp-fr.html #1468
Manual test with index-fgp-fr.html
Closes #1468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1528)

fix(test): English available for index-fgp-fr.html

---

src/locales/translations.csv

shapefile cannot be imported unless it is zipped #1506
Manual test
Closes #1506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1538)

fix(locales): change label Shapefile for zipped Shapefile

---

src/app/layout/shell.directive.js
src/config.en-CA.json
src/schema.json

Added schema option legendIsOpen where default can be changed from false
to true for the three viewport sizes; small, medium, and large
Closes #1338
👀 
inline comment added to `shell.directive.js`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1496)

feat(ui): legend panel can be opened by default

---

src/app/geo/identify.service.js

Point Information not displayed in the details Pane for "Polygon" layers #1537
Manual testing with Shapefiles and geoJson files
Closes #1537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1542)

fix(geo): identify polygon features coming from added file

---

src/app/geo/legend.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1453
Tested against local WMSes. Will add unit tests after code is migrated to geoAPI
Function headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1543)

Use WMS layer title in legend

---

src/locales/translations.csv

Closes #1521, #1522, #1523
👁 
None needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1567)

fix(ui): Improve help section text

---

src/app/ui/toc/toc.directive.js

Closes #1545
Works on chrome desktop, and on iPhone. Needs testing on android
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1583)

fix(ui): autoscroll drag-n-drop support for mobile

---

src/app/core/constant.service.js
src/app/geo/geo.service.spec.js
src/app/geo/init-map.directive.js
src/app/geo/layer-record.class.js
src/app/geo/layer-registry.service.js
src/app/ui/tooltip/tooltip-hover.html
src/app/ui/tooltip/tooltip.directive.js
src/app/ui/tooltip/tooltip.service.js
src/content/styles/modules/_all.scss
src/content/styles/modules/_tooltip.scss
src/content/styles/vendor/_esri.scss
src/locales/translations.csv
src/schema.json

Rebased version of #1569 with a clean commit list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1584)

Hover tips

---

src/index-fgp-fr.html

Left Sided Menu defaulted to English when loaded FGP Visualiser from index-fgp-fr.html #1539
Manual test with index-fgp-fr.html
Closes #1539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1582)

fix(test): add rv-langs with French as default in index-fgp-fr.html

---

src/index-fgp-en.html

Closes #1587
Code is in the sample HTML pages, not in the core lib.
n/a bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1588)

Remove arrow functions in samples

---

src/app/ui/loader/loader-file.html

Error message not disappearing when closing import file window #1505
Manual testing with Chrome and Firefox
Closes #1505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1592)

fix(ui): remove ng-if in div

---

bower.json
src/app/common/formatters.filter.js
src/app/geo/identify.service.js
src/app/geo/layer-record.class.js
src/app/ui/details/details-record-esrifeature.directive.js
src/app/ui/filters/filters-default.directive.js

Testing layer:
http://section917.cloudapp.net/arcgis/rest/services/TestData/TimeParty/MapServer/0
Closes #1330
:eye: 
None needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1591)

fix(ui): ESRI date field now includes time

---

src/index-fgp-en.html
src/index-fgp-fr.html

FGP Visualiser incl. basemap still in English after toggling to French #1513
Manual and visual test with index-fgp-fr.html and index-fgp-en.html
Closes #1513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1596)

fix(test): add lang parameter to config filename

---

src/app/common/formatters.filter.js
src/app/geo/identify.service.js
src/app/ui/filters/filters-default.directive.js

Closes 
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1601
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1608
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1597
WOMM
Added a missing jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1612)

Date filter bugs squashed

---

src/app/ui/filters/filters-default.directive.js

Closes #1593
Eye
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1615)

fix(filters): not able to load sublayer in Eco

---

src/app/ui/filters/filters-default.directive.js
src/app/ui/toc/toc.service.js
src/content/styles/modules/_filters.scss

Same PR as https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1641 except rebased on develop while Johann is away.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1649)

fix(filters): details and zoom function missing

---

src/app/bootstrap.js
src/app/core/core.run.js
src/plugins/core/back-to-cart.js

#1632
plugins are hard to test
comments only
- release notes have been updated (fix for an unreleased bug)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1651)

Back to Cart plugin fix

---

src/app/ui/sidenav/share-dialog.html
src/app/ui/sidenav/sidenav.service.js
src/locales/translations.csv

Share Link not working in IE11 for both Short Link and Long Link #1284
Test with IE11, Fox and Chrome
Closes #1284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1653)

fix(ui): automatic URL selection in share dialog input field

---

src/app/ui/basemap/basemap-item.html
src/index-fgp-fr.html
src/locales/translations.csv

Review du Français #1610
Visual review
Closes #1610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1663)

fix(locales): French review and interface language fixes

---

src/app/core/bookmark.service.js
src/app/core/config.service.js
src/app/core/reload.service.js
src/app/geo/layer-registry.service.js
src/app/ui/toc/toc.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1657 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1658
Tested a medley of language change, bookmark, and back to cart with RCS and file-config based layers
JSDocs. WIki update pending for loading flow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1667)

Handle RCS keys on language change

---

src/app/bootstrap.js
src/index-fgp-en.html
src/index-fgp-fr.html
src/index-one.html

#1665 
Sample page, browser testing
Will get added to custom attribute doc pages.
- release notes have been updated (n/a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1670)

Data attribute translation

---

bower.json
package.json

RC3 release
nay
nay
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1676)

chore(build): version 1.5.0-rc3

---

src/app/core/bookmark.service.js
src/app/ui/toc/toc.service.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1674 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1677
Medley of bookmark, back to cart, and language change
Comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1675)

Language mismatch in RCS bookmark

---

bower.json
package.json

Version 1.5.0 release
yes
yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1684)

chore(build): version 1.5.0

---

docs/user/working_examples.md
src/app/bootstrap.js
src/content/styles/_error.css
src/content/styles/main.scss
src/content/styles/vendor/_special.scss
src/index-fgp-en.html
src/index-fgp-fr.html
src/index-jso.html
src/index-many.html
src/index-mobile.html
src/index-one.html
src/index-wet.html

Closes #1672
deprecate class fgpv on v2.0
:eye: 
yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1701)

fix(ui): deprecate class fgpv on v2.0

---

bower.json

Looks like focus manager wins this round.
Closes #1515
:eye: 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1703)

fix(ui): update angular material for focus fix

---

bower.json

Pins the RColor dependency to sort out the demo build.
Browser testing only
n/a
- (n/a) release notes have been updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1708)

Pin RColor dependency

---

src/app/ui/details/details-content.html

Identify error on OGC/WMS added layer fgpv-vpgf/fgpv-vpgf#1614
Manual test with the three amigos IE11,Chrome and Fox
Closes #1614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1706)

fix(ui): update layer record OGCWMS selection

---

src/app/geo/map.service.js
src/app/ui/tooltip/tooltip.service.js

Closes #1604
:eye: 
jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1713)

fix(ui): remove hovertip on highlight

---

src/app/focus-manager.js

Dialog will now correctly display when tabbing quickly
Closes #1377
:eye: 
jsdoc, inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1714)

fix(ui): focus dialog improvement

---

bower.json
package.json

Version 1.5.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1718)

chore(build): version v1.5.1

---

src/app/ui/common/full-screen.service.js
src/app/ui/mapnav/mapnav.directive.js
src/app/ui/mapnav/mapnav.html
src/app/ui/mapnav/mapnav.service.js

Applies to embedded maps only
Closes #559
:eyes: 
Yes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1717)

feat(mapnav): Added fullscreen toggle to mapnav

---

bower.json

Sinon moved their release files. Bardjs now fetches Sinon by itself.
Nope.
Nope.
- ~~[ ] release notes have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1724)

fix(core): update dependencies

---

src/app/bootstrap.js

Closes #1702
Yes
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1729)

fix(logging): allow non-tested dependency warnings

---

bower.json
package.json

v1.5.2 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1731)

chore(build): version 1.5.2

---

src/app/common/router/statemanager.service.js
src/app/common/router/statemanager.service.spec.js
src/app/geo/map.service.js
src/app/ui/common/morph.directive.spec.js
src/app/ui/common/state.directive.spec.js
src/app/ui/panels/panel.directive.js
src/app/ui/toc/entry-control.directive.spec.js
src/app/ui/toc/entry-flag.directive.spec.js
src/app/ui/toc/entry.directive.spec.js

Main panel width and filters panel height now accounted for when
centering the zoom to feature item.
Closes #1629
👁 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1707)

fix(ui): zoom to feature placement on map now cenetered

---

src/app/geo/layer-registry.service.js
src/app/geo/map.service.js

See issue #1637 for details
Closes #1637
Works with CESI layer provided, additional tested may be needed
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1721)

fix(layerRegistry): workaround fix provided for issue 1637

---

bower.json
docs/developer/contributing_guide/geo_merging.md
docs/developer/contributing_guide/index.json
docs/developer/index.json

Update geoApi to v1.1.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1764)

chore(geoApi): update version to v1.1.3

---

bower.json
package.json

Develop to v1.5.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1765)

chore(build): version 1.5.3

---

bower.json
docs/developer/contributing_guide/geo_merging.md
docs/developer/contributing_guide/index.json
docs/developer/index.json
gulpfile.js
package.json
src/app/bootstrap.js
src/content/styles/common/_all.scss

Master to v1.5.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1766)

Master to v1.5.3

---

gulp.config.js
src/app/geo/geo.constant.service.js
src/app/geo/legend.service.js
src/app/ui/toc/templates/layer-entry.html
src/app/ui/toc/toc.service.js
src/content/svgCache/alert.svg
src/locales/translations.csv

Closes #1186
:eye: 
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1758)

fix(ui): add icon indicating tile layer in wrong projection

---

src/app/geo/layer-registry.service.js

Closes #1433
Yes
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1748)

fix(ui): fixed failed to load indication

---

src/app/ui/basemap/basemap.service.js

Closes #1296
In browser
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1769)

feat(ui): layers are now 0.86 transparent when basemap open

---

docs/user/custom_attributes.md
docs/user/working_examples.md
src/app/core/core.run.js
src/app/focus-manager.js
src/app/ui/common/full-screen.service.js
src/app/ui/mapnav/mapnav.directive.js
src/app/ui/mapnav/mapnav.service.js
src/app/ui/sidenav/sidenav.service.js
src/config-mobile.json
src/config.en-CA.json
src/config.fr-CA.json
src/index-mobile.html
src/index-one.html
src/schema.json

removes the rv-fullpage-app attribute on rootElement
Closes #834
Yes
some inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1768)

feat(config): add support for fullpage viewers

---

src/app/core/core.config.js

Errors are showing up in our builds.
Implements the bugfix from https://github.com/angular-translate/angular-translate/issues/949
Library bugfix, testing in browser locally.
bugfix n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1803)

Set priority for translateProvider

---

src/config.en-CA.json
src/config.fr-CA.json
src/config.rcs.en-CA.json
src/config.rcs.fr-CA.json

Normalize English and French configuration files
Closes #1691
Chrome
No need
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1774)

style(config): Normalize English and French configuration files
