- .jshintrc
- src/app/layout/filters-panel-plug.controller.js
- src/app/layout/side-panel-plug.controller.js
- src/app/ui/filters/filters-default.directive.js
- src/app/ui/filters/filters-default.html
- src/app/ui/panels/content-pane.directive.js
- src/app/ui/panels/content-pane.html
- src/app/ui/panels/filters-panel.directive.js
- src/app/ui/panels/side-panel.directive.js
- src/app/ui/toc/toc.html
- src/content/styles/modules/_buttons.scss
- src/content/styles/modules/_content-pane.scss
- src/content/styles/modules/_content-plug.scss
The content pane directive now has a close button that executes a `closePanel` function found on its parent plug's `ngController`. The button is not shown if the function is undefined.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/56)
> feat(ui): add close button to content panes

- src/app/ui/common/toggle-slide.animation.js
- src/app/ui/toc/layer-group-toggle.html
- src/app/ui/toc/toc.html
- src/content/styles/modules/_toc.scss
I was using `ng-if` to toggle layer groups, but this removes and reinserts them into the dom every time which can get slow, especially with many layers. Changed to using `ng-show` and updated the animation to work with that as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/65)
> perf(ui): do not remove layer groups from dom when toggled

- docs/config/templates/common.template.html
- package.json
- src/app/core/config.service.js
caused by template issue: common.template.html missing marked filter.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/67)
> docs: resolve markdown not rendered in configService

- src/app/ui/common/toggle-slide.animation.js
"open" is a native browser function; this is why it was not picked up during linting.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/84)
> fix(ui): stupidity

- src/app/ui/filters/filters-default.html
- src/app/ui/metadata/metadata.html
- src/app/ui/panels/content-pane.directive.js
- src/app/ui/panels/content-pane.html
- src/app/ui/settings/settings.html
- src/app/ui/toc/toc.html
- src/app/ui/toolbox/toolbox.html
"title" is a proper html attribute; renamed to "title-value" to avoid collisions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/83)
> fix(ui): rename title attributes used in content pane

- src/app/ui/mapnav/mapnav.service.js
Forgot to change actual zoom calls. Is it muffins? If it is, who is responsible?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/215)
> bug(ui): change setZoom calls to shiftZoom

- gulpfile.js
- src/app/common/router/displaymanager.service.js
- src/app/common/router/statemanager.constant.service.js
- src/app/common/router/statemanager.service.js
- src/app/core/config.service.js
- src/app/layout/shell.controller.js
- src/app/ui/appbar/appbar.html
- src/app/ui/details/details.directive.js
- src/app/ui/details/details.html
- src/app/ui/filters/filters-default.directive.js
- src/app/ui/toc/toc.service.js
- src/app/ui/toc/toc.service.spec.js
A bit of reorganization of the statemanager: some code in toc handling data display (like metadata, filters) is abstracted and moved to a new service - `displayManager`.
`stateManager` handles layout - opening/closing panels, morphing between different views (filters panel).
`displayManager` handles the display of dynamically retrieved/generated data (layer metadata, attributes, details); it uses `stateManager` internally to open/close panels.
Suggestions are welcome.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/295)
> statemanager / displaymanager

- src/app/geo/geo.service.js
- src/schema.json
Add layer opacity to schema
Support layer visibility, opacity, and snapshot/onDemand from config
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/343)
> feat(geo): support more layer options from config

- src/app/geo/geo.service.js
- src/app/geo/geo.service.spec.js
- src/app/geo/identify.service.js
- src/app/ui/toc/toc.service.js
This Pull Request (for now) is to get feedback on the changes to layer attributes.  If the team is OK with it, another commit will be done to align the grid load and any .spec tests with the changes.  Online docs will also be updated
Summary: the `.attribs` property of the entry in the layer registry is now a promise that resolves with the attribute bundle.  Previously the property would be undefined while loading, then set to the bundle outright.
It now makes it easier for code using the attributes to wait for them to load.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/364)
> feat(geo): better asynch for attribute load

- gulp.config.js
- gulpfile.js
- src/app/core/config.service.js
- src/app/core/core.run.js
- src/app/core/global-registry.service.js
- src/app/geo/gapi.service.js
- src/app/geo/geo.service.js
- src/app/geo/geo.service.spec.js
- src/app/geo/identify.service.js
- src/app/geo/init-map.directive.js
- src/app/geo/layer-registry.service.js
- src/app/geo/layer-registry.spec.js
- src/app/geo/map.service.js
- src/app/global-registry.js
- src/app/layout/shell.directive.js
- src/app/layout/shell.directive.spec.js
- src/app/layout/shell.html
- src/app/ui/filters/filters-default.directive.js
- src/app/ui/mapnav/mapnav.service.spec.js
- src/app/ui/toc/layer-group-toggle-button.directive.spec.js
- src/app/ui/toc/layer-group-toggle.directive.spec.js
- src/app/ui/toc/layer-item-button.directive.spec.js
- src/app/ui/toc/layer-item-flag.directive.spec.js
- src/app/ui/toc/layer-item.directive.spec.js
- src/app/ui/toc/toc.service.js
- src/config.fr.json
Causes __Panic__ for 60min.
New services created: `layerRegistry`, `mapService` and `gapiService`. They do not directly depend on `geoService`.
`layerRegistry` manipulation with layers mostly (generate, register, remove, etc.)
`mapService` used to register map node and hold reference to the map object
`gapiService` holds reference to gapi
`gapi` loading is hoisted and now starts when the lib package is download, even before `app-seed` initializes app instances.
`identifyService` now accesses layers directly from `layerRegistry`, not storing them itself. This solves the growing number of layers when swapping configs. #367
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/381)
> Proposal: split geoService !important

- bower.json
- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
- src/app/ui/toc/layer-item-flag.html
- src/app/ui/toc/layer-item-symbology.html
- src/app/ui/toc/layer-item.html
- src/app/ui/toc/toc.service.js
- src/config.en.json
Added more stuff to `legendService`:
- generates dynamic legend layer entries with symbology
- generates feature legend entries with symbology
- generates esri image with default symbology
Next:
- ~~if dynamic layer has only one child layer, omit the group entry~~ :point_up: [March 17, 2016 10:23 AM](https://gitter.im/fgpv-vpgf?at=56eabdda3194fbd11097e879)
- add wms legend to the layer selector
- connect dynamic layer children to the appropriate datatables
- generate options/flags for dynamic layer children 
- connect settings/visibility/opacity of dynamic layer children to layer selector
- include only dynamic layer children specified in the config layerEntries
- omit data/image groups if they have no layers
- add options to remove groups (dynamic layer)
- add options to change settings …
> Legend Service cont.

- bower.json
- src/app/geo/layer-registry.service.js
- src/app/geo/legend-entry.service.js
- src/app/geo/legend.service.js
- src/app/ui/settings/settings.directive.js
- src/app/ui/settings/settings.html
- src/app/ui/toc/toc.html
- src/app/ui/toc/toc.service.js
- src/config.en-CA.json
- src/content/styles/modules/_setting-controls.scss
- src/content/styles/modules/_toc.scss
Opacity works for all layers except dynamic layers with `supportsDynamicLayers` set to false.
Initial opacity from config is applied correctly to all layers.
Fixed highlighting of toc entries (both groups and singles) when opening settings, metadata or attribute panels.
Settings like opacity and bounding box which are not supported by certain toc entries are hidden in the settings panel.
Empty setting sections in the settings panel are hidden.
Closes #434 and #442.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/481)
> Toc update (< 30 files)

- src/content/styles/modules/_details.scss
No truncation or tooltips needed
Removes horizontal scrollbar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/540)
> Change how feature details are displayed

- src/app/ui/common/menuItem.decorator.js
- src/app/ui/toc/templates/entry-control-menu-item.html
- src/content/styles/modules/_symbology.scss
- src/content/styles/vendor/_special.scss
- properly center single-image legends
- show text on layer menu buttons (settings, metadata, etc.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/561)
> Fix Firefox and IE layout issues

- src/app/core/config.service.js
- src/app/ui/filters/filters-default.directive.js
- src/locales/translations.csv
Had to move ZOOM_TO_ICON inside createTable so that tooltip language change can trigger when the table is being loaded.  Before when the ZOOM_TO_ICON was global in the file, if you loaded the app in English, then switched language to French, it wouldn't know to translate the tooltips to French.
Closes #546
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/586)
> Translate zoom to feature tooltip

- src/app/ui/toc/entry-symbology.directive.js
- src/app/ui/toc/entry.directive.js
- src/app/ui/toc/templates/layer-entry.html
- src/content/styles/modules/_symbology.scss
- src/content/styles/modules/_toc.scss
Layer name now above graphic, resizing done with GreenSock lib.
Closes #517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/588)
> fix(ui): layer symbology graphics enlarged on legend expansion

- src/content/styles/modules/_esri-map.scss
- src/content/styles/vendor/_all.scss
- src/content/styles/vendor/_wet.scss
All clicks on the map was offset so it creates problem for identify click and shift-zoom. WET does not prefix their css class so this kind of problem may append again
Closes #623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/631)
> fix(layout): overwite padding set by wet css class on .container

- src/polyfill/object.entries.js
PhantomJS is old and doesn't deal with `bind` very well.  If we switch polyfills for Object.entries we can fix this.  PR outside of the window since `gulp test:auto` fails on every reload after the first test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/705)
> Fix for Object.entries polyfill and phantomjs

- src/app/geo/legend-entry.service.js
Previously the visibility of a layer group did not correctly update when the visibility of a child layer changed. If all child layers for example were hidden, the group layer would remain visible. Now changes to child layer visibility correctly update the group layer. A group is considered visible if all children in the group are visible, otherwise it is hidden.
Closes #663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/722)
> fix(ui): layer group visibility updates on child layer visibility change

- src/app/core/config.service.js
- src/app/core/core.run.js
RunBlock (core.run) execution set the language by default to en-CA
while the configService generate fr-CA as the only key
if rv-langs = '[fr-CA]' so a conflict is generate at configService.getCurrent() call
Solution: remove RunBlock language setting and set the config or default language
in configService right after the rv-langs value extraction
Closes #620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/757)
> fix(core): set default language at configService init

- src/app/layout/shell.directive.js
- src/app/layout/shell.html
- src/app/ui/details/details-expand.directive.js
- src/app/ui/details/details-modal.html
- src/app/ui/details/details.directive.js
- src/app/ui/metadata/metadata-content.directive.js
- src/app/ui/metadata/metadata-expand.directive.js
- src/content/styles/modules/_loading.scss
The disableParentScroll property of $mdDialog must be false for correct placement of the expand panel. See https://github.com/angular/material/blob/master/src/components/backdrop/backdrop.js#L35 for more details.
Closes #669, #717, #718, #763
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/781)
> fix(ui): expand panel position and data

- gulpfile.js
- package.json
run `gulp serve --guts` to skip js style checks
P.S.: wanted `lazy` flag, but node already has one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/792)
> chore(build): add lazyguts mode

- src/app/common/router/statemanager.service.js
- src/app/common/router/statemanager.service.spec.js
- src/app/layout/shell.directive.js
- src/app/ui/appbar/appbar.directive.js
- src/app/ui/details/details.directive.js
- src/app/ui/filters/filters-default-menu.directive.js
- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-service.directive.js
Previously the escape key closed all panels. Now the escape key only
closes one panel, the most recent one opened. Focus is set on an opening
panel and restored to the previous panel on close.
Closes #622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/751)
> feat(ui): escape key closes from history

- src/index-fgp-en.html
- src/index-fgp-fr.html
A default configuration file must still be provided; use this feature to
supply a second configuration file which adds or overwrites the default
configuration properties. Append "#?config=config.json"
to the URL, replacing config.json to the name of your second configuration file.
Closes #828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/848)
> feat(ui): allow optional config file as URL parameter

- src/app/common/router/statemanager.service.js
- src/app/ui/common/morph.directive.spec.js
- src/app/ui/details/details.directive.js
Note that closing callbacks are now run in place of the default
closing logic. This change allows closing logic to be uniform across
the application irregardless of how closing is invoked.
Closes #842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/860)
> fix(ui): details panel no longer closes main panel if open

- src/app/geo/identify.service.js
- src/app/geo/layer-blueprint.class.js
- src/app/ui/loader/loader-service.html
- src/config-all.en.json
- src/config-demo.json
- src/config-sample-structure.json
- src/config.en-CA.json
- src/config.fr-CA.json
- src/config.rcs.en-CA.json
- src/config.rcs.fr-CA.json
- src/schema.json
Will allow a feature name field to be consumed and used from config file, RCS, and user added layer wizard.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/866)
> Use name field config values

- gulpfile.js
Moves uglify task to the end of the concat chain - instead of uglifying parts, uglify two resulting files only (core.js and bootstrap.js).
Generates external sourcemaps with `--prod`. This won't give you proper sourcemaps - this let's you somewhat debug production builds.
In Chrome, currently, mapping local variables doesn't work when names are mangled (uglified); see this issue https://github.com/gruntjs/grunt-contrib-uglify/issues/325; it works in latest Canary.
In support of #293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/882)
> chore(build): add sourcemaps to prod build

- src/app/common/router/statemanager.service.js
- src/app/common/router/statemanager.service.spec.js
The focus was being set to the close button on the main panel at the beginning of the transition (not waiting for child promises to resolve). The initial panel's position (shifted upwards) put the button above the app container (even above the top border of the page) and by focusing on it, the page would scroll up.
Closes #815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/880)
> Focusfix 815

- src/app/geo/identify.service.js
- src/app/geo/layer-blueprint.class.js
- src/app/ui/details/details.directive.js
- src/config.en-CA.json
* change sample tile to be in same projection as app default
* make url slash-stripping only occur on feature layers to stop breaking geomet
* incidental fix to object id lookup on aliased object id field when doing identify on dynamic layers
* incidental fix to identify group hilight where feature index of `0` would trigger a falsy check
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/915)
> Fix broken sample layers

- src/index-fgp-en.html
- src/index-fgp-fr.html
Look and feel now mimics GcGEO layout as per http://redmine.gcgeo.gc.ca/redmine/issues/4478.
The green GcGeo bar above the navigation bar is omitted since it was not included for download on redmine.
Closes #861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/937)
> feat(ui): index-fgp-en/fr.html sample pages updated

- bower.json
Allow app to use geoApi version containing fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/948
Please review thoroughly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1002)
> Use geoApi v1.0.1-5

- src/app/geo/identify.service.js
Resolves various errors caused by code execution on loading legend entry
items. Loading entries will not be displayed.
Closes #790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/999)
> fix(ui): omit loading layers from identify

- src/app/geo/layer-registry.service.js
- src/app/geo/map.service.js
- src/app/ui/details/details-record-esrifeature.directive.js
- src/app/ui/filters/filters-default.directive.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/949
Changed things to use the ZoomToScale function in layerRegistry since it already does the same thing anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/992)
> Zoom not respecting visible scales for dynamic layers

- src/app/geo/identify.service.js
Use offscale status when deciding if a dynamic sublayer should be part of the identify results.  Pass valid layers to server to prevent it from querying invalid sublayers
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1023)
> Dont identify offscale dynamic sublayer

- src/app/ui/filters/filters-default.directive.js
- src/content/styles/modules/_filters.scss
It's not possible to reuse a single compiled directive for all the zoom and details button in the table. We have to compile a directive for each button with a shared scope.
When table is being rendered, placeholder markers for zoom and details buttons are inserted. On the `draw.dt` event, placeholders are replaced with properly compiled buttons.
Closes #766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1024)
> Turn datatable "details" and "zoom in/out" "buttons" into real buttons

- src/index-fgp-en.html
- src/index-fgp-fr.html
- src/index-jso.html
- src/index-many.html
- src/index-one.html
- src/index-wet.html
`document.write` for script loading: JS best practices +1
For the moment this is the simplest reasonable fix, and it is only for sample pages
Should close #1042 and #1043 when merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1049)
> Make IE load polyfills consistently

- src/app/layout/shell.directive.js
Closes #889, #1036
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1045)
> fix(ui): ESRI generated svg elements no longer focusable in IE 11

- bower.json
- src/app/geo/locate.service.js
- src/app/geo/map.service.js
- src/app/ui/mapnav/mapnav.service.js
- src/app/ui/mapnav/mapnav.service.spec.js
Previously we used the [geolocator
library](https://github.com/onury/geolocator) for finding a users
location. This library has now been removed.
A users location is found by using the browsers built-in location support.
If this fails AND there exists a valid Google API key named "googleAPIKey"
in the config then we will attempt to locate the user using Google's
geolocation API.
For testing purposes you can use `AIzaSyD_FwYU_mT1xhTdUoiHBRjwToWUe--KVVU`
as the value for "googleAPIKey" in your config.
Closes #954, #686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1051)
> fix(ui): geolocation now correctly finds your location

- src/app/geo/map.service.js
Previously we used the third last LOD as the zoom level. Now we give
preference to the layer closest to a 50K scale.
Closes #874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1054)
> fix(ui): Zoom to location more uniform between projections

- bower.json
- src/app/common/common.module.js
Fixes travis build error on tagging - previously jsdocs would not generate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1059)
> chore(build): version 1.1.0

- src/app/ui/toc/toc.service.js
Fixes an issue where the bounding box remains visible when the settings
panel is closed and the layer is hidden
Closes #675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1065)
> fix(ui): Bounding box is hidden when layer is hidden

- src/app/core/constant.service.js
- src/app/core/core.run.js
Related to bug #1131. The bug itself was accidentally prevented by PR #1117, but the underlying cause remained. 
`rvReady` event should not be broadcasted twice, and nothing should listen to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1135)
> fix(ui): prevents rvReady from being fired multiple times

- src/app/core/bookmark.service.js
- src/app/geo/layer-record.class.js
- src/app/ui/settings/settings.directive.js
Update Legend snapshot value when snapshot is enabled.
Disable Legend snapshot when starting state is snapshot.
Move bookmark group visibility trick logic to LayerRecord, so it will be applied to RCS layers as well.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1139)
> Fix bookmark visibility and snapshot

- src/index-fgp-en.html
- src/index-fgp-fr.html
Prevents both the initial page load code and back-to-cart page load code from running when the back-to-cart demo is triggered. 
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1143)
> Separate startup paths for fpg demo

- src/content/styles/layout/_main.scss
Before: flex box is squashed in IE11
After: add css flex attribute to .md-toast-content CSS class and test
for Chrome, Firefox and IE11
Closes #604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1178)
> IE11 toast error

- src/content/styles/vendor/_special.scss
Before: in IE11, vertical scrolling bar overlap content when the viewer
is in full screen mode
After: add -ms-overflow-style attribute (set to scrollbar) in body css
class
The content and the vertical scrollbar are now aside each other
Closes #1132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1182)
> fix(ui): avoid IE11 scrollbar to overlap content in Full Screen Mode

- src/app/core/bookmark.service.js
When switching basemap schemas, set the config initial extent instead of using center-and-zoom
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1170)
> Set extent on schema change

- src/app/layout/focus.service.js
Fixes an issue where the focus management waiting dialog remains on the page
in standalone maps and can crash the browser.
This fix also improves the focus manager with better event
timing and detection.
Closes #1111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1167)
> fix(ui): focus manager fixes and improvements

- src/app/ui/common/full-screen.service.js
- src/content/styles/vendor/_special.scss
prevents screen reader from reading underlying content
Closes #1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1179)
> feat(ui): hide host page in full-screen mode

- src/app/layout/focus.service.js
- src/index-one.html
Clicking inside the viewer with a mouse completely disables focus
management until focus leaves the viewer.
Closes #1192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1199)
> fix(ui): focus manager correctly responds to mouse activity

- src/app/layout/focus.service.js
Currently $mdDialog does not support multiple dialogs at one time. Updated
focus manager to only close dialogs in WAITING state.
See [this angular material
issue](https://github.com/angular/material/issues/8630) for upcoming support
Closes #1215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1221)
> fix(ui): angular material dialogs no longer close unexpectedly

- src/content/styles/modules/_basemap.scss
Check mark is now visible - basemap title overflow is hidden. Also
corrected separation between title and body text, as well as body spacing
Closes #1209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1227)
> fix(ui): basemap display/css corrections

- src/app/geo/legend.service.js
- src/app/ui/export/export-legend.service.js
- src/content/styles/modules/_export.scss
fixed:
- breaking on missing labels
- breaking on broken layers
- included hidden and "removed" layers
- long layer names without spaces cannot be wrapped fixed here: https://github.com/fgpv-vpgf/svg.textflow.js/commit/d10e14c130614b0240320ce61cbd46490fdbf892
Relates #1176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1256)
> feat(ui): legend export enhancements

- src/app/geo/geo-search.service.js
- src/app/geo/map.service.js
- src/config.en-CA.json
- src/config.fr-CA.json
- src/schema.json
This service will support a geosearch directive. Allows searching by FSA,
NTS, LAT/LNG, and by location names.
Closes #1162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1180)
> feat(ui): create geosearch service

- src/app/geo/layer-registry.service.js
Before: layer extent is not defined for loaded file (CSV,
GeoJSON,Shapefile) so the bbox cannot be displayed
After: add bbox/layer extent calculations when file is loaded. Bbox can
now be displayed. Test with CSV, GeoJSON and Shapefile in both
projections type
Closes #791
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1282)
> feat(geo): add bbox/layer extent calculations at file loading

- src/app/geo/layer-registry.service.js
- src/app/ui/details/layer-list-slider.html
- src/content/styles/modules/_details.scss
Closes #1125 
Also adds an undefined check for `fullExtent` on layer objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1288)
> fix(ui): correct size of the loading spinner in details panel

- src/app/geo/layer-registry.service.js
since it can be null as well as undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1295)
> fix(geo): check if fullExtent is truthy

- src/app/geo/layer-blueprint.class.js
Before: clicking on a feature coming from a user added service give no
result because the featureInfoMimeType is no defined at
identifyOgcWmsLayer call
After: get the available info_format values from the Capabilities XML
and pick the first one supported by the viewer
Closes #1010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1300)
> fix(geo): define featureInfoMimeType in legendEntry for user added service

- src/app/ui/export/export.service.js
Stale print jobs might override the current export image in some cases.
Eyeball testing has been performed. No unit tests.
Added comments in the code.
Stale print requests might override the current export image.
Closes #1285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1336)
> fix(ui): cancel stale print jobs when exporting map image

- devdeploy.sh
- gulpfile.js
Modifies the deployment script to publish both dev and prod build to cloud. Dev build is much easier to test. Also renames samples archives to make clear they contain dev builds.
No unit tests necessary.
Nothing added.
Closes #1302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1335)
> chore(build): deploy dev and prod demo builds to cloud

- src/app/ui/export/export.html
- src/app/ui/export/export.service.js
- src/content/styles/layout/_main.scss
- src/content/styles/modules/_export.scss
- src/locales/translations.csv
If the export map canvas is tainted, instructs the user via the error toast message that the image can be saved manually in some browsers.
Cannot unit test DOM elements with Karma. Protractor is broken.
Code comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1351)
> 1281 manually saving tainted canvas

- src/app/ui/basemap/basemap.service.js
- src/locales/translations.csv
Projection name is now derived from translations, and if no translation is
found outputs a default "other" name. 
Closes #1190
Eyeball tested on FF, IE, and chrome given valid and invalid wkID's including language switching.
jsdoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1354)
> feat(ui): remove hardcoded WKIDs in basemap service

- src/locales/translations.csv
1- Standardize the the use of "Get Link" expression (French: Obtenir le lien)
2- Change the expression "Transparence" for "Opacité" in the French UI
Closes #1270, #1366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1369)
> fix(locales): miscellaneous modifications to translation.csv

- src/app/app.module.js
- src/app/bootstrap.js
Disables angular material ripple effect and debugging information in IE to improve performance. See [this issue](https://github.com/angular/material/issues/8329#issuecomment-216816971) for some discussion on improving AM responsiveness.
I also tried disabling animations/transitions globally in IE, however this breaks map panning and the mini map toggle button. There was no noticeable improvement with global animations/transitions turned off.
Looking into this issue further, it seems IE 11 has a difficult/slow time with element CSS selectors. They should be avoided in favor of CSS classes. AM 1 is all element selectors, AM 2 is moving to classes. I suspect datatables is slow atm in part due to the potential for thousands of element CSS selectors such as md-icon. 
Closes #1274
Eyeball …
> feat(ui): disable animations in IE

- src/app/core/constant.service.js
Angular services (value and constant services) and not initialized with something like `Object.create` and remain shared between app instances.
Relates #1363 
Eyeball testing. Cannot be tested with Karma; needs Protractor tests.
Source comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1364)
> fix(core): stop appInfo service from being shared

- src/app/focus-manager.js
- src/app/ui/sidenav/sidenav.html
Fixes issue where added `div` element in `md-sidenav` broke css styling. Removed the div, instead focus manager will not target `md-sidenav` even if `tabindex` is set.
:eyes: 
None needed
Closes #1383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1398)
> fix(ui): sidenav styles are no longer broken

- src/app/focus-manager.js
- Only occurs with Chrome (FF, IE are OK) when clicking on the map. Using the close button or pressing escape does not cause issue.
- The cause seems to be focus related, but it's not immediately clear why this fix works. 
Closes #1376
Tested in Chrome, FF, and IE
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1395)
> feat(ui): viewer displacement after projection change corrected

- src/app/ui/filters/filters-default.directive.js
Omits blank `symbol` column from grid CSV export.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1394
Small fix, no existing unit tests for datagrids.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1408)
> Exclude symbol column in grid CSV

- src/config.en-CA.json
- src/config.fr-CA.json
- src/config.rcs.en-CA.json
- src/config.rcs.fr-CA.json
- src/schema.json
Adds export options to the config schema. All export components (map, title, legend, map elements (north arrow and scalebar), footnote and timestamp) will be configurable through the config including:
- allowing the user to select if a component should be included in the output graphic
- displaying the component graphic in the export dialog (as a preview)
- including the component graphic in the resulting image
NOTE: This breaks the current footnote implementation. 
Schema validates.
Comments included.
In support of #1258;
Relates #1258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1436)
> feat(core): update schema with export options

- bower.json
- src/app/ui/export/export-legend.service.js
- src/app/ui/export/export.html
- src/app/ui/export/export.service.js
- src/content/styles/modules/_export.scss
Updates geoApi dependency version number.
Fixes a bug when a single-column export legend cannot be generated.
Repositioned the export title input field when the ap compoennt is hidden.
Eyeballing.
Source comments.
Relates #1439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1450)
> 1258 export size finale

- src/app/ui/filters/filters-default.directive.js
- src/content/styles/common/_breakpoints.scss
- src/content/styles/layout/_main.scss
When clicking on zoom to feature in small/medium sized viewports the data table is made almost transparent so that the changes to the map are visible. Clicking anywhere restores the data table.
:eyes: chrome 
jsdoc
Closes #1344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1402)
> feat(ui): enhance zoom to feature on small/medium viewports

- src/app/geo/geo.constant.service.js
- src/app/ui/toc/templates/layer-entry.html
- src/app/ui/toc/toc.service.js
- src/locales/translations.csv
Adds an option to layer dropdown menu to open the datatable. I have not been able to identify why the datatable icon fails to show, since the icon is defined in `toc.service.js` and is added in `layer-entry.html`. Most likely the flag is not being activated for layers with data. The icon was displayed in `v0.7.0`, and my guess is that the flag activating logic was removed sometime after this. Input would be appreciated.
:eyes: 
None
Closes #1429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1455)
> feat(ui): add option to layer dropdown for datatable

- src/app/ui/common/dragula.directive.js
Adds a one second delay to dragula start which is canceled if there is vertical movement of more than 10 pixels. 
:eyes: on IE, FF, and chrome. Does not change IE functionality. 
jsdoc
Closes #1343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1410)
> fix(ui): scrolling now possible in legend for touch devices

- bower.json
Bump geoApi dependency version to use fix for #1463.
Eyeballing.
Not required.
Closes #1463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1464)
> chore(build): update geoApi to 1.1.0-6

- src/app/ui/details/details.directive.js
The point information panel should not be closed by clicking on its icon in the appbar. See here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1431 and here https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1399 for more information.
Eyeballing.
Not needed.
The point information panel can only be closed by the close button located
inside the panel itself.
Closes #1399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1466)
> fix(ui): point info panel toggles not closes

- src/app/ui/sidenav/sidenav.service.js
Share dialog would not open as 'ngInject' was missing.
Eyeballing.
Not needed.
Restored missing 'ngInject' from the share controller.
Closes #1478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1479)
> fix(ui): share dialog opens

- src/app/ui/toc/entry-symbology.directive.js
- src/app/ui/toc/entry-symbology.directive.spec.js
- src/app/ui/toc/templates/layer-entry.html
- src/app/ui/toc/toc.service.js
- src/locales/translations.csv
- src/schema.json
When hovering over a layer, the symbology stack is fanned out. Also added
an option in the layer menu to 'Show Legend'.
Closes #1425
:eye: 
None needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1489)
> feat(ui): Layer symbology stack improvements

- src/app/ui/appbar/appbar.html
- src/locales/translations.csv
👀 
None needed
Closes #1426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1498)
> feat(ui): change tooltip labels

- src/app/ui/details/detail.service.js
- src/app/ui/details/details-content.html
- src/app/ui/details/details-expand.html
- src/app/ui/details/details-header.directive.js
- src/app/ui/details/details-header.html
- src/app/ui/details/details-modal.html
- src/app/ui/details/details.directive.js
- src/app/ui/details/details.html
- src/app/ui/panels/content-pane.directive.js
- src/app/ui/panels/content-pane.html
- src/content/styles/modules/_content-pane.scss
- src/content/styles/modules/_details.scss
Close and expand button in the details panel are added to the fixed header that doesn't scroll with the rest of the content. User found that it's hard to see the floating header.
Eyeballing.
Source comments.
Closes #1431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1499)
> 1431 info panel close modifications

- schemas/fgpv_schema_v1_4.json
- src/app/ui/appbar/appbar.html
- src/app/ui/mapnav/mapnav.service.js
- src/config.en-CA.json
- src/config.fr-CA.json
Mapnav cluster buttons now configured by the config file (default English config has geoLocation, home and help; default French has geoLocation, home, help, basemap, history, and marquee buttons).
Eyeballing.
Source code comments.
Closes #1481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1503)
> feat(core): use config for mannav cluster

- src/app/focus-manager.js
Fixed issues with focus related to dropdown menus. Also reduced focus
recovery time from 800ms to 200ms since basemap selector moved to left
side which when on the right was the original cause for the focus recovery time increase.
Closes #1469
👀 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1500)
> feat(ui): focus lost or changed on layer dropdown

- src/app/layout/shell.directive.js
- src/app/ui/common/full-screen.service.js
- src/app/ui/sidenav/menulink.html
- src/content/styles/modules/_app-menu.scss
:eyes: 
None needed; minor changes
Closes #1424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1504)
> feat(ui): add left sided menu alt navigation paths

- src/config-all.en.json
- src/config-demo.json
- src/config.fr-CA.json
- src/config.rcs.en-CA.json
- src/config.rcs.fr-CA.json
Remove unused buttons from the mapnav cluster (basemap selector, history, and marquee).
Nope.
None needed.
Closes #1517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1518)
> fix(ui): remove unsused buttons from the mapnav

- src/app/ui/loader/loader-file.html
- src/app/ui/loader/loader-service.html
- src/locales/translations.csv
Added short paragraph over Continue button to let users know application may become unresponsive for a short amount of time.
:eyes: 
None needed
Closes #1428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1511)
> feat(ui): feedback provided for add layer unresponsiveness

- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-file.html
- src/app/ui/loader/loader-menu.directive.js
- src/app/ui/loader/loader-menu.html
- src/app/ui/loader/loader-service.directive.js
- src/app/ui/loader/loader-service.html
- src/content/styles/modules/_content-pane.scss
Set focus to close button on open. Set focus to add button on close (bug for Firefox and Safari on Mac)
Close #1374
Issues #1374. Added auto focus on close because of a bug with Firefox and Safari on a Mac. When closed, the focus doesn't go to add button.
Chrome, Firefox and Safari
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1535)
> fix(loader): auto focus on open and close

- src/app/ui/export/export.html
- src/locales/translations.csv
Closes #1471
A lot of :eye: balling
Inline where needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1529)
> feat(ui): updates to export dialog UI

- src/app/bootstrap.js
- src/app/ui/export/export.service.js
- src/locales/translations.csv
Safari doesn't save the image when exported. It's open in a new tab. To solve this, we catch the save task and show a message on how to save the image like for tainted canvas error (#1398)
Tested in Chrome and Safari IOS to make it behave as before. Test in Safari OSX to see the message
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1534)
> fix(export): Safari open a new tab on save

- src/app/ui/help/help.service.js
- src/app/ui/mapnav/mapnav-button.html
Fixes the bug preventing the help dialog from opening in Firefox.
Eyeballing.
Closes #1508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1549)
> fix(ui): help dialog properly opens in Firefox

- src/app/layout/shell.html
- src/app/ui/common/stepper/stepper-item.html
- src/app/ui/export/export-size.class.js
- src/app/ui/export/export-sizes.service.js
- src/app/ui/export/export.html
- src/app/ui/panels/content-pane.html
- src/app/ui/toc/toc.html
- src/content/styles/modules/_content-pane.scss
- src/content/styles/modules/_export.scss
- src/content/styles/modules/_progress-indicator.scss
- src/content/styles/modules/_shell.scss
- src/content/styles/modules/_toc.scss
Fixes a condition when a browser locks up trying to apply an invalid export size. If the selected export size is invalid when the export dialog is opened, the export size resets to a default size.
Eyeballing and lots of page reloading.
Closes #1532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1547)
> 1532 export locks browser

- src/app/ui/filters/filters-default.directive.js
Field names with periods no longer destroy the datagrid.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1530
Tested using modified geoJson file, and service `http://section917.cloudapp.net/arcgis/rest/services/JOSM/JOSM2_en/MapServer/0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1552)
> Periods in field names

- bower.json
- src/app/geo/legend-entry.service.js
- src/app/geo/legend.service.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1487 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1525
Unit tests should be added after move to geoApi and general legend refactor.
Tested against these two layers
`http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_crop_spatial_density_barley/MapServer/`
`http://www.agr.gc.ca/atlas/rest/services/imageservices/landuse_2010/ImageServer`
Function header docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1551)
> Legends for image and raster layers

- src/locales/translations.csv
Changes labels from "Expand/Collapse All" to "Expand/Collapse Groups".
If you know French, can you check if Google's translation is okay? Thanks.
I just hope it works.
Closes #1509
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1562)
> fix(content): change expand menu labels

- bower.json
- src/app/common/formatters.filter.js
- src/app/ui/details/details-content.html
- src/app/ui/details/details-record-esrifeature.directive.js
- src/app/ui/toc/entry-symbology.directive.js
- src/content/styles/modules/_details.scss
Adds url and email autolinking in the details panel. Not possible at the moment in the datagrid. See issue comment for details.
Related #1564
Eyeballing with this layer: http://section917.cloudapp.net/arcgis/rest/services/JOSM_SSB/JOSM_SSB_en/MapServer/1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1572)
> feat(ui): add autolinking to details panel

- src/content/styles/modules/_app-menu.scss
- src/content/styles/modules/_help.scss
Removes the clear button rendered by IE from the help search box.
Fixes crushed side menu on `fgp-*` page.
Closes #1520, #1578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1579)
> 1520 ie draws clear buttons

- src/content/styles/modules/_filters.scss
Scroll area width set to 100% to prevent custom width being applied
Closes #1576
:eye: chrome, ie
none needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1581)
> fix(ui): datatable scrollbars restored

- src/app/geo/overview-toggle.directive.js
- src/app/layout/animation.service.js
- src/app/ui/basemap/basemap-item.directive.js
- src/app/ui/common/full-screen.service.js
- src/app/ui/common/morph.directive.js
- src/app/ui/common/morph.directive.spec.js
- src/app/ui/common/plug-slide.animation.js
- src/app/ui/common/toggle-slide.animation.js
- src/app/ui/details/layer-list-slider.directive.js
- src/app/ui/toc/entry-symbology.directive.js
- src/app/ui/toc/entry.directive.spec.js
- src/app/ui/toc/toc.directive.js
- Disabled all GSAP animations for IE, and most for touch devices (when `$rootElement` was available)
- Does not remove GSAP animation, but rather immediately moves the timeline to completion 
Closes #1465
:eye: balling in IE & chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1556)
> feat(ui): disable GSAP-based animations for IE and touch enabled devices

- src/content/styles/modules/_app-menu.scss
Removes extra scrollbars from the sidemenu in IE; see issue for details.
Closes #1578
Eyeballing.
Nope.
- ~[ ] release notes have been updated~ not needed as the bug was not released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1585)
> fix(ui): remove side menu scrollbars in IE

- src/content/styles/modules/_filters.scss
Closes #1404
Content panel doesn't update height properly in Safari from maximize to split view for filters (related to #1404).
Visual in Chrome, FF and Safari
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1558)
> fix(filters): display filters between maximize and split view in Safari

- src/app/focus-manager.js
- src/app/ui/filters/filters-default.html
Any child of an element with the rv-ignore-focusout property is ignored
when it loses focus, and the next tab press is handled by the browser.
Closes #1557
:eye: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1580)
> fix(ui): added rv-ignore-focusout to focus manager

- src/app/ui/export/export-generators.service.js
- src/app/ui/export/export.html
- src/app/ui/export/export.service.js
Solves #1563, a problem with scalebar width when image is rezise and scroll to custom size section on selection
Inlline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1624)
> fix(export): issues with export

- src/content/styles/modules/_details.scss
IE has many interesting bugs... In this case, a flexbox didn't want to vertically center it's content, unless you set it's height to a concrete number or wrap it in another flexbox.
Closes #1646
Eyeballing.
Inline.
- ~~[ ] release notes have been updated~~ not a relased bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1647)
> fix(ui): center details panel header in IE

- src/content/styles/modules/_details.scss
Truncate overflowing details values that cannot be wrapped.
Closes #1635
http://fgpv.cloudapp.net/demo/users/AleksueiR/1635-truncate-autolinks/prod/samples/index-fgp-en.html?keys=JOSM
Eyeballing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1645)
> fix(ui): truncate overflowing details values

- src/app/geo/identify.service.js
- src/app/geo/legend-entry.service.js
- src/app/ui/toc/entry-flag.directive.js
- src/app/ui/toc/entry-flag.directive.spec.js
- src/app/ui/toc/templates/layer-entry.html
- src/config.en-CA.json
config file option.data was not properly read from the config file.
index-one.html
With feature layer Land Pub Standard Zone Details ("data": { "enabled": false })
With dynamic layer Eco Geo first layer ({"index": 6, "data": {"enabled": false}})
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1652)
> fix(filters): option data not read from config file

- src/app/ui/details/details-record-esrifeature.directive.js
- src/content/styles/modules/_details.scss
Prevents unbreakable key names and values from overflowing and causing scrollbars to appear. See the issue for more details. Fix is done by switching from floating elements to the flexbox.
Closes #1659
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1660)
> fix(ui): details scrollbars for good

- src/app/ui/details/details-record-esrifeature.directive.js
- src/content/styles/modules/_details.scss
Filters out `rvInteractive` column from the details view.
Simplifies the template and fixes a small bug when the key value might not
be flush with the right edge of the container.
Closes #1661
Eyeballing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1673)
> fix(ui): filter rvInteractive column from details

- src/app/ui/details/details-record-esrifeature.directive.js
Autolinked html snippets were incorrectly bound to the details panel and displayed as plain text.
Relates #1661
Eyeballs.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1680)
> fix(ui): properly bind autolinked html snippets

- src/app/geo/geo-search.service.js
- src/app/ui/geosearch/geosearch-bar.html
- src/app/ui/geosearch/geosearch.html
- src/app/ui/geosearch/geosearch.service.js
- src/app/ui/help/help.service.js
- src/config.rcs.fr-CA.json
- src/locales/translations.csv
Closes #1616
Add FSA, NTS, scale and coordinates search. Relates to #1616
Chrome, FF and Safari. For FF, there is a problem with result panel height (#1668)
For FSA, only the first 3 characters are allowed (A1A = ok; A1A1 = no)
For NTS,  need 3 numbers, letter between a-p then number between 01 to 16
For scale, need to start with 1: followed by number or spaces (1:100000 = ok, 1:100 000 = ok)
For coord in decimal degree (lat, long): [+-](nothing = +) 0 to 90 [space , or ;] [+-](nothing = +) 0 to 180
For coord in degree, minute, second (lat, long): [+-](nothing = +) 0 to 90 [space] 0 to 60 [space] 0 to 60 [, or ;]  [+-](nothing = +) 0 to 180 [space] 0 to 60 [space] 0 to 60
Inline
--- …
> feat(geosearch): add FSA, NTS, Scale and coordinates search to geosearch

- src/app/layout/layout.service.js
- src/app/ui/geosearch/geosearch.directive.js
- src/app/ui/panels/panel.directive.js
- src/app/ui/tooltip/tooltip.directive.js
- src/content/styles/modules/_geosearch.scss
Adds a size change listener to the main panel and updates the `max-height` attribute on the geosearch content node to have it size up correctly in IE (other browser behaviour is fixed by CSS only). This might seems as an overkill for an IE bug, but we probably can use `onResize` in other places, like tooltip (it has a similar logic for watching tooltip dimension changes).
Please, check the demo in IE and Firefox to make sure it's working correctly for you.
Closes #1668
IEballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1687)
> fix(ui): fix geosearch resutls overflow

- bower.json
- gulp.config.js
- src/app/bootstrap.js
- src/index-mobile.html
Only load Angular if not present on the host page; output console warning
if the angular version does not match expected version.
If Angular is loaded by the host page before jQuery (or jQuery is not loaded at all), output console error and stop viewer initialization as jQuery must be loaded before Angular for it to bind correctly.
Removed not-needed "include-media" dependency. Updated datatable dependencies to `1.10.11` as specified in bootstrap.
Closes #960
Eyeballs.
Some inline comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1694)
> fix(bootstrap): check for angular loaded by host

- src/app/ui/details/layer-list-slider.html
Closes #984
Present layers with data above those without while maintaining ordering within these groups.
:eye: 
None yet as 1.6 branch is missing jsDocs tutorial implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1696)
> fix(ui): prioritize layers with data in slider

- gulpfile.js
- package.json
- src/app/app.module.js
Closes #1692
Removes most console logs on prod builds. To keep a log message simply append `/*RemoveLogging:skip*/`. For example:
```js
console.log('This message will be logged'); /*RemoveLogging:skip*/
```
Cannot unilaterally remove logging for libraries and bower files since it breaks them in some cases. 
:eye: 
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1699)
> chore(build): clean up console logs on prod builds

- src/app/ui/filters/filters-default-menu.directive.js
- src/app/ui/filters/filters-default-menu.html
remove split/max options in datatable for sm/md layouts
Closes #1678 
:eye: 
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1705)
> fix(ui): remove split/max options in datatable for sm/md layouts

- src/app/ui/filters/filters-default.directive.js
See #1683 
The problem was Datatables use rendererto export data. Setting orthogonal = null in the option solve the problem. Now Datatable use the real data for export and print.
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1710)
> fix(filter): duplicate values when export

- src/content/styles/modules/_export.scss
Minor changes to CSS affecting only small viewports. 
Closes #1474
Tested on iPhone and chrome mobile emulation.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1726)
> fix(ui): Improve export header for small viewports

- src/content/styles/common/_all.scss
App's top level selectors (`fgpv` class and `is="rv-map"`) were treated as a single selector breaking any map using `fgpv` class instead of `is="rv-map"`.
Closes #1737
Eyeballs.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1738)
> fix(ui): use append-selector to avoid squashing

- src/app/ui/details/details-modal.html
- src/app/ui/export/export.html
- src/app/ui/help/help-summary.html
- src/app/ui/metadata/metadata-modal.html
- src/app/ui/sidenav/share-dialog.html
AM only supports the opening animation for dialogs without ng-cloak.
There is no plan on changing this.
Closing #1312
:eyes: 
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1742)
> fix(ui): restored dialog opening animation

- bower.json
Angular material is using "angular-messages": "^1.4.8" which pulls 1.6.x
of the angular messages which breaking the build. Pin `angular-messages` and `angular-mocks`. Thank you.
Yeah!
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1747)
> fix(core): pin angular messages dependency

- gulpfile.js
The `samples` task was not waiting properly on the `remove-apikey` task completion as it wasn't returning a promise.
@alyec maybe this was the problem with one of the config files in the samples archive being completely empty.
Made local sample builds.
Not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1746)
> fix(build): remove-apikey didn't execute async

- src/app/ui/filters/filters-default.directive.js
- src/app/ui/filters/filters-search-directive.js
- src/app/ui/filters/filters.service.js
Related to #1619
Use GitHub search syntax to search datatable for complex query. We can still only put text and datatable will try to find the value everywhere inside the table. To have a more specific search, user can search by field. All field:value pairs are cumulative and treated as AND query.
user can filter a string field who contain number as a numeric field. Some field seems to be date but they are not (e.g. 2/23/2208). Trying to filter those field by date will give bad results
All field:value pairs is separated by a space
string - fieldName:value e.g. tc_id:myvalue
e.g. tc_id:"this is my value" (if spaces in the query enclose text in "")
e.g. tc_id:valueA|valueB (pipe character | is used to say OR)
number fieldName: (select operand <=, <, >=, >, []
e.g. …
> feat(filter): add complex query for global search

- gulpfile.js
- package.json
- src/app/bootstrap.js
All console output is removed in production builds. To force a console
output in production use RV.logManager.* (where * can be any console
method such as log, warn or error).
Closes #1702
`index-mobile.html` shows warnings on prod build
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1763)
> fix(log): removed console output in production

- docs/developer/technical/focus_manager.md
- gulp.config.js
- src/app/bootstrap.js
- src/app/focus-manager.js
- src/app/geo/overview-toggle.directive.js
- src/app/ui/basemap/basemap.service.js
- src/app/ui/common/dialog.decorator.js
- src/app/ui/common/dragula.directive.js
- src/app/ui/common/menu.decorator.js
- src/app/ui/common/select.decorator.js
- src/app/ui/common/stepper/stepper.class.js
- src/app/ui/export/custom-size.directive.js
- src/app/ui/export/custom-size.html
- src/app/ui/export/export.html
- src/app/ui/filters/filters-default.directive.js
- src/app/ui/geosearch/geosearch-bar.directive.js
- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-menu.directive.js
- src/app/ui/loader/loader-service.directive.js
- src/app/ui/panels/content-pane.html
- src/app/ui/sidenav/sidenav.service.js
- src/app/ui/toc/templates/entry-flag.html
- Removed requirement for calling init(), now initialized before
app-seed but after jQuery (required)
- Added new HTML and jQuery element prototype rvFocus() which replaces focus(true) when
setting focus on viewer elements. They are now exclusive and will raise
a warning when used incorrectly.
- Added attribute rv-focus-init which allows the use of focus() on a
viewer element or one of its children if focus is outside the element
- Added jQuery element prototype nextFocus() which moves focus to the
next element
- Documentation added
Closes #1623, #1373
Yes, quite a bit
Of course!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1741)
> feat(focus): Add arrow support for md-menu and other improvements

- bower.json
- src/app/geo/legend.service.js
Adds viewer support for tile based layers. 
geoApi PR https://github.com/fgpv-vpgf/geoApi/pull/185 must be merged first.
No, depends on pending geoApi code 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1767)
> feat(legend): Add support for tile based layers

- docs/developer/technical/focus_manager.md
- src/app/focus-manager.js
- src/app/ui/common/select-menu.decorator.js
Introduced new FM attribute rv-focus-memeber which indicates element and
its children are a part of the viewer but does not assume focus
responsibilities.
Closes #1771, #1772
Yes
Docs, jsDocs, inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1773)
> fix(focus): md-select actions no longer deactivate FM

- docs/developer/technical/focus_manager.md
- src/app/focus-manager.js
- src/app/ui/geosearch/geosearch-bar.html
Introduces new attribute rv-focus-exempt for an element and its children to gain focus via the normal .focus() implementation. Differs from rv-focus-init where focus can only move onto the element or its children from outside (and further focus attempts are rejected)
Closes #1770
Yes
inline, docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1802)
> fix(focus): allow focus to move into input on search selection

- src/app/ui/common/svg.directive.js
Closes #1671, #1642
Chrome and Safari
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1780)
> fix(symbol): Safari doesn't render svg

- bower.json
- src/app/common/formatters.filter.js
- src/app/ui/filters/filters-default.directive.js
- src/content/styles/modules/_details.scss
- src/content/styles/modules/_filters.scss
Be able to show details key-pair with html tag inside details panel. At the same time show html tag and links inside the filters panel.
Note: There is a problem with rvFocus from focus manager. When testing, the focus can be lost. I will create a new issue.
Chrome, FF and Safari with a layer internal to NRCan for html tag and http://geoappext.nrcan.gc.ca/arcgis/rest/services/MMS/IMA_E/MapServer/0 for the links
image sample
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1815)
> fix(details): be able to show details key-pair with html tag

- src/app/ui/common/menuItem.decorator.js
- src/app/ui/filters/filters-default-menu.html
- src/content/styles/vendor/_special.scss
Closes #1743
Set filters menu the same layout as other menu (icon / text / checkbox)
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1819)
> fix(filter): set filter menu layout the same as side nav layout

- src/app/bootstrap.js
Prevents loading order conflicts by first initializing RV.logger as
console then later switching it to logger library when ready
Yes
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1849)
> fix(bug): RV.logger is now initialized as console

- bower.json
- src/app/geo/overview-toggle.directive.js
- src/app/layout/shell.html
- src/app/ui/appbar/appbar.html
- src/app/ui/basemap/basemap-item.html
- src/app/ui/details/details-header.html
- src/app/ui/export/export.html
- src/app/ui/filters/filters-default-menu.html
- src/app/ui/geosearch/geosearch-bar.html
- src/app/ui/geosearch/geosearch-bottom-filters.html
- src/app/ui/geosearch/geosearch-top-filters.html
- src/app/ui/help/help-search.html
- src/app/ui/loader/loader-menu.html
- src/app/ui/panels/content-pane.html
- src/app/ui/settings/settings.html
- src/app/ui/toc/templates/expand-menu.html
- src/app/ui/toc/templates/visibility-menu.html
- src/app/ui/toc/toc.html
- issue was resolved by removing `translate` along with `translate-attr-aria-label` and changing to manual translations. 
Closes #1839
:eyes: 
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1848)
> fix(bug): missing icons have been restored

- src/app/ui/basemap/basemap-item.html
es6 string substitution doesn't work in templates;
Closes #1860
Not needed.
- ~[ ] release notes have been updated~ unreleased bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1861)
> fix(ui): es6 strings don't work in templates

- src/app/common/graphics.service.js
- src/app/ui/common/svg.directive.js
- src/app/ui/toc/entry-control.directive.spec.js
- src/app/ui/toc/entry-flag.directive.spec.js
- src/app/ui/toc/entry.directive.spec.js
- src/app/ui/toc/toc.service.js
Closes #1671
The problem append again because now safari use NS1:href not just href
Safari and Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1854)
> fix(legend): safari svg symbol doesn't render

- src/app/bootstrap.js
#1842 
From the answer given by datatables developer, we need to migrate to version 1.10.15
Chrome, Safari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1851)
> fix(filter): keytable extension slow with huge table

- src/app/ui/filters/filters-default.directive.js
- src/app/ui/filters/filters-default.html
- src/content/styles/modules/_filters.scss
#1825, #1816 
Tried to optimize when user scroll continuously with the keyboard by debouncing the focus. Can only do it when there is no redraw because redraw mess up the scroller info when scroll with the keyboard and keytable extension.
Tried to make it faster by excluding all the focus when scrolling with the keyboard and only focus when it is finish but always have problems with shifting focus.
Hope enough
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1841)
> fix(filter): focus with keytable extension

- src/app/core/config.class.js
- src/app/geo/layer-registry.service.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/ui/tooltip/tooltip.service.js
- move hovertip template to tootlip service as the default template
- prevent controlled layers from being queried (even if specified in the config)
- prevent controlled layers from having enabled bounding boxes (even if specified in the config)
- prevent controlled layers from having hovertips
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1895)
> Moving hovertip template

- package.json
- src/app/app-loader.js
- src/app/ui/filters/filters-default.directive.js
- src/content/styles/modules/_filters.scss
Closes #1896
There is a lot of bugs between Keytable and Scroller extention and Focus manager.  Build our own keyboard navigation will solve this.
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1898)
> fix(filter): replace Keytable by our own keyboard navigation

- src/content/samples/blank.tpl
- webpack.common.js
- webpack.config.js
- webpack.dev.js
Replaces geoApi from node_modules with a local copy on disk. Works with
live reload.
Source maps no longer generate for develop automatically (faster builds). Use env.useMap
to enable.
Must merge geoApi PR #217 first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1916)
> chore(build): added env.geoLocal

- src/app/core/bookmark.service.js
- src/app/core/config.class.js
- src/app/core/reload.service.js
- src/app/geo/geo.service.js
- src/app/geo/layer-blueprint.class.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/geo/map.service.js
- src/app/ui/basemap/basemap.directive.js
- src/app/ui/sidenav/sidenav.service.js
- src/app/ui/toc/templates/expand-menu.directive.js
- src/app/ui/toc/templates/visibility-menu.directive.js
- src/content/samples/index-mobile.tpl
When switching to a basemap with a different projection, it actually works, and layers settings are remembered correctly. Bookmark V2 is used.
Some work is done towards full state restore.
At this point, projection change can be done without a bookmark.
Some eyeballing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1931)
> Restore switching to basemaps with different proejctions

- src/content/styles/vendor/_special.scss
fixes #1749 
Make the tool tip wrap instead of being cut off when it exceeds the length of small screen
No, because it is an UI issue.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1937)
> Make the tool tip readable when it exceeds the length of small screen

- src/content/styles/vendor/_esri.scss
Closes #1925 
Hide the default esri zoom commands previously shown in the top left
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1941)
> fix(layout): hide esri default zoom options

- src/app/ui/loader/loader-file.directive.js
Closes #1924 
Fixes closing import file menu prior to uploading a file
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1939)
> fix(loader): issue closing import file menu

- src/app/ui/loader/loader-file.directive.js
Closes #1926 and #1927 
Reset progress bar on cancellation of step 2
Allows for drag and drop after cancellation of step 2
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1945)
> Fix upload progress bar and drag / drop functionality

- src/app/geo/overview-toggle.directive.js
fixes #1943, the collapse button should appear when first loaded now.
No, it was a UI bug.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1946)
> fix not init collapse mini map

- src/app/core/config.class.js
- src/app/geo/init-map.directive.js
- src/content/samples/config-mobile-2.json
- src/content/styles/modules/_shell.scss
- src/content/styles/vendor/_esri.scss
Scale bar is not at the right place after switching basemap. To achieve this it was not easy because there something wrong when the scalebar is on the left side. Application always force it back to the left. I we use bottom-right inside the scalebar init, there is no need for almost 2/3 of the code from this PR.
Chrome, FF
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1872)
> fix(scale): scale wont move after projection switch

- package.json
- src/app/geo/identify.service.js
- src/app/geo/layer-registry.service.js
Tied to this change on geoApi https://github.com/fgpv-vpgf/geoApi/pull/223
Change identify parameter to use map wrapper object
None, thanks
None, thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1971)
> Identify map parameter

- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
Closes #1956.
Removes permanent bounding box on reload of a layer.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1978)
> fix(boundingbox): remove permanent bounding box on reload

- src/content/samples/blank.tpl
- src/content/samples/index-fgp-en.tpl
- src/content/samples/index-fgp-fr.tpl
- src/content/samples/index-mobile.tpl
- webpack.common.js
- webpack.prod.js
Hot reloading not yet supported by sri plugin. Dev serve/builds no
longer use sri checks.
Production serve/builds will fail if hot swapping is enabled.
:eyes: 
nope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/1986)
> chore(build): move sri checks on prod only

- src/app/geo/geo-search.service.js
#2005, fixes geosearch when config -> map -> components -> geoSearch -> enabled is false.
Manually.
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2007)
> Fix geosearch when config -> map -> components -> geoSearch -> enabled is false

- src/app/ui/common/select-header.html
- src/app/ui/loader/loader-service.html
- src/app/ui/ui-loader.js
- src/content/styles/vendor/_special.scss
[See discussion here](https://github.com/angular/material/issues/10342#issuecomment-308568524)
As a workaround, nestle:
```html
<md-select-header>
<md-input-container>
// stuff here . . .
</md-input-container>
<md-select-header>
```
Caused by parent controller scoping, [see material/select.js](https://github.com/angular/material/blob/93c29175c897136463aad248494fccfc4dc080a2/src/components/select/select.js#L277)
Closes #1990
womm
none
--- …
> fix(ui): md-input-container no longer throws multiple input error

- src/app/geo/geo-search.service.js
- src/app/ui/appbar/appbar.directive.js
- src/app/ui/appbar/appbar.html
- src/locales/translations.csv
Disables geoSearch icon and displays tooltip indicating geoSearch is not
available when either province.json or concise.json fail to load
Closes #1976
:eye: 's on chrome
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2035)
> feat(ui): handle external geoSearch api errors gracefully

- src/app/ui/filters/filters-definition.directive.js
Fixes:
* Bug #1998: Datatable not populated for layers with date columns
* Undocumented bug: Datatable not populated after switching layers from layer with date column to other layers
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2031)
> fix(datatable): loading for layers with date columns

- src/app/bootstrap.js
- src/app/core/bookmark.service.js
- src/app/core/core.run.js
- src/app/core/reload.service.js
- src/content/samples/index-samples.tpl
#2029.  Add a bookmark loader to substitute the url bar to avoid complicated and unnecessary implementation for the bookmark to reload when a different config file was swapped.
Manually.
`index-samples.tpl`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2043)
> Add a bookmark loader in the sample page

- src/app/core/core.config.js
Closes #2047.
Fixes datatable record loading for layers with columns containing numbers in title.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2065)
> fix(datatable): loading for numeric columns

- src/app/core/config.class.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/ui/details/details-header.directive.js
- src/app/ui/details/details-header.html
- src/app/ui/details/details.html
- src/app/ui/loader/layer-source.service.js
- fixes a double-tooltiop regression bug #2059 
- allows to reload user-added layers #2056 
- adds a partial fix to #2061 
Closes #2056, #2059 
Eyeballs. Minimal.
- ~~[ ] release notes have been updated~~ unreleased bugs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2066)
> 2059 and friends

- src/app/ui/help/help.service.js
- src/content/styles/vendor/_angularmaterial.scss
- Corrected help regex where ie failed to match valid groups of text.
- CSS update to prevent datatable search field from displacing
Closes #1973, #1876
Yes, in IE and chrome
None needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2069)
> fix(ui): datatable and help section fixes

- src/app/core/config.class.js
- src/app/core/constant.service.js
- src/app/geo/layer-registry.service.js
- src/app/ui/toc/toc.directive.js
Properly opens the datatable by default is specified in the config.
Close #2088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2090)
> fix(ui): open initial datatable specified in the config

- src/app/core/bookmark.service.js
- src/app/core/config.class.js
- src/app/core/config.service.js
- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
- [bug #2092] prevents bookmarking of errored and still loading layers
- [bug #2095] user-added layers were breaking bookmark
- [bug #1983] bookmark preserves user-change layer order (autolegend only)
- [bug #1983] bookmark preserves user-remove layers (autolegend only)
Closes #2092, #2095, #1983
Eyeballs.
- ~~[ ] release notes have been updated~~ unreleased bugs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2094)
> 2092 dont bookmark broken layers

- package.json
- src/app/geo/legend-block.class.js
- src/content/samples/schema.json
Duplicate layers now share control of the bounding box controls. Only
one bounding box is created.
Closes #1977, #2018
:eyes: 
None needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2101)
> fix(ui): filters title schema change and bounding box update

- src/app/geo/legend-block.class.js
- src/app/ui/loader/loader-file.html
- src/app/ui/loader/loader-service.html
- src/app/ui/toc/legend-element-factory.class.js
- src/locales/translations.csv
- [bug #2071] query values now propagate to children when set on the group
- [bug #2104] raster layers no longer display data flags or data controls
- [bug #2107] invalid feature counts (like -1) will not be shown anymore
- [undocumented enhancement] layer import wizard less likely to miss service url value changes
Close #2071, #2104, #2107
Eyeballs.
- ~~[ ] release notes have been updated~~ unreleased bugs
--- …
> Bugfest: 2071, 2104, 2107

- src/app/ui/loader/loader-service.html
- webpack.common.js
Makes the "display as a group" checkbox undefined when no layers are selected as requested by QA:
Eyeballs.
Nope.
- ~~[ ] release notes have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2122)
> fix(ui): make singleentrycollapse checkbox undefined if no layers

- src/content/styles/vendor/_angularmaterial.scss
(Sorry @AleksueiR :smiley_cat: )
Closes #2116
chrome and FF, not ie (filters not displayed bug)
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2118)
> fix(ui): md-select values no longer exceed parent width

- src/app/ui/filters/filters-default.directive.js
Closes #2082.
Column reordering for datatables is now only accessible through the datatable settings panel and not by way of drag-and-drop.
In-line comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2117)
> fix(ui): column reordering only enabled from settings

- src/app/ui/toc/legend-element-factory.class.js
Does not store the legend type (structured or auto) anymore, check at the source.
Closes #2140
Eyeballs.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2143)
> fix(core): check legend type properly

- src/app/core/config.class.js
- src/content/samples/config/config-sample-01-structured-visibility-sets.json
- src/content/samples/config/config-sample-02-structured-legend-controlled-layers.json
- src/content/samples/schema.json
Closes #2048
Hide the help button in both nav bar and side bar when the folder name for it is absent
Tested in `samples-index`
- sample 1: with `ui.help.folderName`
- sample 2: with `ui.help` but not `ui.help.folderName`
- sample 3: `ui.help` is absent
config files for sample 1 and 2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2146)
> Hide help when the corresponding folder name is absent

- package.json
- src/app/ui/loader/layer-source.service.js
- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-file.html
- src/app/ui/loader/loader-service.html
Allows to load files from the network using the Angular $http service instead of the esri loader library.
Loading files from a source without proper CORS settings will fail.
Sample data for testing is here: http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/
Closes #2061
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2156)
> fix(core): allow loading files from network

- src/app/core/config.class.js
- src/app/ui/filters/filters-default.directive.js
Closes #2084 Fix the issue when contents is not loading in the datatable in IE and fix a bug with the `about` entry not being load when `help` is no in the config file.
Manually
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2171)
> Fix the issue when contents is not loading in the datatable in IE

- package.json
- src/app/core/core.run.js
- src/app/core/graphics.service.js
- src/app/geo/geo.service.js
- src/app/geo/init-map.directive.js
- src/app/geo/layer-registry.service.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/ui/common/truncate.directive.js
- src/app/ui/panels/content-pane.directive.js
- src/app/ui/toc/templates/expand-menu.directive.js
- src/app/ui/toc/toc.directive.js
Layer sorting function used a wrong condition that somehow managed to work correctly for a relatively small number of layers, but failed for a larger sample. Now, the map layer order should map layer order in the UI (barring mixing vector and image based layers of course).
To test, check out the branch, `npm install`, grab [this config](http://geoappext.nrcan.gc.ca/fgpv/map/egs/en/config.en-CA.json), and then load it in `index-mobile` page. The `Today's Smoke Forecast` layer should be under the `Active Fires` layer.
Closes #2178 
Please keep the original issue up to date with the final solution, expected behaviour, and …
> fix(core): correctly synchronize map layer stack with config layer order

- src/app/geo/layer-registry.service.js
Ignores non-layer legend blocks (like text and images blocks) when synchronizing layer order.
Relates #2178
Almost none.
- ~~[ ] release notes have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2184)
> fix(core): ignore non-layer legend blocks when synchronizing layer order

- src/app/core/common.service.js
- src/app/core/config.class.js
- src/app/ui/common/full-screen.service.js
- src/app/ui/mapnav/mapnav.service.js
- src/app/ui/sidenav/sidenav.service.js
Safair iOS doesn't not support full-screen; the library fails when invoked somehow causing all md-icons to fail.
Closes #2187
Eyeballs on browserstack.
Nope.
- ~~[ ] release notes have been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2191)
> fix(ui): remove full screen option if not supported

- package.json
- src/app/ui/details/details-record-html.html
WMS results are directly bind into the template.
Test layer: http://geo.weather.gc.ca/geomet/
Expected result:
Test layer: http://maps.geogratis.gc.ca/wms/railway_en
Expected result:
Closes #2196
Eyeballs.
Nope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2197)
> fix(ui): bind wms results as html

- src/app/ui/panels/panel.directive.js
- src/app/ui/table/table-default.directive.js
Closes #2040 Fixes the issues when close button on the data table was clicked twice quickly when the table was still loading
Manually, using all the muscle power I had to click the closing button twice on time
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2195)
> Fixes when close button on the data table was clicked twice quickly

- src/app/core/config.class.js
- src/app/ui/geosearch/geosearch-bar.html
- src/app/ui/geosearch/geosearch.html
- src/content/styles/vendor/_esri.scss
- [bug #2189] Allow mouse events through feature highlights.
- [undocumented enhancement] move geosearch progress bar from the results panel to the search bar itself
Closes #2189 
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2198)
> fix(ui): prevent feature highlight from blocking hovertips

- src/content/styles/vendor/_angularmaterial.scss
Closes #2181 Remove the extra clear button in the filter on the data table.
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2218)
> fix(IE): remove extra clear button in filter

- docs/developer/technical/focus_manager.md
- src/app/focus-manager.js
- src/app/ui/common/dialog.decorator.js
- src/app/ui/sidenav/share-dialog.html
- Calling rvFocus sets the viewer to ACTIVE state.
- New rv-focus attribute now available to children of md-dialog. Focus moves to rv-focus element instead of close button. If needed this attribute can be expanded to other element types in the future as an alternative to manual rvFocus invocations.
Closes #2170, #2186
jsdocs, inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2219)
> fix(focusManager): new attribute and logic changes

- src/app/ui/details/details.directive.js
A watch for the first identify result to be resolved wasn't removed correctly, causing endless errors.
Closes #2225
:beholder:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2227)
> fix(core): remove identify result watchs

- src/app/geo/legend.service.js
Does not remove layer records unless they are no longer references by the legend blocks.
Closes #2233
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2237)
> fix(core): don't remove layers if they are still referenced in legend

- package.json
- src/app/core/config.class.js
- src/app/geo/map.service.js
Related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2182
Wires in geoApi support for custom overview map.
See this commit for the geoApi contents of `v2.1.0-1` https://github.com/james-rae/geoApi/commit/c379c8f6ddabf51039e19e02a0c73b4f7d531f0a
Tested against index-mobile, verified custom map appeared and did not change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2238)
> Custom overview and bugs

- .travis.yml
- src/app/ui/table/table-default.directive.js
- src/app/ui/table/table-definition.directive.js
- src/app/ui/table/table.service.js
Note that `column.type` changed from `date` to `rv-date` as `date` type has built-in sorting (which does not work for our date format)
Closes #2200
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2242)
> fix(datatable): date columns are now sortable

- src/app/core/bookmark.service.js
- src/content/styles/modules/_geosearch.scss
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2226
Ignores dynamic children of layers in non-stable states (loading, error) when generating bookmark.
Also re-adds lost commit `fix(geoSearch): make hovered results readable`
Tested against app by generating bookmarks in various stages of layer-load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2268)
> Bookmark ignores loading children

- schemas/fgpv_schema_v2_0_0.json
- src/app/core/config.class.js
- src/app/geo/legend-block.class.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/legend-info.html
- src/app/ui/toc/templates/legend-node.html
- src/app/ui/toc/templates/symbology-stack.html
- src/content/samples/config-mobile-2.json
- src/content/styles/modules/_symbology.scss
Allows to add an optional description to legend entry blocks and legend info blocks (unbound layers only).
Config schema is updated to 2.1.
Closes #2260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2281)
> feat(ui): add opt description to legend blocks

- src/app/ui/table/table-definition.directive.js
Closes #2257.
Closes undocumented bug: When applying filters, keep the same offset between filters and row values to ensure the correct rows are filtered out.
Visually tested; Chrome, IE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2287)
> fix(table): parsing of dates in non-ISO format

- package.json
- src/app/core/formatters.filter.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2239
Stops detail pane from getting angry if a null appears
Loaded null-riddled layer in viewer. Tested detail view, identify, data grid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2288)
> Handle null in esri detail pane

- src/app/ui/geosearch/geosearch.directive.js
- src/app/ui/geosearch/geosearch.html
Replace geo search result animations when truncated with tool tips
Closes #1877 
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2285)
> Replace geo search result animations with tooptips

- schema.json
- src/app/core/config.class.js
Should now properly parse sidemenu items defintion. `items` is an array of arrays representing sections in a submenu.
```json
items: [
[
"layers",
"basemap"
],
[
"fullscreen",
"export",
"share",
"touch",
"help"
],
[
"language"
]
]
```
Closes #2289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2291)
> fix(ui): side menu items are rendered correctly

- src/app/ui/table/table-default.directive.js
Closes #2271
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2286)
> fix(datatable): column headings position corrected on resize

- package.json
- src/app/geo/legend-block.class.js
- src/app/geo/locate.service.js
- src/app/geo/map.service.js
- src/app/ui/common/error.service.js
- src/app/ui/toc/legend-element-factory.class.js
- src/app/ui/toc/toc.service.js
- src/locales/translations.csv
Detect zoom to boundary events that move the extent center outside the full extent of the basemap and display a toast to the user with an option to adjust the new extent.
Closes #2273
)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2304)
> feat(ui): add toast for bad boundary zooms

- src/app/ui/toc/toc.service.js
- src/content/styles/modules/_table.scss
It seems datatables does not adjust the column width of `rvInteractive` based on the child width as would be expected. It could be using the literal value `rvInteractive` as a basis for the width.
It also seems it does not properly use the column width as defined in
our columnDefs.
These issues made it necessary to resort to manual width adjustments.
Closes #2262
👀 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2298)
> fix(ui): rvInteractive button widths adjusted

- package.json
- src/app/ui/loader/layer-source.service.js
Treat importing files and services differently
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/868 and requires https://github.com/fgpv-vpgf/geoApi/pull/259
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2306)
> Separate importing logic for files and services

- src/app/core/reload.service.js
Closes #1365 and #2136 
Intermediate solution because complete solution requires full state stored. Previously, the panels remained open but were not functional after changing projection. This will close the side or datatable panel if open.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2311)
> fix(ui): close open panels when switching projection

- src/app/layout/layout.service.js
Closes #2266, #2272, #2315 and any other related problems with the layout
There may be a more elegant solution that will solve all these problems. Until we can find that, this will suffice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2319)
> fix(layout): correctly determine layout in IE

- src/app/core/bookmark.service.js
- src/app/core/reload.service.js
- src/app/geo/geo.service.js
- src/app/geo/legend.service.js
Closes #2152 
Changed the inserting position of RCS layers in legends.
Manually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2323)
> Fix RCS layers ordering issue when they were loaded from bookmarks

- src/app/geo/legend.service.js
- src/app/ui/toc/toc.service.js
Closes #2328 and #2329
To test using nested groups, [this](http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer/0) can be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2330)
> fix(panel): close panel when removing layers

- src/app/geo/legend.service.js
- src/app/ui/toc/toc.service.js
Closes #2329
Closes [undocumented bug] - when removing layers, cache visibility of layer and any children, instead of only top level visibility
In-line comments, JSDoc for helper function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2331)
> fix(legend): close panel only when matching layer removed

- src/app/core/plugin.service.js
- src/app/core/statemanager.service.js
- src/app/geo/init-map.directive.js
- src/app/geo/map.service.js
- src/app/layout/layout-loader.js
- src/app/layout/layout.service.js
- src/app/layout/reference.service.js
- src/app/layout/shell.directive.js
- src/app/ui/appbar/appbar.directive.js
- src/app/ui/basemap/basemap.directive.js
- src/app/ui/common/full-screen.service.js
- src/app/ui/details/detail.service.js
- src/app/ui/details/details-record-esrifeature.directive.js
- src/app/ui/export/export-sizes.service.js
- src/app/ui/export/export.service.js
- src/app/ui/geosearch/geosearch.directive.js
- src/app/ui/geosearch/geosearch.service.js
- src/app/ui/help/help.service.js
- src/app/ui/lightbox/lightbox.directive.js
- src/app/ui/metadata/metadata-expand.directive.js
- src/app/ui/metadata/metadata-panel.directive.js
- src/app/ui/panels/panel.directive.js
- src/app/ui/sidenav/sidenav.service.js
- src/app/ui/table/table-default-menu.directive.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/table/table-definition.directive.js
- src/app/ui/table/table.service.js
- src/app/ui/toc/toc.directive.js
- src/app/ui/toc/toc.service.js
- src/app/ui/tooltip/tooltip.service.js
Closes #2266 and related issues.
Split `layoutService` into two separate services:
- `LayoutService` works with actual layout (`currentLayout`, `isShort`, etc.)
- `ReferenceService` works with panels, mapnode, etc.
`reference.service` description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2337)
> fix(layout): use screen width when going fullscreen

- src/app/core/bookmark.service.js
- src/app/core/displaymanager.service.js
- src/app/core/reload.service.js
- src/app/core/statemanager.constant.service.js
- src/app/core/statemanager.service.js
- src/app/focus-manager.js
- src/app/geo/geo-search.service.js
- src/app/geo/init-map.directive.js
- src/app/geo/legend.service.js
- src/app/geo/map-tools.service.js
- src/app/ui/common/full-screen.service.js
- src/app/ui/common/stepper/stepper.class.js
- src/app/ui/details/layer-list-slider.directive.js
- src/app/ui/geosearch/geosearch-bar.directive.js
- src/app/ui/help/help.service.js
- src/app/ui/lightbox/lightbox.directive.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/table/table-definition.directive.js
- src/app/ui/table/table-search.directive.js
- src/app/ui/table/table.service.js
- src/app/ui/toc/legend-control.directive.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/toc.html
- src/app/ui/toc/toc.service.js
- src/app/ui/tooltip/tooltip.directive.js
Closes #1636 - focus link is set between legend block button and first focusable element in table
Also cleaned up some console warnings
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2343)
> fix(datatable): change focus link to allow proper tabbing

- schema.json
- src/app/core/config.class.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/ui/settings/settings-content.directive.js
- src/app/ui/settings/settings-content.html
- src/app/ui/settings/settings.directive.js
- src/app/ui/toc/legend-control.directive.js
- src/app/ui/toc/legend-element-factory.class.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/legend-control-link.html
- src/app/ui/toc/templates/legend-control-slider.html
- src/app/ui/toc/toc.service.js
- src/content/samples/config/config-sample-47.json
- src/content/samples/index-samples.tpl
- src/content/styles/modules/_setting-controls.scss
- src/content/styles/modules/_toc.scss
- src/locales/translations.csv
- [bug #2345] legend block symbology stack got stuck when expanded from the menu
- [bug #2131] opacity controls for `not-true-dynamic` dynamic layers are confusing - added jump link to parent block
Closes #2131, #2345
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2347)
> 2131 2345 confusing opacity slider and stuck legend stack

- src/app/core/formatters.filter.js
- src/app/core/statemanager.service.js
- src/app/focus-manager.js
- src/app/ui/common/dialog.decorator.js
- src/app/ui/export/export-generators.service.js
- src/app/ui/metadata/metadata-panel.directive.js
- src/app/ui/settings/settings.directive.js
- src/app/ui/table/table-default.directive.js
Closes #2344.
Closes #2353 - formatting dates correctly. 
~~Focus is only applied to the close button in the metadata panel if there is metadata displayed; so as long as the error is not thrown.~~
Also prevents an error from being thrown when the datatable has no rows displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2350)
> Fix focus in side and help panels

- src/app/core/config.class.js
- src/app/geo/layer-blueprint.class.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/app/ui/table/table-default-menu.directive.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/table/table-definition.directive.js
- src/app/ui/table/table.service.js
- src/app/ui/toc/toc.directive.js
- src/app/ui/toc/toc.service.js
Closes #2362 - filters are restored when reloading; currently only looks like it works for feature layers because of another bug that came up which is being looked at right now
Closes #2363 - when removing all filters by backspacing or deleting instead of hitting the `Clear filters` button, the `Apply to Map` option is available
Fixes small bug for #2120 - filtering on reload after opening datatable for dynamic layers
Visually tested - hours and hours of testing (still might have missed something)
Sample 46 can be used to test pre-existing filters and any sample can be used to test by adding filters.
JSDoc and in-line comments
Please keep the original issue up to date with the final solution, …
> 2362 2363 filtering on reload and applying to map when removing filters

- src/app/core/formatters.filter.js
- src/app/ui/help/help-summary.html
- src/app/ui/toc/templates/legend-info.html
- src/content/samples/config/config-sample-02-structured-legend-controlled-layers.json
- src/content/samples/config/config-sample-47.json
Add Markdown/HTML support to legend info sections.
Closes #2383
Eyeballing.
Inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2384)
> feat(ui): add markdown support to legend info sections

- src/app/ui/table/default.html
- src/app/ui/table/setting-cluster.html
- src/app/ui/table/table.service.js
- src/content/styles/modules/_table.scss
Closes #2374 - The table is still 'open' when the settings panel is open so the correct column widths can be calculated
Also renamed function `toggleSetting` to `openSettings` in `table.service.js`
Changed JSDoc for `openSettings`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2382)
> 2374 table width 

- src/content/styles/layout/_main.scss
- src/content/styles/modules/_geosearch.scss
One of the most annoying bugs has fallen!
Tooltips are no longer getting stuck when using geo search and scale-dependent layers.
Closes #1760
Visual.
Inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2391)
> fix(ui): tooltips are no longer linger after geoserach

- schema.json
- src/app/core/config.class.js
- src/app/geo/legend-block.class.js
- src/app/geo/map.service.js
- src/app/geo/overview-toggle.directive.js
- src/app/ui/export/export-legend.service.js
- src/app/ui/toc/toc.service.js
- src/content/samples/config-mobile-2.json
- src/content/samples/config/config-sample-01-structured-visibility-sets.json
- src/content/samples/config/config-sample-47.json
Closes #2367 - added option to include info sections and controlled layers to export legend
Closes #2376 - added option to have overview map initially collapsed
Closes #2387 - notification toast restored
To test #2367 - `index-mobile` or `index-samples` Sample 47
To test #2376 - `index-samples` Sample 01
To test #2387 - Remove any layer from anywhere
JSDoc for `_showBlock` and `_createSVGCode`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgp …
> Config options for export and overview map and removing layer toast

- src/app/core/reload.service.js
- src/app/ui/geosearch/geosearch.service.js
- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-file.html
- src/app/ui/table/table.service.js
- src/content/styles/modules/_progress-indicator.scss
- src/locales/translations.csv
- Closes #2390
- Closes #2157 
- Fixed bug for undefined panel (`geosearch.service.js`)
- Modified filter flag to not display when `Filter By Extent` is enabled and changed tooltip text
This can be used to test file size counter: http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/G%C3%A9ochronologie.csv
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2400)
> 2390 close export image, 2157 file size counter

- src/app/ui/common/stepper/stepper.class.js
- src/app/ui/loader/loader-file.directive.js
- src/app/ui/loader/loader-service.directive.js
- src/app/ui/table/table.service.js
Closes #2396
Also made changes to the loader functionality;
- when importing a file, if you drag and drop on any step, it'll reset to first step and then continue the upload
- when importing a service, cancelling on the first step will clear the field
Fixed small undocumented bug when filtering by extent and table is not open (`table.service`)
Sample 1 can be used to test #2396 (and the loader too)
--- …
> 2396 filtering by extent and loader modifications

- docs/developer/function/index.json
- docs/developer/function/scale_dependent_layers.md
Adds some info on scale-dependent layers.
Closes #1097
Nope.
:+1: 
- ~~[ ] Release notes have been updated~~ not neeeded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2401)
> docs(layers): add some docs about scale-dependent layers

- src/app/core/constant.service.js
- src/app/geo/layer-registry.service.js
- src/app/geo/map.service.js
When a feature is highlighted, the next click will clear the highlight/haze without triggering identify, unless you click directly on another feature, in that case, the identify will trigger right away.
Relates #2395
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2413)
> feat(ui): remove feature highligh on click

- src/app/geo/legend.service.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/toc/toc.service.js
Closes #2404 - clearing filters functionality fixed
Closes #2406 - panel is reopened if it is connected to the layer being reloaded. Otherwise, it's closed
Any sample can be used to test. For #2406, you can use [this](http://section917.cloudapp.net/arcgis/rest/services/TestData/Nest/MapServer/0) service for dynamic groups.
Lots of comments added, some JSDoc changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2408)
> 2404 clear filters and 2406 reopen panel on reload

- package.json
- src/app/ui/export/export-legend.service.js
Related to PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2402, @JahidAhmed noticed in IE that text was not displaying at all so markdown is stripped for IE instead. 
@JahidAhmed can you verify in IE, if it works ok to merge.
No IE on linux, so tested in chrome and :pray: 
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2437)
> fix missing IE text by instead stripping markdown altogether

- package.json
- schema.json
- src/app/core/config.class.js
- src/app/ui/loader/loader-service.directive.js
- src/app/ui/loader/loader-service.html
- src/app/ui/settings/settings-content.directive.js
- src/app/ui/settings/settings-content.html
- src/content/samples/config/config-sample-01-structured-visibility-sets.json
- src/content/styles/modules/_loader.scss
Related to #332 
Allows users to choose styles for layers while importing (Step 3)
Also allows changing styles to be disabled (legendEntryControls).
Sample 1 can be used to test disabled styles control
This service can be used to test configuring styles when importing: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities.
Comments, JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2429)
> WMS Layer Styling

- .vscode/settings.json
- src/app/geo/layer-registry.service.js
- src/content/samples/config/config-sample-51.json
- src/content/samples/index-samples.tpl
Enforces layer order specified in the config file is used to synchronize the map stacks layer order. Before, the layer selector order was used.
Closes #2348 
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2431)
> fix(core): enforce config layer order

- package.json
- schema.json
- src/app/core/config.class.js
- src/app/core/constant.service.js
- src/app/focus-manager.js
- src/app/ui/table/table.service.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/legend-info.html
- src/app/ui/toc/templates/legend-node.html
- src/app/ui/toc/templates/symbology-stack.html
- src/content/styles/modules/_symbology.scss
- src/locales/translations.csv
Allows symbology to be toggled. New controls added when symbology is expanded. Symbology is filtered both on the map and table (if open).
Can be disabled in config under layer config as `toggleSymbology: false`. It's true by default.
Do not merge until James gives the :white_check_mark: since geoApi is being beefed up to handle more edge cases on the `definitionClause`.
@dan-bowerman got you on this as well to make sure this works for CESI.
Closes #2368
46 `Dynamic Layer with only one child with filter -> Power Plants".  You can also test sample 1 crops but dt is very slow.
inline
Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes …
> Ability to toggle ranges via legend

- .gitignore
- .vscode/settings.json
- src/app/ui/table/default.html
- src/app/ui/table/table-default.directive.js
The datatable will not longer get stuck in a failed state after the data load errors or a user switches the table to a different layer while the table is still being rendered.
Closes #2410
- ~~[ ] Release notes have been updated~~ not a released bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2441)
> fix(ui): datatable renderes correctly

- src/app/ui/common/full-screen.service.js
Rewrote the fullscreen service:
- Animations cannot be used on OS level fullscreen changes, therefore they were removed.
- The animation timelines caused the need for `$timeout`, this is the first time I've removed a `$timeout` :tada: 
- There is no support, at the moment, for when a user uses the `F11` key instead of through our UI since
- Programmatic use of fullscreen API (in our UI) is handled from browser -> OS and therefore can trigger the proper events
- F11 is directly OS, no browser events are fired
> Aha! Why don't you detect the F11 keydown event?
Because no `F11` event is triggered when exiting fullscreen, only the first one entering fullscreen. Remember, `F11` in fullscreen is an OS level command, the browser won't see it.
Chrome, IE with both eyes
inline
Remember, it is a …
> fix(fullscreen): re-center works in IE, removed unused animations

- src/app/geo/legend.service.js
- src/app/ui/toc/toc.service.js
Ensure layer entry does not get removed when failed to reload as well as error out a customized message when in times of failure.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2425
Try to reload the CESI layer
Before:
http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO
After:
http://fgpv.cloudapp.net/demo/users/barryytm/2.1.1-2425/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO
NA
--- …
> Ensure layer entry does not get removed when failed to reload

- src/app/ui/common/full-screen.service.js
- src/app/ui/toc/templates/legend-control-input.html
Closes #2487
Closes #2476 
Closes #2052 ? I think; it seems to be working now.
Visually tested. Chrome and IE. `index-samples` and `index-mobile`
Restored earlier comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2496)
> fix(ui): fullscreen menus and positioning

- src/app/geo/legend-block.class.js
Fix bounding box not retaining/working when changing basemap with a different projection.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2468
Manually, try enable bounding box then switch to a different base map with different projection
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2505)
> Fix bounding box when changing basemap with a different projection

- src/app/geo/legend-block.class.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2514
Fix issue with bounding box unable to turn off 
http://fgpv.cloudapp.net/demo/users/barryytm/2.2.0-2514/dev/samples/index-fgp-en.html?keys=ZoomScale
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2521)
> Fix bounding box toggling issue

- src/app/geo/layer-registry.service.js
Layer reorder was broken by the sync function always referring to the original layer order from the config file. Now the original layer order from the config is used only for structured legends; auto legends use legend block order.
Closes #2536
Eyeballs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2537)
> fix(core): broken reorder for auto legends #2536

- package.json
- schema.json
- src/app/core/config.class.js
- src/content/samples/config/config-sample-54.json
- src/content/samples/index-samples.tpl
Closes #2528
Add a property `imageFormat` in dynamicLayerNode for users to configure the dynamic layer image output format.  This allows a higher quality of image for users to view.
Added sample 54 for testing, try changing the opacity to see the difference.
http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2528/dev/samples/index-samples.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2548)
> Allow configuration for dynamic layer image output format

- src/app/ui/common/full-screen.service.js
Closes #2555 
Override browser's default full screen exiting action when using `Esc` or `F11`.  Replace the overridden action with a custom made action.
Enter full screen mode, then exit with `Esc` or `F11`.
http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2555/dev/samples/index-fgp-en.html
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2568)
> Exit Full screen at intended

- src/app/core/core.run.js
- src/app/focus-manager.js
- src/app/geo/init-map.directive.js
From the code:
> We allow the angular material menu component to set its own initial focus by default. However when there is no focusable element in the component, AM does not set focus which leaves focus on the triggering element. This is turn makes it impossible to close the menu using the escape key.
> The solution is to predict if a focusable element exists, and if not to set focus on the overall menu element.
Minor fixes to apply FM specific logic to both programmatic and manually created maps at startup.
Future updates to FM will make more use of `MutationObserver` for improved performance and maintainability.
Closes http://tfs.int.ec.gc.ca:8080/tfs/DC/CCPED/_workitems?_a=edit&id=36428 when merged and `v3.1` is rebased on `develop`.
Tested @ …
> fix(focus manager): Add MutationObserver for angular material menus

- package-lock.json
- src/app/geo/legend.service.js
Through using the API for CIP we came to the conclusion that keeping layers on the map when the structured legend changes is easier to manage.
```
var mapInstance = RZ.mapInstances[0];
var sLegend = [];
sLegend.push({"layerId": "crops"});
mapInstance.legendConfig = sLegend;
```
And then see the "liquids" features are still visible on the map.
:speak_no_evil: 
No code added, no documentation to add.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2655) …
> feat(legend): keep layers in map on legend change

- src/app/ui/export/export-generators.service.js
- src/content/styles/modules/_table.scss
Closes #2649, #2652
Truncate `Name` in datagrid setting if too long.  Fix the direction of north arrow when exporting in Mercator projection.
Visually
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2653)
> Couple of UI fixes

- src/app/core/constant.service.js
- src/app/geo/map.service.js
Closes #2596, #2644 
Remove "setMapCursor" of null errors by unsubscribing feature hover events when destroying a map instance.
1. Go to http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2644/dev/samples/index-samples.html
2. Switch to another sample that with feature layers
3. Open Console
4. Hover over one of the features
5. Try to find "setMapCursor" of null errors
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2648)
> Unsubscribe feature hover events when destroying a map instance.

- src/app/geo/map.service.js
- src/content/samples/index-samples.tpl
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2660## Description
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2618
Fix viewer failure causes by switching to anther sample (different map instance).
Manually, try switching samples in `index-samples`
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2660)
> Intention Patch

- package.json
- src/app/geo/legend.service.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/toc/toc.service.js
Closes #2544.
Closes #2670.
Closes #2671 - if the layer is not in the legend, directly remove the `layerRecord` if it exists.
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2672)
> 2544 identify, 2670 zoom, 2671 API removing layers

- src/app/ui/export/export.service.js
Adds ability to specify export extension type (png is default or jpg only) via the legacy API call:
```js
RZ.mapInstances[0].mapI.export(); // png (legacy support)
RZ.mapInstances[0].mapI.export('png'); // png
RZ.mapInstances[0].mapI.export('jpg'); // jpg
```
This is to support [CIP PBI 38424](http://tfs.int.ec.gc.ca:8080/tfs/DC/CCPED/_workitems?id=38424)
👀 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2667)
> feat(export): add support for specifying download file type.

- package.json
- src/app/core/config.class.js
- src/app/geo/geo.service.js
- src/app/geo/legend.service.js
- src/app/geo/map.service.js
Fix the layer stack order for autolegends and as a result, the map layer order 
:eyes: - tested with both working and broken initial basemap by importing tile layer and then dynamic layer through API in both autolegend and structured legend
In-line comments, JSDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2677)
> fix(ui): layer stack order

- src/app/ui/table/setting-panel.html
- src/app/ui/table/table-setting-panel.directive.js
- src/content/styles/modules/_table.scss
Relates to #2649 
Add tooltip for truncated cells under column `Name` in datagrid setting
Find a `Name`/`Nom` that is truncated in datagrid setting, then hover to see the tool tip.  If none was found, try shrinking the width of the window until one of the cells is truncated.
Sample: http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2649/dev/samples/index-fgp-fr.html?keys=CESI_Other
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2669)
> Add tool tip for truncated cells under column `Name` in datagrid setting

- src/content/styles/modules/_setting-controls.scss
Closes #2673
Remove extra refresh interval clear cross in IE
Visually in IE 11.  
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2681)
> Remove extra refresh interval clear cross in IE 11

- src/app/geo/legend.service.js
- src/content/samples/config/config-sample-16-structured-legend-tile-layer-only-valid-one-proj.json
- src/content/samples/config/config-sample-63.json
- src/content/samples/index-samples.tpl
Closes #2679
Fix legend order of newly added feature layers
Feature service: http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/2
feature file: 
http://fgpv.cloudapp.net/demo/__assets__/Sample%20Data/convert.json
in sample 15, 16, 59
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2694)
> Fix legend order of newly added feature layers

- src/app/ui/tooltip/tooltip.service.js
Closes #2614
Prevent hovertip from following mouse in IE
Tested by hand. Verified in all browsers. 
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2710)
> fix(ui): prevent hovertip from following mouse

- webpack.common.js
Reduces moment-timezone bundle size from 528kb to 164kb by removing unused locales. Actual production bundle reduced by 197.3Kb. There is another library https://date-fns.org/ worth looking at in the future which is just as capable and smaller in size.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2713)
> Reduce bundle size by removing unused locales in moment-timezone

- api/src/events.ts
- api/src/map.ts
- src/app/core/config.class.js
- src/app/geo/identify.service.js
- src/app/geo/map.service.js
- src/app/ui/sidenav/sidenav.service.js
- src/content/samples/config/config-sample-63.json
- src/plugins/core/coord-info.js
Closes #2375 - plugins is an available item in side menu.
Closes #2625 - coords info active until manually disabled. also disabled identify which plugin active, and resets identify value to previous value after plugin disabled. also fix small bug with `parseUtm` function, when `zone < 10`.
Closes #2612 - create a `mapPoint` using screen point if it does not already exist.
:eyes: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2721)
> Plugins modifications and API mouseMove

- api/src/layers.ts
- api/src/map.ts
- package-lock.json
- package.json
- src/app/core/config.class.js
- src/app/geo/identify.service.js
- src/app/geo/layer-registry.service.js
- src/app/geo/legend-block.class.js
- src/app/geo/map.service.js
- src/plugins/core/coord-info.js
Closes #2600 - buffer size can be set for each layer individually
Closes #2684 - idea 1 implemented
Starts on #2603 - moved `identifyMode` to from `Map` to `LayerGroup` and added `queryable` option to `ConfigLayer` which is linked with the UI query option in settings panel
:eyes: 
To test identify mode: 
```js
`RZ.mapInstances[0].layers.identifyMode = 'none'` // turns off identify 
`RZ.mapInstances[0].layers.identifyMode = 'details'` // turns on identify 
```
To test field name in identify result (open the logged features array and check the contained data array):
```js
RZ.mapInstances[0].layers.identify.subscribe(event => {
event.requests.forEach((request, index) =>
request.features.then(features =>
console.log(features)
)
);
});
```
To test layer `ConfigLayer` queryable:
```js …
```
> fix(api): identify buffer size and layer queryable

- src/app/geo/legend.service.js
Relates to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2679
**Before fix:** new layers/legends were added at the bottom of the existing layers/legends of the [same rank](https://github.com/barryytm/fgpv-vpgf/blob/2.4.0-2679-patch/src/app/geo/geo.constant.service.js#L66).
**After fix:** new layers/legends will be added on top of the existing layers/legends of the [same rank](https://github.com/barryytm/fgpv-vpgf/blob/2.4.0-2679-patch/src/app/geo/geo.constant.service.js#L66).
Add any layers using the add button.  
Layer used for testing (changed the index at the end for a different layer): http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/27
NA
Remember, it is a *muffin offence* to open a PR with any of the above checklist items …
> Correct newly added layer positioning 

- src/app/api-loader.ts
- src/app/geo/init-map.directive.js
- src/app/startup.ts
- src/app/tag-manager.js
Adds [Google Tag Manager](https://developers.google.com/tag-manager/quickstart) code programmatically on RAMP startup. Adds the GTM dataLayer on our api.  `tag-manager.js` will contain push events triggered by api observations and consolidates tracking into one central location. Most tracking is configured within GTM console. The one's that aren't are included in this PR:
-  tracking the time it takes from page landing to when `events.rvMapLoaded` is fired. This is passed through to analytics user speed analysis. 
- extent changes (pan/zoom)
- basemap changes
Tags firing as expected when tested in preview mode in GTM.
None yet
- [] Help files and documentation have been updated
Please keep …
> feat(analytics): integrate google tag manager

- src/content/samples/index-samples.tpl
Closes #2767 
Fix the problem where the plugin - area of interest would not fresh if the corresponding config was not initially selected nor not reloaded.
Try load a sample other than 64 initially, then load sample 64 and open area of interest.  Tested in IE as well.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2769)
> Fix the blank issue of area of interest 

- schema.json
- src/app/core/config.class.js
- src/app/core/config.service.js
- src/app/geo/geo.constant.service.js
- src/app/geo/map-tools.service.js
- src/app/ui/common/north-arrow.directive.js
- src/content/samples/config/config-sample-44.json
Closes #2771 
Prevent the north pole icon being set when the spatial reference is not Lambert and add some constants.
sample 44
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2772)
> Prevent the north pole icon being set when the spatial reference is not Lambert

- src/app/geo/legend.service.js
- src/app/ui/common/north-arrow.directive.js
Fixes:
#2776 
#2716 
North pole layer is now created directly instead of relying on the API, and the structured legend config swap is now simpleLayer proof.
No unit tests.
```
RZ.mapInstances[0].mapI.setLegendConfig({"root": {
"name": "root",
"children": []
}})
```
The above will now run with no errors, north pole/arrow still exist, everything is happy. :smile: 
Any in-line comments that needed updating have been updated.
--- …
> Structured legend revival

- src/app/core/config.class.js
- src/app/geo/layer-blueprint.class.js
- src/app/ui/table/table-default.directive.js
- src/app/ui/table/table-definition.directive.js
- src/app/ui/table/table-search.directive.js
- src/app/ui/table/table.service.js
- src/content/samples/config/config-sample-61.json
Before: filter from config of type 'date' not filtering the table.
Values not loading properly. Confusion on type ('date' vs 'rv-date')
Filtering results from search, date picker and config not similar.
After: filter from config of type 'date' filtering the table.
Filtering results from search, date picker and config are similar.
Closes #2749
|Browser|Works as expected|
|---|---|
|Chrome| :white_check_mark: |
|Fox| :white_check_mark: |
|Edge| :white_check_mark: |
|IE11| ❌ see #2749 |
with service:
[https://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer](https://geoappext.nrcan.gc.ca/arcgis/rest/services/GSCC/Geochronology/MapServer)
Double checked with the table which can be found [here](https://www.nrcan.gc.ca/earth-sciences/geography/atlas-canada/geochron/18211) …
> fix(table): table dates filtering

- docs/index.html
- src/app/ui/common/error.service.js
Corrected technical documentation links in our hosted documentation. Bonus points for using regex 🏆 
Closes #2812
https://ramp-docs.fgpv-vpgf.com/doc-test-01
None added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2813)
> fix(docs): correct links to technical docs

- src/app/ui/toc/templates/symbology-stack.html
Console was being flooded with error messages because it couldn't find the `image` property for icon style symbology. 
:eyes:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2817)
> fix(ui): failure to load image 

- package-lock.json
- package.json
- src/app/ui/details/details-record-esrifeature-item.directive.js
- src/app/ui/table/table-setting-panel.directive.js
Closes #2485 #2803 
Allows showing or hiding details fields in the identify details. 
By default `SHAPE`, `Shape`, `rvSymbol`, `rvInteractive` are hidden.
The table columns specified to show in the config will also apply to the details in the details panel. 
Columns hidden using the table settings will also be hidden in the details panel. 
:eyes:
In `index.samples` configs `1, 6, 7, 40, and 68` are good for checking various cases. 
in-line commenting 
--- …
> feat(ui): allow showing or hiding details fields

- api/src/schema.d.ts
- docs/user/details_templating.md
- src/app/ui/details/details-record-html.directive.js
- src/app/ui/details/details-record-text.directive.js
- src/content/samples/templates/test-script.js
- src/content/samples/templates/test-template.1.html
- src/content/samples/templates/test-template.html
Use $watchCollection to watch for resolving identify requests in custom templating directive. Using $watch on an array does not fire when elements are added or removed. Also pass the current language value to the parser function and its template, so the output can be tailored to the current locale.
Relates #2814
:eye: 
Updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2836)
> fix(ui): custom templating uses $watchCollection

- api/src/schema.d.ts
- schema.json
- src/app/ui/details/details-record-esrifeature-item.directive.js
- src/content/samples/config/config-sample-70.json
- src/content/samples/templates/test-script.js
Initially an assumption was made that feature layers wouldn't need a parser as they return JSON, but there is still value in allowing a function to run before details output (like getting translation strings for a template, etc.)
Sample 70, the electricity layer now runs a parser before displaying details
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2846)
> feat(details): allow parsers for feature layer details output

- package.json
- src/app/geo/layer-blueprint.class.js
- src/app/geo/layer-registry.service.js
- src/app/ui/details/details-record-esrifeature-item.directive.js
Fixes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2859 and a pile of other broken cases.
Recognizes when a WFS is loading from the config.
Pushes the service data requests to a separate thread (not on the Blueprint constructor thread).
Updates WFS Layer Record with real layer once separate thread finishes.
Layer loader will avoid attempting to add layer to map until things are actually ready.
Tested in RAMP - autolegend and structured legend.  Tested in CCCS viewer.
--- …
> Fix race condition on wfs load

- src/app/geo/legend.service.js
Legend waits on blueprints to be created. Layers added via the api had their blueprint promises lost.
Made change to catch them and make legend respect them
Testing on viewer and CCCS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2867)
> Make legend wait for api layer blueprints

- src/app/geo/layer-registry.service.js
WMS layers that omit a GetCapabilities, and initialize to invisible, never get to the `loaded` state.  The legend will show them as always loading (and not offer a visibility control).
Added some hack code to force it to loaded.
Tested against RAMP samples (both auto & structured), and against CCCS viewer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2873)
> Force invisible local wms to load

- package-lock.json
- src/app/ui/details/details-record-esrifeature-item.directive.js
- src/app/ui/details/details-record-html.directive.js
- src/app/ui/details/details-record-text.directive.js
Angular digest cycles would clash when running the `scope.$apply` before compiling the details template; replaced that with a `$timeout` that runs as soon as the current cycle is over. Additionally, some wms layers would not update their templates correctly; added a watch to force the link function to actually do something.
Tested multiple configs
in-line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2874)
> fix(details): fix digests clashing, items not showing

- src/app/geo/layer-blueprint.class.js
- src/app/ui/table/table.service.js
Closes #2864. Selector filters now work properly.
Done by fixing formatting of filter definitions.
Click on sample 61. Make sure one or more country filters are selected. 
[Build 2.5.0-b1](http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-samples.html): Breaks layer, did not filter properly.
[With this PR](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/correct-grid-filter/prod/samples/index-samples.html): Layer stays intact, points filtered properly by country (and whatever other filters are specified).
Note applicable. 
--- …
> fix(table): fix selector filter

- schema.json
- src/content/samples/config/config-sample-64.json
- src/content/samples/config/config-sample-73.json
- src/content/samples/index-samples.tpl
- src/plugins/core/area-of-interest.js
Addresses second and third bullet points in #2787. This PR is to be used as a "save point" before functionality is moved to an extension using the Panels API.
- `noPicture` option added to `areaOfInterest`
- Thumbnails and extents should work for Sample 64
- No thumbnails are shown for Sample 73 (but same extents/descriptions as 64)
Samples 64 (Pictures enabled) and 73 (Pictures disabled)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpg …
> perf(plugin): thumbnails, noPicture opt in config

- src/app/geo/overview-toggle.directive.js
Displays a toast when the default or selected basemap has failed to load.
Closes #107
👀 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2849)
> fix(ui): basemap load failed error toast fixed

- src/app/geo/layer-blueprint.class.js
Closes #2837 
http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/mercator-projection/prod/samples/index-samples.html (Sample 68 - WFS Layers Defined in the Config)
All layers in default pre-added to Lambert Maps should be visible upon switch to Mercator Basemaps. 
User added layers imported from wizard (GeoJSON, CSV, Shapefiles) should load properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2862)
> fix(geo): WFS layers appear in Mercator Basemaps

- src/plugins/core/area-of-interest.js
Area of interest plugin threw error when not used on the map. This is now fixed.
Test sample 64 a and b (plugin defined) and compare it to rest of the samples. No errors from this file should be thrown. 
Not applicable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2884)
> fix(plugin): fix plugin to not throw an error when not in use

- package-lock.json
- package.json
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2578. Updated version of `marked` dependency to latest version `0.4.0` which should be free of vulnerabilities. 
None (that I know of). Build generated successfully with the updates made to `package.json` and `package-lock.json`
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2887)
> fix(package): update marked to v4.0

- src/app/core/statemanager.service.js
- src/content/styles/layout/_main.scss
Gives some extra space to work with below panels (on the z-axis). Helps with integrations like CCCS where we have other panels to layer.
:eyes: and inspecting the css in devtools
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2910)
> Move panels higher in z-index

- package-lock.json
- src/app/geo/identify.service.js
- src/app/geo/layer-blueprint.class.js
- src/app/geo/layer-registry.service.js
- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
This is related to #2859. This comment specifically: #2859 (comment).
This is another refactor update leading up to hopefully fixing layer loading process.
The generation of `LayerRecord`s is now treated as an async call. `LayerBlueprint`s return promises resolving with `LayerRecord`s (although the blueprint loading process is not fixed yet - that's the next part). A `LayerRecord` can now exist in a sort of limbo, not added to the map yet, but in the process of being made. As such, it will be excluded from the `map.layerRecords` array. There is a new function in the `layerRegistry` to get a promise of `LayerRecord` even if it's still loading. 
There are now two major cases:
`LayerRecord`s are made "instantaneously"; their `proxy` objects are also created synchronously. The corresponding …
> 2859 wfs loading restructuring backwards - Part 2 

- package-lock.json
- package.json
Supports this PR in `geoApi`: https://github.com/fgpv-vpgf/geoApi/pull/320
sampe 68: WFS points didn't have outlines before, now they do
n/a
- [x ] PR targets the correct release version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2927)
> Circle outline support

- src/app/ui/toc/toc.service.js
Remove toast "Layer Removed" when a layer is removed with the api.
👓 
❌ 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2938)
> Suppress toast/undo for layers removed via the api

- api/src/legend.ts
- src/app/geo/legend.service.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/toc.service.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2931
Creates new `LegendItem` class for new Legend API. 
***Notes:***
- `reload` and `remove` function not included
- `console.logs` were left purposefully for testing purposes (to be removed in final PR to `v3`)
-  datatables are broken in `v3` so they are broken over here
- you'll notice that `settings` and `metadata` panels don't always toggle properly...this happens even when existing ui for them is clicked
https://gist.github.com/ShrutiVellanki/b6449f38e0abb246ed5888addc0b9e6f
JSDocs, inline comments
---
This …
> feat(api): add LegendItem class for new Legend API

- src/app/geo/legend-block.class.js
- src/content/samples/config/config-sample-11-structured-legend-opacity-disable.json
- src/content/samples/index-samples.tpl
Closes #2594 #2658
_**Update:** Sample 11 now has multiple dynamic layers with various initial opacities._ 
Fixes issue where opacity would not apply for dynamic layers where initial opacity was set to 0. 
Changes were made in line with [this comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2594#issuecomment-381215002) going with the option to fix the initially outlined expected behaviour. 
Also Barry's [comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2594#issuecomment-384373771) is no longer an issue since a label has been added to show child values differ from parent.
:eyes: 
Sample 11 - Finally working when you change opacity
Please keep the original issue up …
> Broken opacity setting when initial opacity is 0

- api/src/schema.d.ts
- schema.json
- src/app/core/config.class.js
- src/app/ui/export/export-generators.service.js
- src/app/ui/export/export-legend.service.js
- src/content/samples/config/config-sample-77.json
- src/content/samples/index-samples.tpl
Adds a config attr for custom legend column width.
Removes structured legend titles with nothing under them.
Fixes issues with export legend structure, removes extra titles that no longer have entries between them and another title (or the end of the legend).
Also adds a config attribute `columnWidth` on export.legend that specifies the column width for the export legend image.
Sample 77: titles will do as their names imply, legend should be rendered as one column in default export.
inline
--- …
> enhance export legend 

- src/app/ui/toc/symbology-stack.directive.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2888.
- Symbology toggle checkboxes are now aligned with parent layer checkboxes
- Achieved by adjusting padding slightly
Pixel alignment tested using [Greenshot](http://getgreenshot.org/)
1. http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/symbology-checkboxes/dev/samples/index-samples.html?keys=JOSM,CESI_Other,NPRI_CO
2. Sample 46, look at these layers: 
none
--- …
> Symbology stack checkboxes aligned with parent

- src/app/ui/toc/symbology-stack.directive.js
Closes #2935 
Prevent symbology stack overlapping and fix the issue with description of the symbol not fully shown.
1. Add service: http://maps.geogratis.gc.ca/wms/railway_en
2. Add `Railway Subdivision Name` (the image is not working) and add any other layer(s)
3. Open the symbology stack.
NA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2943)
> Fix symbology stack overlapping issue

- src/app/core/bookmark.service.js
- src/content/samples/bookmark-decode.html
- src/content/samples/config/config-sample-26.json
Closes #2944 
Fix issue where bookmark was not able to encode non Latin1 characters by convert them to URI components.
1. http://fgpv.cloudapp.net/demo/users/barryytm/2944/dev/samples/index-samples.html?sample=26
2. Go to Menu
3. Click SHARE
4. Copy the link and decode it in http://fgpv.cloudapp.net/demo/users/barryytm/2944/dev/samples/bookmark-decode.html
**Note:** The en dash `–` is not a Latin1 character.  
NA
--- …
> Fix bookmark encoding with non Latin1 characters 

- src/app/ui/details/details-record-html.directive.js
- src/app/ui/details/details-record-text.directive.js
Fixes issue where multiple parser calls were being made by an item data watcher.
Closes #2929
Built and tested on CCCS develop
none
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2957)
> Fix multiple details parser calls

- package-lock.json
- package.json
Print map was modifying layer SVGs and causing them to be offset when the map resized.
Most prominent was print map -> fullscreen pushing features away from their proper locations.
https://github.com/fgpv-vpgf/geoApi/pull/322
index-samples 76 and 75
in-line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2960)
> Fix export map and full screen clash

- package-lock.json
- src/app/core/graphics.service.js
- src/app/ui/export/export-legend.service.js
Fixes CCCS bug 43540: Cannot download map if Legend selected in chrome
Chrome, FF, IE
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2952)
> fix(export): export image working in chrome when legend is included

- src/app/geo/layer-registry.service.js
- src/app/geo/legend-block.class.js
- src/content/samples/config/config-sample-78.json
- src/content/samples/index-samples.tpl
Prevents excessive and premature display of error toasts. If the layer does fail properly, the error toast will be displayed as expected.
Closes #2971
- open sample 78
- pan and zoom around
- observe no error toast and no failed legend entries
- open console and see lots of tile images failing to load (that's expected)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2972)
> fix(ui): prevent excessive and premature errors

- src/app/ui/export/export-legend.service.js
Info sections were failing to appear in export legend.
Sample 77
Click export, you should see the legend properly generate with headers and the image should be downloadable.
in-line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2973)
> fix(export): make export legend svg generation sync

- src/app/startup.ts
Adds support for `document.createTouch` (deprecated and dropped on chrome 68+) where the browser supports `window.Touch`. 
Closes #2962
Pan & zoom working on pixel chrome 68 for CCCS.
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2963)
> Fix pan & zoom on Chrome 68+ for touch/pen events

- src/app/startup.ts
Fixes TS error on [v2.8.3](https://github.com/Microsoft/TypeScript/blob/v2.8.3/lib/lib.dom.d.ts#L13308) where `Touch` constructor has no parameter causing prod build to error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2974)
> fix(esri): Polyfill createTouch with Touch

- src/app/ui/toc/symbology-stack.directive.js
- src/content/samples/config/config-sample-77.json
#2975 
It was the `ref.descriptionItem.show()` breaking things. Removed the rest of it as I couldn't find a case where `.height()` didn't work. I assume the other logic was an attempt at patching the `.show()` error.
Sample 77, second layer has multi-line description and icon symbology.
removed misleading comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2976)
> fix(ui): fix icons covering description

- src/app/startup.ts
Adds a polyfill for `Promise.prototype.finally` as it's not supported by Safari 11 and some other browser versions.
Closes #2982
Test in Browser stack with an iOS Safari 11 device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/2983)
> fix(core): add `finally` polyfill for Safari

- src/app/ui/toc/symbology-stack.directive.js
#2975 
Properly see if `.height()` is returning the height of the description. Before it was taking `0` as a proper height when it should've fallen back to the calculation.
Last attempt was #2976 . Always worked on ramp because icons were inline SVG, CCCS race condition decided to take a break for a bit that day.
Sample 77 + tested in cccs
Reinstated old comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3000)
> Fix icons overlapping description (properly this time)

- src/app/geo/legend.service.js
- src/content/samples/config/config-sample-07-structured-legend-one-group-proper-subset.json
- src/content/samples/config/config-sample-08-structured-legend-one-layer-muti-legends.json
Closes #2987 
Dynamic layers with `symbologyExpanded` set in the config will expand the symbology of all its child layers.
:eyes:
index-samples 7 & 8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3005)
> fix(ui): `symbologyExpanded` not working for dynamic layers

- package-lock.json
- src/app/ui/export/export-legend.service.js
Prod builds weren't finishing but were getting a :heavy_check_mark: from travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3016)
> fix(build): remove prod destroying comma

- src/app/ui/common/expand-image-button.html
- src/app/ui/common/expand-image.directive.js
- src/content/samples/config/config-sample-67.json
Closes #3003
[Sample 67](http://fgpv.cloudapp.net/demo/users/dane-thomas/repeat-image-req/dev/samples/index-samples.html?sample=67)
Now has an image with a bad link. Should see the `GET` error once in the console on initial failed load and none after. Big images should still have working expand buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3015)
> fix(ui): invalid legend img url results in repeated requests

- package-lock.json
- src/app/startup.ts
- src/content/samples/index-samples.tpl
Adds the `rz-gtm` html attribute to the map element to opt-in to our google tag manager tracker.
Closes #3018
👁 
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3020)
> opt-in to google tag manager via rz-gtm on map element

- src/app/ui/common/expand-image.directive.js
Expanding images when the legend takes up the entire app width doesn't make much sense, on small layouts we now force there to be no zoom button.
sample 67; Button appears normally at large size, reducing the screen width to small and refreshing will remove the zoom button on the images.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3032)
> fix(ui): don't expand images in small layout

- src/app/geo/layer-blueprint.class.ts
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3022
File wizard now loads GeoJSON with custom projections.
save the following in a file (eg: `example.json`):
```js
{
"type": "FeatureCollection",
"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3174"}},
"features": [
{
"type": "Feature",
"properties": {"name":"4905 Duffers"},
"geometry": {
"type": "Point",
"coordinates": [
1400729.1329429878,
813466.9383310359
]
}
}
]
}
```
Try importing through file wizard, if it doesn't error and something like the follow shows up, the fix works.
Please keep the original issue up to date with the final solution, expected behaviour, …
> fix(epsgLookup): file wizard loads GeoJson with custom projection

- package-lock.json
- package.json
Closes: fgpv-vpgf/fgpv-vpgf#2981
When Dynamic Layers in symbology stacks were identified, all symbologies in close proximity were identified (regardless if they were toggled on/off). Now only the symbologies that are toggled visible  are identified.
Test sample 46, also `keys=NPRI_CO`
http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/fix-dynamic-identify/dev/samples/index-samples.html
--- …
> fix(dynamicRecord): identify filters out invisible symbologies in stack

- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/symbology-stack.html
- src/content/styles/modules/_symbology.scss
Fix in #3011 wasn't working in all situations. Should now properly align the symbology whether or not there's a scroll bar. 
:eyes:
Sample 46
http://fgpv.cloudapp.net/demo/users/dane-thomas/symbology-toggle-offset/dev/samples/index-fgp-en.html?keys=CESI_Other,JOSM
Any layers with toggle symbology 
in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3034)
> fix(ui): symbology toggle not aligned with parent

- src/app/ui/toc/symbology-stack.directive.js
Fix in #3034 wasn't working in all situations. Should now properly align the symbology whether or not there's a scroll bar. 
:eyes:
Sample 46
http://fgpv.cloudapp.net/demo/users/dane-thomas/symbology-toggle-offset2/dev/samples/index-fgp-en.html?keys=CESI_Other,JOSM
Any layers with toggle symbology 
in-line comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3035)
> fix(ui): symbology toggle bug with scroll bar

- package-lock.json
- src/app/ui/geosearch/geosearch.html
- src/app/ui/geosearch/geosearch.service.js
- src/content/styles/modules/_geosearch.scss
- src/locales/translations.csv
Displays an error when the search query is rejected.
Block requests to `geogratis.gc.ca` in dev tools after the map has finished loading, then perform a search.
❌ 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3001)
> fix(search): add error when search query rejects

- package-lock.json
- package.json
- src/app/core/core.run.js
- src/app/geo/geo.service.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3023
Links in geoApi patch and fixes a few other instances where the map extent set was not respecting the map size.
`index-fgp-en.html` is the best test for my monitor.  Basically, find any map that, on load, cuts off southern Ontario (you can resize your browser until it happens).  Then with same size, load this build and see that the map starts at a zoom level that shows all of Canada.
--- …
> Fit extent to map

- package-lock.json
- package.json
Closes #3049
check https://github.com/fgpv-vpgf/geoApi/pull/330 for the geoApi changes
:eyes: 
https://webservices.maps.canada.ca/arcgis/rest/services/PHAC/fluwatchers_en/MapServer/0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3052)
> fix(ui): update geoApi to fix queries where min and max are equal

- src/app/geo/legend.service.js
Fix issue with parent element not being found before accessing children
:eyes:
Reload layer through api or otherwise. Should no longer see an error in console stating parent wasn't found. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3046)
> fix(legendAPI): fix parent not found before trying to access children

- src/app/ui/toc/symbology-stack.directive.js
Code essential for identify (geoAPI side) got deleted here https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3050.  Reversed this fix: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3036. This PR adds it back.
Tested with `JOSM`, `NPRI_CO`, `CESI_Other`, `sample 46`
- ~[ ] Release notes have been updated~ (Fix linked above already updated in release notes)
--- …
> fix(identify): indentify properly filters out symbology stacks

- package-lock.json
- src/content/samples/iframe-map.tpl
- src/content/samples/index-samples.tpl
- src/locales/help/default/en-CA.md
- src/locales/help/default/fr-CA.md
The 'datatable' section of the help file was being added as a subsection to the 'export image' section (in both English and French pages).
Fixed the spacing issue so all intended main sections appear as so.
:eyes: 
English and French help files (`en-CA.md`, `fr-CA.md`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3073)
> docs(help): datatable documenation not subsection anymore

- src/app/ui/loader/loader-service.directive.js
- src/app/ui/loader/loader-service.html
- src/locales/translations.csv
Displays an error when attempting to load an http service over an https connection.
Closes #3031
Tested over localhost https mode. 
inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3048)
> fix(https): display error when importing non https service over https

- src/app/ui/geosearch/geosearch-top-filters.html
- src/locales/translations.csv
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3068
Test on any sample, close button should have original text, erasing filter should have new text.
French translations are official (copied from datatable) and should work.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3070)
> fix(geosearch): clear filters has proper label on hover

- src/app/core/bookmark.service.js
- src/content/samples/bookmark-decode.html
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3071
Test sample 76, sample 75. 
WFS layers should be preserved upon switching from Lambert/Mercator and English/French.
**Use the [UPDATED BOOKMARK DECODER](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/fix-mercator-french/dev/samples/bookmark-decode.html) to test if the WFS layer is properly encoded/decoded.**
--- …
> fix(bookmark): WFS layer bookmarks properly encoded and decoded

- src/app/geo/legend-block.class.js
- src/app/ui/toc/symbology-stack.directive.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2456
`keys=NPRI_CO, CESI_Other, JOSM`, `sample 46`, other samples with symbology stacks. 
**Test six cases:**
- Toggle off each item in stack, does top level layer toggle off automatically?
- Now toggle on an item in the stack, does top level layer toggle on automatically?
- Toggle off top level in the stack, do all items in the stack toggle off automatically?
- Toggle on top level in the stack, do all items in the stack toggle on automatically?
- Toggle off visibility of non-symbology stack layer, is the datatable empty?
- Toggle on visibility of non-symbology stack layer, is the datatable formatted properly?
Pay attention to correct entries showing up on datatable, and correct symbologies showing up on map.
- ~[ ] Help …
> fix(ui): toggle stack and layer behaviour in sync

- src/app/focus-manager.js
Fixes an issue where the focus manager would appear to be stuck before a slider element. It had an incorrect focus target selector which resulted in a falling back to the original position. 
Closes #3094
👁 
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3101)
> fix(focusManager): Slider selector corrected

- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
The order not being correct on the API side prevented certain lookups  from working properly. Should now keep track of reorders and orders of layers added through the wizard.
:eyes:
Try adding services, reordering legends
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3074)
> fix(LegendAPI): keep viewer and api legend children synced

- src/app/geo/legend-block.class.js
- src/app/ui/toc/symbology-stack.directive.js
Fixes a bug which was missed in this PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3051
Also closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3110
https://webservices.maps.canada.ca/arcgis/rest/services/PHAC/fluwatchers_en/MapServer/0
Add above service [current develop](http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html). 
- Uncheck each symbology individually WITHOUT OPENING TABLE
- Now check top level --> you will notice that boxes are checked but points on map are gone
This PR fixes that issue. 
Repeat the steps described above, in any demo sample, it should work.
Please test multiple cases especially where layers are under groups or sets if you can. 
The bug was caused because of a piece of code that was added to avoid race conditions with groups or sets ( as a …
> fix(symbology): layer toggles properly when table not open

- src/app/core/config.class.js
- src/content/samples/config/config-sample-80.json
Sets default values for the legend export config component. Without the defaults, the config tries to read values of `undefined` and fails.
- open config 80
- if the map loads, everything is okay
- generate export image and config there is no legend in the image
- eat a fizzy boom
Closes #3146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3148)
> fix(config): add defaults to legend export config

- api/plugin-loader.ts
- intention/geosearch/geosearch.intention.ts
- src/app/ui/geosearch/geosearch.service.js
- src/content/samples/intentions/epsg.js
- Basic conversion of @barryytm `geoSearch` intention to TypeScript for proper compilation. 
- Fixed `EPSG` intention to use native functions instead of arrow functions not supported in IE11. This file is not compiled during build.
- Fixed issue where an object type was being instantiated as a class type.
None
That's a lot of checklist items 😟
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3142)
> Fixed v3 loading issues for IE11

- src/app/geo/legend-block.class.js
- src/app/geo/legend.service.js
- src/content/samples/config/config-sample-06.json
Closes #3113
:eyes: on sample 6
Added a metadata url for `Nuclear` layer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3163)
> fix(geo): metadata shouldn't be available if undefined in config

- src/app/ui/export/export.html
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2978
Title length is limited to 128 chars, and as a direct result filename is also limited thanks to this bit of code in `export.service.js`:
```js
// file name is either the `app id + title` provided by the user or `app id + timestamp`
if (self.titleComponent && self.titleComponent.value !== '') {
fileName += ` - ${self.titleComponent.value}`;
} else {
const timestampComponent = self.exportComponents.get('timestamp');
if (timestampComponent) {
fileName += ` - ${timestampComponent.value}`;
}
}
```
copy/paste this into export map
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip …
> fix(export): limit export title to 128 chars

- src/app/ui/export/export.service.js
- webpack.common.js
Fixes downloading of the exported image in Edge. See the issue for more details.
Closes #3184 
Load sample 75 and try to download the export image in Edge. It should work. (It also should still work in all other browsers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3189)
> fix(export): use native toBlob in Edge

- package-lock.json
- src/polyfills.js
This update makes the `NodeList.forEach` polyfill available for all browsers - previously it was restricted to IE11.
Also, the `TextEncoder` and `TextDecoder` polyfill code has been updated so that it gets properly applied by the Microsoft Edge browser. This fixes issues with file based layer loading as discussed [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2700#issuecomment-445911366).
Tested file based layer loading on ie11, Edge 15, and chrome.
Layer used: [oddProjDownsview.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/2686615/oddProjDownsview.zip)
Inline as needed
Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes …
> fix(polyfill): NodeList.forEach no longer ie11 specific + more

- package-lock.json
- package.json
- schema.json
- src/app/geo/geo-search.service.js
- src/content/samples/config/config-sample-21.json
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3111
Function `isEnabled()` was returning `isDisabled()` :trophy: :clap: 
Sample 21 has `FSA` in the disabled searches list. 
Searches should not return any FSAs (e.g. `K1K`) but should return a scale result (e.g. `1:50000`).
Any other sample should return both FSAs and scales
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3179)
> Enabled search test logic fix

- package-lock.json
- package.json
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3194
Updates screenfull library, makes fullscreen work in Chrome again
Tested in IE11, FF, Chrome. Went in and out of full screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3195)
> Update screenfull library

- docs/developer/legacy_api.md
- docs/index.html
- docs/mapauthor/intro.md
- docs/mapauthor/working_examples.md
- package-lock.json
- src/app/core/core.run.js
- src/app/core/global-registry.service.js
- src/legacy-api.ts
- webpack.common.js
Completes code portion of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3153.
The ramp build now outputs a `legacy-api.js` file which needs to be included on the host page before any legacy api calls are made. This file contains the proxy logic in the form of a priority queue. 
`getMap` continues to be synchronous while all subsequent api calls are async. No changes are needed to legacy api calls when upgrading to v3 except for including the `legacy-api.js` file.
👀 on chrome, IE, and Edge
Inline. User documentation to follow.
--- …
> chore(api): add back support for legacy api

- api/src/map.ts
- api/src/panel.ts
- docs/developer/panels.md
- intention/table/PanelManager.ts
- intention/table/table.intention.ts
Reduces complexity on end-user by accepting more content types when setting a panels body or controls. 
Plugins repo updated as well.
Closes #3169
👀 on chrome, ie, edge
Main docs updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3208)
> fix(panels): improve panel api

- api/src/layers.ts
- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/toc.directive.js
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3252
`index-samples` didn't used to work on `v3` because of lack of checks for filter/filterState/tableNode when they didn't exist (mostly on image, tile and wms layers)
:eyes:
- open index-samples and mess around with sample 75 (all layer types) and other samples with diverse layers
- ~[ ] Release notes have been updated~
--- …
> fix(filter): add checks for filter/tableNode existence

- src/legacy-api.ts
Since `runQueue`  be called multiple times (language/projection changes) this PR purges a priority queue once it has run so that a queued api call is never invoked more than once.
Closes #3255 
Tested with http://fgpv.cloudapp.net/demo/users/milesap/3255-fix-legacy-queue/prod/samples/index-fgp-en.html?keys=josm in chrome, ie, and edge by toggling languages & projection changes. See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3255#issue-402819769
None 
--- …
> fix(api): purge queued legacy api calls once invoked

- package-lock.json
- package.json
- src/app/geo/legend-block.class.js
Updates geoApi in support of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3269)
> geoApi update

- scripts/travis/builddocs.sh
Fixes documentation deployment error (bad bash) which occurs on the `dev` travis build matrix for select tags and branches of the official ramp repo. 
https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/travis-build-fix/#/
https://docs.fgpv.org/fgpv-vpgf/fgpv-vpgf/travis-build-fix/#/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3298)
> chore(build): fix travis doc deploy error

- src/app/geo/layer-blueprint.class.ts
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3324
Closes #3329 
Also fixes a (related) unidentified bug where an incorrect tooltip field was being displayed for file layers.
:eyes: 
Change the primary field and lat/long fields when adding a file-based layer through the import wizard
In-line comment added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3328)
> fix(details): display correct primary field for file layers

- src/app/core/config.service.js
#3319 
`rcs.abc.en` wouldn't match `rcs.abc.fr` in the bookmark. Regex to the rescue.
http://fgpv.cloudapp.net/demo/users/spencerwahl/lang-change-rcs/prod/samples/index-fgp-en.html?keys=JOSM
- toggle visibility of layer off
- language switch using top right link
- Layer should not be visible on load
- toggle layer vis back on
- switch language again and layer should be visible on load
Added a comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/332 …
> fix(core): fix rcs and bookmark id matching

- package.json
- src/app/geo/layer-blueprint.class.ts
- src/app/ui/loader/loader-service.html
Closes: 
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3301: WFS layers are configurable through wizard
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3306: leftmost indicator arrow appears in `enhancedTable`
Test with WFS Layers (eg: http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?startindex=6000)
they should be configurable like this:
Primary Field should correspond to the field shown in identify: 
Tooltip should correspond to hovertip: 
n/a
--- …
> Configurable fields for WFS services + First Column Sort Indicator

- package-lock.json
- package.json
- src/app/ui/common/full-screen.service.js
Closes #3291 - Updated `screenfull` library to 4.0.1 but issue persisted. Need to only enter/exit fullscreen mode if we aren't already in the appropriate mode. Added a check for that.
:eyes: 
Tested in Chrome, Firefox, IE - Entered / exited fullscreen mode using the menu options and also `Esc`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3352)
> fix(fullscreen): correctly exit out of fullscreen mode

- api/src/legend.ts
- package-lock.json
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/symbology-stack.html
#3131 
Refactored symbology stack to stop relying on symbol names
index-fgp use key `JOSM`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3357)
> Symbology toggle upgrades

- src/app/geo/metadata.service.js
- src/content/metadata/xstyle_default_en.xsl
- src/content/metadata/xstyle_default_fr.xsl
#3180 
`mailto` link is now correct, french metadata has returned, email address is still duplicated in display
index-samples #6 is an easy one to check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3354)
> fix(ui): fix metadata mailto and french

- api/src/panel-registry.ts
- api/src/panel/index.ts
- src/app/api-loader.ts
- src/content/samples/plugins/panels.js
Adds a `reopenAfterOverlay` boolean option to panels which reopens a panel iff it was closed by an overlaying panel.
The panel registry keeps a list of panels in the order they were closed so they can be notified to check if they can reopen whenever:
- A panel closes
- The viewport size changes
- A panels position or width/height changes 
Added a checkbox to index-samples.html which lets you create a panel with this setting. 
None yet - will add prior to v3 merge
--- …
> Panels: reopenAfterOverlay implementation 

- api/plugin-loader.ts
- src/app/core/reload.service.js
- src/app/geo/geo.service.js
- src/content/samples/plugins/panels.js
Adds support for an optional plugin method `destroy` which gets called right before the map is destroyed.
Closes #3391
Added a console warning to the panel tester on `index-samples.html`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3393)
> feat(plugins): support destruction

- features/geosearch/geosearch.feature.ts
- features/package.json
- package-lock.json
- package.json
Made by @JahidAhmed (package files fixed by me)
Closes: #3112
- you can look at commits `2.0.8`, `2.0.9` and `2.1.0` on `geosearch`: https://github.com/RAMP-PCAR/geosearch/
these will be absent from results and filter dropdown menu in sample `87` where `FSA` and `NTS` are both disabled. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3395)
> fix(geosearch): allow for NTS querying and excluded results

- api/src/schema.d.ts
- src/app/ui/common/expand-image.directive.js
- src/app/ui/toc/symbology-stack.directive.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3183
:eyes: sample 87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3433)
> fix(ui): symbology stack image enlarge button missing

- api/src/panel/button.close.ts
- src/app/ui/details/detail.service.js
- src/app/ui/geosearch/geosearch.service.js
- src/content/styles/modules/_details.scss
- src/content/styles/modules/_geosearch.scss
Fixes issue where details and geoSearch panels did not open on certain mobile browsers.
Closes #3457 
Works on mobile emulation in Chrome and on iPhone XS (browserstack)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3460)
> fix(panels): mobile styling fixes + close button fix

- src/app/geo/legend-block.class.js
(Hopefully) Closes #3476 
Moved around some of the previously added logic to prevent loaded attribute count going above the actual count to a more suitable spot since it was not doing its intended behaviour previously
Hard to reproduce issue so wasn't easy to test. Tried slow layers / in IE and did not notice the issue. Can't fully confirm if the issue is resolved however.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3492)
> fix(table): loaded attributes capped at maximum value

- src/content/samples/index-fgp-en.tpl
Fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3464
Unable to test the fix for the button being cut off in Safari, but according to a similar issue (https://stackoverflow.com/questions/50561964/button-width-cut-off-in-safari), this fix may work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3497)
> refactor(samples): change backToCart button text for consistency

- api/src/panel-registry.ts
- package-lock.json
- package.json
- src/app/geo/map.service.js
- src/app/layout/reference.service.js
- src/app/ui/appbar/appbar.directive.js
#3481 
plugins PR: https://github.com/fgpv-vpgf/plugins/pull/95
Zoom wasn't working until the table set `externalOffset` because the calculation was using the old panels.
Now the calc uses the new panels PLUS it will fade any panel (from plugins, etc) that are on top of or very close to the zoom point.
Details zoom should work in any sample without triggering a zoom from the table.
Comments and function headers updated
- [] Release notes have been updated
--- …
> Fix for zoom offset calculation

- package-lock.json
- package.json
- src/app/geo/layer-registry.service.js
Closes #3515 
Remove the WMS layer in Sample 1 through the API: `RAMP.mapInstances[0].layersObj.removeLayer('wms')`
- ~~[ ] datagrid works~~
- ~~[ ] identify works~~
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3526)
> fix(layerRecord): remove extra check for filter listener

- scripts/travis/docs.sh
Disables jekyll on GitHub pages allowing files leading with an `_` underscore to be served.
This change retroactively corrects all prior doc deployments. 
Docs referenced in original issue: http://fgpv-vpgf.github.io/fgpv-vpgf/ghpages-docs/developer/api_tech_docs/ is working
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3551)
> chore(build): fix GitHub Pages technical doc

- README.md
- docs/developer/legacy_api.md
Updating any docs pages referencing `ghpages-docs` to point to version specific cut of docs, as gh is not getting updated.
Tested new urls in browser.
Tested relative path changes in legacy api doc page using `npm run docute`
I am documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3553)
> Use tagged docs instead of ghpages

- src/app/ui/geosearch/geosearch.service.js
Fix for https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3539
Tests can be performed using existing sample files. Open search and search for coordinates, and then try filtering by province or type. The error should no longer appear.
--- …
> fix(geosearch): fix error when using drop boxes with coordinates

- src/app/core/reload.service.js
- src/app/ui/geosearch/geosearch-filters.service.js
Closes #3558 and #3559 
Use any sample page. First, test that the province and type filters for geosearch are now in the correct language when changing languages. Next, apply a province and/or a type filter, then change languages and ensure that the search and filters still work as intended. 
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> fix(geosearch): fix filter languages and changing languages with filters applied 

- src/app/ui/geosearch/geosearch-bar.directive.js
Closes #3569 
Use any sample page. Open geosearch and type in a search term longer than 1 character. Highlight and delete the term. Close geosearch and reopen, the search term should be cleared. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/357 …
> fix(geosearch): fix geosearch search term popping up after clearing by highlighting term 

- src/app/ui/details/details.directive.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3517
Reverting changes from https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3581)
> fix(details): revert details panel is properly populated

- api/src/schema.d.ts
- schema.json
- src/app/geo/legend.service.js
- src/app/ui/toc/symbology-stack.directive.js
- src/content/samples/config/config-sample-90.json
- src/content/samples/config/config-sample-91.json
- src/content/samples/index-samples.tpl
Starts on: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3143, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3143#issuecomment-505011927
**Note:** custom symbologies don't apply to WMS layers
Important additions to schema: 
- [sqlQuery](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3619/files#diff-76d5ffeac090c76ed5f4c581f02f3c53R587)
- [CORS Description](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3619/files#diff-76d5ffeac090c76ed5f4c581f02f3c53R582)
`sample 91` ( ^ pointing to different but identical branch until travis build issues are solved)
- WFS Layers, Feature Layers, Dynamic Layers, File Based Layers (GeoJSON, Zipped ShapeFile, CSV)
- New Stacks (no default symbology stack exists for layer)
- Overriden Stacks (default symbology stack exists for layer)
- Mixed Stacks (`Feature …
> feat(ui): add custom query capabilities for symbology stacks

- src/app/ui/geosearch/geosearch-filters.service.js
Fix for #3611 
Thanks to @yileifeng for finding this solution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3628)
> fix(geosearch): type and province filters work in IE

- api/src/panel/header.ts
Closes #3627
Use any sample page with this layer: https://maps-cartes.ec.gc.ca/arcgis/rest/services/ICDE/MapServer/5. 
Click on one of the data points and make sure the details header title is displayed correctly. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3640)
> fix(details): display detail header title containing french apostrophe

- package-lock.json
- package.json
- schema.json
Closes #3651
Created the following to run custom tests on special characters (convert to CSV): 
[gridSpecialChars.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3387342/gridSpecialChars.xlsx)
Import this as a file layer and filter the special characters column using `?`, `\`, `|`, etc. The filters may not apply to the table correctly but applying filters to map should work. The exceptions are `%` and `*`, which will be worked on in #3647. 
--- …
> fix(attrib): fix special chars applying filters to map

- api/plugin-loader.ts
- src/app/ui/export/export-component.class.js
- src/app/ui/export/export-components.service.ts
- src/app/ui/export/export-generators.service.js
- src/app/ui/export/export-simple.html
- src/app/ui/export/export.service.js
- src/content/samples/config/config-sample-91.json
- src/content/samples/index-samples.tpl
- src/content/styles/modules/_export.scss
Adds export plugin registration to the core export service. Also updates some of the internal export generator code to no longer accept `exportSize` when creating export images. Generator output now only depends on the size of the RAMP container, if at all (north arrow generator for example doesn't need the map size at all).
This PR should not change the existing export behaviour. 
Closes #3599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3654)
> core(export): add export plugin registration

- api/src/map.ts
- api/src/schema.d.ts
- package-lock.json
- src/app/core/graphics.service.js
- src/app/ui/export/export-generators.service.js
- src/app/ui/export/export-legend.service.js
- src/app/ui/export/export.service.js
Closes #3600 - expose export generators on API
Starts on #3602 - use array of API layers as the way to indicate which layers should be in export image (EDIT: need to change to using legendAPI if possible, after this PR)
Existing export behaviour remains the same.
Made some changes to existing code added by Aleks' but it is currently commented out:
`// CURRENTLY COMMENTED OUT WIP. Code modified though to use generators exposed on API`
Please also review this section to see if changes made are acceptable.
Tested using breakpoints and viewing result in default export window.
In-line comments added
Please keep the original issue up to date with the final solution, expected behaviour, and any …
> feat(export): expose export generators on API

- src/app/focus-manager.js
Fix regression for https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3387 (discovered here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3663#issuecomment-513259188)
Thanks @ShrutiVellanki for the fix!
`index-samples`: http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-option-regression/dev/samples/index-samples.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3666)
> fix(ui): fix list navigation regression

- src/app/focus-manager.js
Fixes an issue where closing some panels using tab in IE, Firefox or Edge would result in tab no longer working. This fix prevents the tab key from being locked after closing a panel.
This change fixes the problem in Firefox and Edge completely and doesn't break anything in Chrome. In IE, this fixes the issue when closing some panels (the data grid and share panels) but does not work when closing the help or export menus. Another issue will be created to handle these.
http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3537/dev/samples/index-samples.html
---
This …
> fix(ui): fix accessibility navigation issues with tab in some browsers

- src/app/geo/legend.service.js
Update the legendAPI to close panels through new method
Sample 1
Opened a `Liquids Pipeline` panel and then in the console... `RAMP.mapInstances[0].ui.configLegend.configSnippets = [RAMP.mapInstances[0].ui.configLegend.configSnippets[0]]`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3682)
> fix(legendAPI): close any open panels when updating legend

- src/app/focus-manager.js
- src/app/ui/toc/symbology-stack.directive.js
Closes #3542 
`index-fgp-en.html?keys=JOSM,CESI_Other` and `sample 91` 
Use keyboard navigation to expand the symbology and ensure that the navigation does not get stuck at any point with symbology expanded. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3684)
> fix(ui): fix keyboard nav for expanded symbology icons

- package-lock.json
- src/app/ui/export/export.service.js
Closes #3685 
Console, checked that a copy was correctly made with the required functions (e.g. `walk`).
Checked that we had the correct IE polyfills required.
In-line comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3688)
> fix(export): plugin takes cloned copy of legendBlocks

- package-lock.json
- package.json
Fix for #3694 and #3689
GeoApi PR: https://github.com/fgpv-vpgf/geoApi/pull/356 
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/132
Use: 
[test.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3486948/test.xlsx) and convert to CSV
The lat/long columns should be treated as numbers now with the min/max filters. Negative values should be filtered correctly and all non-numbers will not be accepted (e.g. typing -12 followed by 'a' will revert back to -12) 
--- …
> fix(attrib): fix lat/long column filtering

- src/app/geo/legend-block.class.js
- src/app/ui/toc/symbology-stack.directive.js
- src/app/ui/toc/templates/visibility-menu.directive.js
addresses comment on https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3593
Allows the show all button to steamroll changes through symbology
:eyes: any layer with symbology toggles 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3704)
> fix(symbology): show all/hide all effect symbology

- package-lock.json
- package.json
Implements #3699
[testLongLatZeroes.xlsx](https://github.com/fgpv-vpgf/fgpv-vpgf/files/3493955/testLongLatZeroes.xlsx) (conver to CSV)
Negative num filters should properly apply to map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3705)
> feat(query): add support for Prefixes

- package-lock.json
- package.json
The package-lock.json file was using an old commit hash. The border should no longer be visible on the colour picker.
Test [here](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-borders/dev/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3733)
> fix(ui): remove border from colourpicker

- package-lock.json
- src/app/geo/layer-registry.service.js
- src/app/geo/legend.service.js
Closes #3751 
Fixes issue with dynamic layers not getting added to legend / API due to timing issues. May need to revisit this problem to find a better overall solution to the timing relating to layers and legend objects.
👀
Tested mainly using `NPRI_CO` since it used to error the most frequently
Link for testing: http://fgpv-app.azureedge.net/demo/users/JahidAhmed/legendAPI-timing/dev/samples/index-samples.html?keys=NPRI_CO
Seems to be working as expected in Chrome, IE11 and Edge.
JSDoc, in-line comments
--- …
> fix(legendAPI): dynamic layers getting added to API

- api/plugin-loader.ts
- api/src/events.ts
- api/src/geometry.ts
- api/src/map.ts
- package-lock.json
- package.json
- schema.json
- src/app/core/config.class.js
- src/app/core/core.run.js
- src/app/geo/identify.service.js
- src/app/geo/layer-blueprint.class.ts
- src/app/geo/legend-block.class.js
- src/app/geo/locate.service.js
- src/app/geo/map-tools.service.js
- src/app/geo/map.service.js
- src/app/layout/shell.directive.js
- src/app/ui/basemap/basemap.directive.js
- src/app/ui/basemap/basemap.html
- src/app/ui/geosearch/geosearch.service.js
- src/app/ui/loader/layer-source.service.js
- src/app/ui/tooltip/tooltip.service.js
- src/content/samples/config/config-sample-92.json
- src/content/samples/index-samples.tpl
Adds support for WKT projections, and fixes code that previously demanded WKID only.
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3442
Also fixes some related bugs discovered along the way
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3744
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3745
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3746
GeoAPI best buddy PR https://github.com/fgpv-vpgf/geoApi/pull/360
Sample 92 contains a 3rd basemap section Azimuth, and that projection is WKT type.  It also has the cursor info set to show points in Azimuth projection.
Unless specified, all tests are against both wkid and wkt basemaps
This corner of James and Hudson bays is `[-82.438345, 55.012662]` in lat-long and `[511951, -3856581]` in the Azimuth WKT projection.
Note there can be some difference …
> Support for wkt projections

- packages/ramp-core/src/content/styles/modules/_basemap.scss
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3759
http://fgpv-app.azureedge.net/demo/users/yileifeng/projection-warning/dev/samples/index-samples.html?sample=92
See projection warning when changing basemaps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3773)
> fix(ui): enhance projection warning label

- packages/ramp-core/src/app/layout/shell.directive.js
Closes #3784 
Pressing the `esc` key will act in a manner similar to how it did in RAMP 2.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3788)
> fix(geosearch): prevent focus from getting stuck in geosearch

- packages/ramp-plugin-enhanced-table/src/panel-manager.ts
Closes #3775 
Plugins PR: https://github.com/fgpv-vpgf/plugins/pull/150
__Note__: had to re-PR this because I forced pushed 0 commits to the last one 🤦‍♂. You can find the old PR [here](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3777)
http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3775/dev/samples/index-samples.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3789)
> fix(enhancedTable): tooltip always shows up when cell text is cut off

- packages/ramp-core/src/app/core/config.service.js
- packages/ramp-core/src/app/global-registry.js
Updates from 3.22 (for real this time) to 3.31.
Testing the basics like maps load, layers load, layer load indicators turn off appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3793)
> Update esri api to 3.31

- packages/ramp-core/schema.json
- packages/ramp-core/src/app/core/config.class.js
- packages/ramp-core/src/content/samples/config/config-sample-90.json
- packages/ramp-core/src/content/samples/index-samples.tpl
Closes #3787 
Adds outfields support to feature layers.
I've added a test case to sample 90 for this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3790)
> feat(schema): add outfield option to feature layers

- packages/ramp-core/src/locales/translations.csv
Closes #3783 
Changed side menu labels for `Plugin Links` and `Liens`. 
See side menu.
[test link](http://fgpv-app.azureedge.net/demo/users/yileifeng/rename-sidenav/dist/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3800)
> fix(ui): rename sidenav plugins options

- packages/ramp-geoapi/src/attribute.js
Fixes an issue where the details panel would display all attributes even if `outfields` was defined on the layer.
You can test this PR using [this sample](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-outfields/dist/samples/index-samples.html?sample=90). Click on one of the `Electric Transmission Line` points on the map. Only the fields defined in `outfields` (`OBJECTID`, `COUNTRY`, `LATITUDE`, and `LONGITUDE`) should appear.
--- …
> fix(details): details shows correct attribs when using outfields

- packages/ramp-core/api/src/layers.ts
Builds off of James' comment in #3568 - API removal of attributes now doing what is intended
Test link: http://fgpv-app.azureedge.net/demo/users/JahidAhmed/3568-remove-attributes-fix/dist/samples/index-samples.html
No
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3807)
> fix(api): removal of attributes as intended

- packages/ramp-core/api/src/panel-registry.ts
- packages/ramp-core/api/src/panel/index.ts
- packages/ramp-core/src/app/layout/shell.directive.js
Adds a panel history array that stores the opened panels in the order they were opened. When pressing Esc, the panels are closed in the opposite order of which they were opened.
[Test Link](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-panel-history/dist/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3809)
> fix(panels): implement open panel history + close in order

- README.md
- packages/ramp-core/README.md
3.3 docs are broken, and not much has changed between 3.2 and 3.3.
rolling back readme links for now to avoid 404s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3818)
> rollback doc links to 3.2

- packages/ramp-core/package-lock.json
- packages/ramp-core/package.json
- packages/ramp-core/src/app/geo/identify.service.js
- packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js
- packages/ramp-geoapi/src/layer/layerRec/featureRecord.js
- packages/ramp-geoapi/src/layer/layerRec/wmsRecord.js
Enhances https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3781
Makes sure the new layer id properties make it onto the objects that get emitted by the observables.
Also found a race condition in the geoApi identify routines where the ids would not appear until after server results, and if slow the observables would emit `undefined` properties.
Easy console testing code (have a map with some layers)
```
var map = RAMP.mapInstances[0];
map.click.subscribe(c => {
console.log('click result', c);
c.features.subscribe(featureList => {console.log('features from click', featureList)});
});
map.layers.identify.subscribe(i => { console.log('identify result', i); });
```
[test link](http://fgpv-app.azureedge.net/demo/users/james-rae/layeridRedo/dist/samples/index-samples.html)
--- …
> Redo LayerId Observables Params and Identify Race Fix

- packages/ramp-core/api/src/schema.d.ts
- packages/ramp-core/docs/mapauthor/migration.md
- packages/ramp-core/src/content/samples/plugins/areas-of-interest/aoi-no-pics-config.json
- packages/ramp-core/src/content/samples/plugins/areas-of-interest/aoi-no-pics-index.tpl
- packages/ramp-core/src/content/samples/plugins/areas-of-interest/aoi-pics-config.json
- packages/ramp-core/src/content/samples/plugins/areas-of-interest/aoi-pics-index.tpl
- packages/ramp-core/src/content/samples/plugins/back-to-cart/back-to-cart-index.tpl
- packages/ramp-core/src/content/samples/plugins/coordinate-info/coordinate-info-index.tpl
- packages/ramp-plugin-areas-of-interest/src/html-assets.ts
- packages/ramp-plugin-areas-of-interest/src/index.ts
- packages/ramp-plugin-coordinate-info/src/html-assets.ts
- packages/ramp-plugin-coordinate-info/src/index.ts
- packages/ramp-plugin-custom-export/src/index.ts
Reverts resource keys and samples for ramp-supplied plugins.
A change during the migration to monorepo caused the plugin webpack package names to be used as the identifier in some spots.
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3826
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3827)
> Revert plugin resources to use public names

- packages/ramp-core/src/app/ui/toc/legend-control.directive.js
- packages/ramp-core/src/app/ui/toc/templates/legend-control-body.html
- packages/ramp-core/src/app/ui/toc/templates/legend-group.html
- packages/ramp-core/src/app/ui/toc/templates/legend-node.html
For #3819. There's still a problem with focusing for some layers (see [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3819#issuecomment-607343586)).
Fixes a legend problem where the tooltip does not appear when it is focused on using keyboard navigation.
[Test Link](http://fgpv-app.azureedge.net/demo/users/RyanCoulsonCA/fix-3819/dist/samples/index-samples.html?sample=1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3828)
> fix(legend): fix missing tooltip when navigating with tab

- packages/ramp-core/src/app/focus-manager.js
- packages/ramp-core/src/app/ui/toc/legend-element-factory.class.js
- Fixes an issue where focus incorrectly occurred within the map while trying to tab past the map. Elements with attributes `tabindex=0` were not being properly updated by the focus manager. 
- Adds focus links between some legend actions and the corresponding panels/content.
- Tested on chrome/edge/FF
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3852)
> Focus fixes

- packages/ramp-core/src/app/focus-manager.js
Fixes an issue where in some cases such as focus leaving the document the `keyup` event handler was not being invoked causing the focus manager to have an incorrect depressed key state.
The escape key is manually cleared after an `esc` + `tab` action. `tab` does not need to be cleared manually since it would be cleared by `keyup` on a subsequent `tab` press.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3853)
> Fixes an issue with FM incorrect pressed key state

- packages/ramp-core/src/app/geo/layer-blueprint.class.ts
Code change for #3857 
This covers the changes in the WFS3 spec now named OGC API - Features. The new query is backwards compatible from my testing. I also tested it in CCCS and layers following the new spec load there as well.
The new layer as mentioned in the issue (internal to ECCC): https://api.wxod-dev.cmc.ec.gc.ca/collections/ltce-stations/items
Old layer to test that its backwards compatible: https://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items
http://fgpv-app.azureedge.net/demo/users/spencerwahl/ogc-api-features/dist/samples/index-samples.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3858)
> Update WFS query to comply with OGC API - Features spec

- packages/ramp-core/src/content/styles/modules/_details.scss
Donethankses #3862 
[Demo link](http://fgpv-app.azureedge.net/demo/users/james-rae/css/dist/samples/index-fgp-en.html). Note the normal samples page can't be resized small enough to go to mobile view, but this one can. Just add a layer via the `+` to get some details.
Pls give it a good kicking to test it out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3863)
> Mobile css fix for Details

- packages/ramp-core/src/app/geo/layer-registry.service.js
Donethankses https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3864
Puts an interval in front of the code that generates the API layer. Interval spins until the map api variable is populated, avoiding the race condition error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3866)
> API Layer race condition

- packages/ramp-core/src/app/ui/common/truncate.directive.js
- packages/ramp-geoapi/spec/hilightSpec.js
Donethankses https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3869 , https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3871
corrects mispelled attribute tag.
removes code formatting chars from truncator spans
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3870)
> Text Truncation fixes

- packages/ramp-core/src/app/core/config.service.js
- packages/ramp-core/src/app/global-registry.js
- packages/ramp-geoapi/src/layer/layerRec/attribFC.js
Donethankses https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3873
- Boosted ESRI API to `v3.35`
- Removed the "take geometry from local layer" optimization for Point-based feature layers. First access will now always get full precision from the server, then use that as the cached value.
[Demo](http://fgpv-app.azureedge.net/demo/users/james-rae/hilight/dist/samples/index-fgp-en.html). To test, add feature layers via the `+` wizard, and attempt to zoom to points from Canada view (via grid zoomies or details zoomies buttons). After zoom, do a minute pan and ensure the layer point remains where the highlight was drawn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3875)
> Fix offset point highlighting

- packages/ramp-core/api/src/layers.ts
Fixes an issue that showed up on CDV.
WFS and file based layers were having their attributes deleted by a delayed init. This was breaking the layer and causing datatables to not open. It now checks and only deletes attributes from ESRI layers since they can reload attribs.
Thanks @james-rae for the help debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3879)
> WFS table bug

- common/config/rush/pnpm-lock.yaml
- packages/ramp-geoapi/.babelrc
- packages/ramp-geoapi/package.json
- packages/ramp-geoapi/webpack.config.js
This PR fixes a build issue where the viewer would not load in IE11. The `ramp-geoapi` package didn't have its own build, and `ramp-core` was pulling in its raw source code (and assuming that source code was fine to bundle as-is). 
This PR adds webpack and babel to the `ramp-geoapi` package. `ramp-core` will now pull in code that has been built and passed through babel by the `ramp-geoapi` package.
I also checked the other plugin packages and they all have a proper build setup. While they don't use babel they go through an equivalent transformation with the typescript compiler using a target output of `es5`.
Since this is a major build change it's best to test this PR a little more thoroughly and between all the browsers.
[Demo](http://fgpv-app.azureedge.net/demo/users/milespetrov/3867-bab …
> Fix geoapi build to use babel for ie11

- packages/ramp-geoapi/src/layer/layerRec/attribFC.js
Donethankses #3881
[Demo](http://fgpv-app.azureedge.net/demo/users/james-rae/hilight/dist/samples/index-fgp-en.html)
Use wizard to add layers. Test the zoom in button (found in grid rows, details panes). After a zoom in, do a small pan to ensure highlight is not jumping to new location.
Sample WFS Layer: `https://api.weather.gc.ca/collections/ltce-precipitation/items?LOCAL_DAY=3&LOCAL_MONTH=3`
Sample Feature Layer (from original issue): `https://section917.canadacentral.cloudapp.azure.com/arcgis/rest/services/MSC150/MapServer/5`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3882)
> Use local points for non esri layers geometry lookup

- README.md
- common/config/rush/pnpm-lock.yaml
- packages/ramp-core/package.json
Initial fix for getting the local build up and running. Updated `README` with new instructions required.
Couple of notes:
- `node-sass` version required updating (which I already updated in the `package.json` file, so nothing to worry about) since support for node v14+ added in this updated version
- Python 2 (and not 3) is required to run the build, added a download link and instruction to the docs
- New steps required to run project are updated in the `README` (update -> build -> serve)
- there may be one extra step involving a `c++` package which is required but I was unable to verify this, will need further testing from someone else to let me know if they can just take these updates and build without running into any issues or if I need to add that extra step in too
- I am still …
> chore(build): initial local build fix

- packages/ramp-core/src/locales/translations.csv
The French version contains `{{settingName}}` which doesn't print anything to the page. The English version contains a `span` translation element which is dynamically rendered based on the components value for `controlName`. 
Removing the `span` does not change the visible layout. Therefore I've replaced `{{settingName}}` with the working `span` from the English translation. 
Closes #3886 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3891)
> Correct french translation

- packages/ramp-plugin-coordinate-info/src/html-assets.ts
- packages/ramp-plugin-coordinate-info/src/index.ts
Closes #3910. 
This PR replaces the deprecated magnetic declination service with a noaa geomag service: https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination 
To test, use [this link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3910-mag-declin-service/samples/plugins/coordinate-info/coordinate-info-index.html). Turn on the Coords Info on the side bar and then click on different points on the map. The magnetic declination section should display proper values that can be validated with the declination calculator linked above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3929)
> fix(coordInfo): update magnetic declination service

- packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.html
- packages/ramp-core/src/content/samples/config/config-sample-66.json
- packages/ramp-core/src/content/styles/modules/_details.scss
- packages/ramp-core/src/content/styles/modules/_lists.scss
Closes #3914 
Changes the HTML structure of key-value pairs in the details panel to use `<dl>`, `<dt>`, and `<dd>` tags. Additionally, the feature title is surrounded by `<h4>` tags.
A demo link can be found [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3914/samples/index-samples.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)
> fix(details): fix semantic structure of key-value pairs

- packages/ramp-core/src/app/geo/init-map.directive.js
- packages/ramp-core/src/locales/help/default/en-CA.md
- packages/ramp-core/src/locales/help/default/fr-CA.md
Closes #3917 
This PR adds the ability to pan the map in a more granular manner by holding the `CTRL` key whilst using the arrow keys. The original issue also requests for a button to speed up panning, but this already exists by holding the `CTRL` key. 
I've added a new line to the help page that mentions this feature.
A demo for this PR can be found [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3917/samples/index-samples.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3935)
> feat(map): pressing CTRL key allows for a more granular pan of map

- packages/ramp-core/src/content/styles/modules/_buttons.scss
- packages/ramp-core/src/content/styles/modules/_lists.scss
- packages/ramp-core/src/content/styles/modules/_mapnav.scss
- packages/ramp-core/src/content/styles/modules/_setting-controls.scss
- packages/ramp-core/src/material/angular-material.scss
Adds a solid border around focused buttons to improve contrast. This border also applies to focused legend items and other interactive information sections such as the help content. 
[Demo](http://ramp4-app.azureedge.net/legacy/users/milespetrov/3916-focus-ring/samples/index-samples.html)
Closes #3916
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3930)
> Add focus ring around interactive elements to improve contrast

- packages/ramp-plugin-enhanced-table/src/index.ts
- packages/ramp-plugin-enhanced-table/src/panel-manager.ts
- packages/ramp-plugin-enhanced-table/src/templates.ts
Closes #3821 
This PR adds a new `hide all` button to the `Hide columns` panel in the table.
If all columns are visible, clicking this button will hide all of the columns. If some columns are hidden, then clicking this button will make the hidden columns visible.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3821/samples/index-samples.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)
> feat(enhancedTable): add a toggle all button for column visibility

- packages/ramp-core/api/src/schema.d.ts
- packages/ramp-core/schema.json
- packages/ramp-core/src/app/core/config.class.js
- packages/ramp-core/src/app/ui/toc/toc.directive.js
- packages/ramp-core/src/content/samples/config/config-sample-90.json
Closes #3823 
Adds a new option to the configuration file that allows you to open the table for a dynamic layer by default.
You can test this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3823/samples/index-samples.html?sample=90).
---
Note: This PR makes an assumption that the index provided will be a direct child of the `LegendBlock`. Is it possible that there may be a more deeply nested sublayer? If so, I'll need to modify the search code to do a recursive search.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3938)
> feat(toc): add dynamic layer support for tableIsOpen

- packages/ramp-core/src/app/ui/sidenav/menulink.html
- packages/ramp-core/src/app/ui/sidenav/sidenav.html
Closes #3913 and #3920 
Adds the required dialog roles + aria properties for the sidenav as a modal and `aria-labels` for each of the buttons on the sidenav (all buttons were missing labels). 
[Demo page](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3920-3913-WCAG-roles-labels/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)
> WCAG: add roles and aria labels to sidenav buttons and modal

- packages/ramp-core/package.json
Command was failing after a README.md file was deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3946)
> Fix doc generation command

- packages/ramp-core/src/app/geo/geo.constant.service.js
- packages/ramp-core/src/app/ui/toc/legend-element-factory.class.js
- packages/ramp-core/src/locales/translations.csv
Closes #3945 
This PR adds an icon and tooltip to the legend when displaying a layer that uses multipoint geometry.
You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3945/samples/index-samples.html). Try to import the following feature layer using the wizard and check that the symbol shows up in the legend entry. When hovering over the symbol, the tooltip should say `ESRI Feature Layer (974 points)`.
The feature layer: https://maps-cartes.services.geo.ca/server_serveur/rest/services/IAAC/assessment_inventory_en/MapServer/0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)
> fix(legend): add tooltip and icon for Multipoint geometry

- packages/ramp-core/src/app/ui/details/details-modal.html
- packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.html
- packages/ramp-core/src/app/ui/details/details-record-html.directive.js
- packages/ramp-core/src/content/samples/templates/wms-bc-script.js
- packages/ramp-core/src/content/samples/templates/wms-bc-template.html
- packages/ramp-core/src/locales/translations.csv
Closes the main issue in #3888, will be writing a follow-up to this [comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3888#issuecomment-843202034) shortly. 
To test, use the following steps: 
1. Add this [layer](https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT/ows?SERVICE=WMS&REQUEST=GetCapabilities) via wizard (ogcWms)
2. `const mapInstance = RAMP.mapInstances[0]`
3. `let layer = mapInstance.layers.allLayers[2]` (access the added layer - index may vary depending on layer order)
4. `layer._viewerLayer.config._details = { parser: "templates/wms-bc-script.js", template: "templates/wms-bc-template.html" };`
5. `layer._viewerLayer.config._featureInfoMimeType = "text/html"`
6. Click one of the points for the wms BC layer and expand the details …
> fix(details): fix empty expanded panel for wms bc templating

- README.md
- packages/ramp-geoapi/src/defaultSymbols.json
- packages/ramp-geoapi/src/symbology.js
Closes #3925 
This may be a bit harder to test since there is inconsistency in that the layer will sometimes error out when loading. 
1. Add this layer containing arcade symbology https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/PATH/MapServer/0 and wait for it to fully load (hopefully)
2. Opening up the details panel or data table should work with a placeholder `?` symbology icon
[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3925-arcade-symbology/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)
> fix(geo): use placeholder symbology in tables/details for arcade

- packages/ramp-core/src/app/ui/toc/toc.service.js
Closes #2592 
As far as I can tell, the original toast issue linked above has been fixed previously. The toast no longer appears when removing a layer via the API. If anyone is able to reproduce this issue, let me know.
This PR fixes another issue that is brought up in the comments of the issue, that the `layerRemoved` event is not fired when a console error related to the toast appears. This error was occurring due to a missing dependency in the `toc` service file. Now that this error no longer occurs, the event is emitted properly.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-2592/samples/index-samples.html?sample=1).
**Test Instructions**
To test this PR against a pre-added layer (i.e. through the config), use the following …
> fix(api): fix layerRemoved event when removing layer through API

- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/app/ui/toc/templates/symbology-stack.html
- packages/ramp-core/src/content/styles/modules/_toc.scss
Closes #3932 
When focusing on a symbology stack while in keyboard mode, a box will be drawn around the element.
[Demo 1](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3932/samples/index-samples.html) (regular symbology stack)
[Demo 2](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3932/samples/index-samples.html?sample=70) (symbology stack expanded by default)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3952)
> feat(toc): add focus box around symbology stack

- packages/ramp-core/src/app/core/shell.service.js
- packages/ramp-core/src/app/geo/identify.service.js
- packages/ramp-core/src/app/geo/legend.service.js
- packages/ramp-core/src/app/layout/shell.html
- packages/ramp-core/src/app/ui/details/detail.service.js
- packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.directive.js
- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/app/ui/toc/toc.service.js
- packages/ramp-core/src/content/styles/modules/_shell.scss
- packages/ramp-core/src/locales/translations.csv
- packages/ramp-plugin-enhanced-table/src/index.ts
- packages/ramp-plugin-enhanced-table/src/panel-manager.ts
Closes #3847
Announces map changes to screen reader users. Currently, the user is only alerted upon opening a data table (when it finishes loading) and when legend symbology is toggled as these were the two instances discussed in the issue. If there are more map changes that should be included (e.g. expanding details, opening settings/metadata panels, etc.), leave a comment and I will work on incorporating those in the PR.
Most of the browser extension SRs seemed to be fairly low quality so I ended up using [Microsoft Narrator](https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1) for testing which I found to be quite good. Let me know if there is a default/recommended SR that should be used instead.
[Demo …
> WCAG - alert users on map changes

- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
Closes #3955 
Fixes an issue where the focus could be trapped in the legend if you press TAB too quickly after expanding symbology.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3955/samples/index-samples.html).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3956)
> fix(toc): focus can get stuck in the legend when pressing TAB

- packages/ramp-geoapi/src/map/esriMap.js
Closes #3906 
This PR fixes a race condition that occurred between the Esri map load and the overview map load which caused the overview map to sometimes not be displayed on the viewer.
🚨 Before merging this PR, the config file for `index-fgp-en.html` needs to be reverted back. The config used in this PR is just for testing purposes. 🚨 
You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3906/samples/index-fgp-en.html).
**Test Instructions**
1. Open the demo link above in Firefox.
2. The overview map should always be displayed in the top right corner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3957)
> fix(map): remove race condition on overview map load

- packages/ramp-core/src/app/ui/help/help-summary.html
- packages/ramp-core/src/app/ui/sidenav/share-dialog.html
- packages/ramp-core/src/locales/translations.csv
fixes #3963 #3959 
The help expand buttons now have an `aria-label` of "Expand", this is the same as the expand buttons in details.
The bookmark "input" has an `aria-label` of "Link to share".
DEMO: http://ramp4-app.azureedge.net/legacy/users/spencerwahl/missing-labels/samples/index-samples.html
Nothing should be different visually, if you inspect both of the elements talked about above you should see an `aria-label` attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3965)
> fix(ui): add aria-label to help and bookmark

- packages/ramp-core/src/app/ui/appbar/appbar.html
- packages/ramp-core/src/app/ui/basemap/basemap.service.js
- packages/ramp-core/src/app/ui/sidenav/sidenav.service.js
- packages/ramp-core/src/content/samples/config/config-sample-01.json
Closes #3966 
The side menu will no longer open after closing the basemap panel (after it has been opened through the appbar).
This PR also fixes some small issues with sample 1: the WMS layer & legend icon should now load properly.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/334-fixes/samples/index-samples.html).
**Test 1 Instructions**
- open the basemap panel through the appbar
- close the basemap panel
- the side menu should not open
**Test 2 Instructions**
- open the basemap panel through the side menu
- close the basemap panel
- the side menu should open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3967)
> fix(ui): fix side menu opening unexpectedly 

- packages/ramp-core/src/app/ui/geosearch/geosearch-bottom-filters.directive.js
- packages/ramp-core/src/app/ui/geosearch/geosearch-filters.service.js
- packages/ramp-core/src/app/ui/geosearch/geosearch-top-filters.directive.js
Closes #3964 
Steps to test: 
1. Type anything into geosearch (e.g. Toronto) and add filter(s) (e.g. Type - City)
2. Change projection to trigger reload 
3. Open geosearch and all searched results should be there along with the filters applied and can be cleared properly
4. Ensure other geosearch functionality still works as intended
[Demo](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3964-geosearch-reprojection/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3968)
> fix(geosearch): keep province and type filters after projection change

- packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.html
- packages/ramp-core/src/app/ui/help/help-summary.html
- packages/ramp-core/src/app/ui/toc/legend-element-factory.class.js
- packages/ramp-core/src/app/ui/toc/templates/legend-control-body.html
- packages/ramp-core/src/app/ui/toc/templates/legend-group.html
- packages/ramp-core/src/content/samples/config/config-sample-05.json
- packages/ramp-core/src/locales/translations.csv
closes #3961 
Tooltips added to
- legend groups
- legend entries that are clickable
- expand/collapse buttons in details + help
DEMO: http://ramp4-app.azureedge.net/legacy/users/spencerwahl/missing-labels/samples/index-samples.html
hover over/tab to stuff, you should see the tooltips listed above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3969)
> feat(ui): add legend + expand/collapse tooltips

- packages/ramp-plugin-enhanced-table/src/main.scss
Closes #3962 
Changes the height of reorder arrows to center focus ring: 
[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3962-grid-focus-ring/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3985)
> fix(enhancedTable): fix off-centre focus ring for column reorder arrows

- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/app/ui/toc/templates/symbology-stack.html
Closes #3960 
This PR allows you to navigate properly between the individual components of the symbology stack.
You can find a demo link [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3660/samples/index-samples.html?sample=91).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3987)
> fix(toc): fix navigation between symbology stack components

- packages/ramp-core/src/content/styles/modules/_content-pane.scss
Closes #3970 
When the `close` button tooltip is focused, there will no longer be a horizontal scroll bar at the bottom of the modal window. As far as I'm aware, the close button being focused when the window opens is intentional, so I didn't fix this part of the issue. Let me know if I'm wrong here though.
You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3970/samples/index-samples.html).
**Test Instructions**
Click any button that opens a modal window (`share`, `help`, expand `details`, etc.) and put focus on the close button if it isn't already. There should no longer be a horizontal scroll bar at the bottom unless necessary.
--- …
> fix(ui): remove horizontal scrollbar from modal windows

- packages/ramp-plugin-enhanced-table/src/index.ts
- packages/ramp-plugin-enhanced-table/src/templates.ts
Related issue: #3973 
Renamed the "Hide Columns" button to "Toggle Columns" to better describe the button functionality.
Added unofficial French translations for the new strings. 
[Demo](http://ramp4-app.azureedge.net/legacy/users/sharvenp/3973/samples/index-samples.html)
To test:
1. Load RAMP
2. Hover over the toggle columns button in the data table and check the label
3. Use a [screen reader](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) and TAB to the button and check if the label can be read
4. Change the language and do the same
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3991)
> Rename "Hide Columns" button to "Toggle Columns" in the data table

- packages/ramp-plugin-enhanced-table/src/custom-floating-filters.ts
Related issue: #3975 
When the min and max date are set to the same value on the date filter, it will now filter out that specific date. 
[Demo](http://ramp4-app.azureedge.net/legacy/users/sharvenp/date-filter-fix/samples/index-samples.html)
To test:
1. Load RAMP
2. Load this layer: https://maps-cartes.ec.gc.ca/arcgis/rest/services/Shellfish_Classification_Mollusques/MapServer/6 (Feature layer)
3. In the "RISC_DATE" field, set the min date and max date to the same value
- Pick one of the existing date values in the column to single it out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3992)
> Fix date filter to single-out dates when min=max

- packages/ramp-plugin-enhanced-table/src/panel-manager.ts
- packages/ramp-plugin-enhanced-table/src/panel-status-manager.ts
Closes #3978 
When using the arrow keys to navigate through the data table cells, console errors will no longer appear.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3978/samples/index-samples.html).
**Test Instructions**
1. Open a data table and the developer console.
2. Use the arrow keys to navigate through cells.
3. There should no longer be errors displayed in the console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3993)
> fix(enhancedTable): remove error when navigating using arrow keys

- common/config/rush/pnpm-lock.yaml
- packages/ramp-core/package.json
- packages/ramp-core/src/app/geo/legend.service.js
Closes #4002 
Layer groups that are added through the wizard should now correctly work with identify and should no longer display an error in the console.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4002/samples/index-samples.html?sample=93).
To test this PR, make sure sample 93 still works as described in the fix for #3908:
>This PR adds a new sample page that contains a dynamic layer with stateOnly set to true on all children (the icon with the water droplets on it), and a dynamic layer with stateOnly set to true on one of its children (the blue circle with a flame in it).
Additionally, try following the steps posted [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/4002#issuecomment-978163190) and ensure that no error appears …
> fix stateOnly check to work with layer groups

- packages/ramp-core/src/app/ui/metadata/metadata.run.js
- packages/ramp-core/src/content/styles/modules/_content-pane.scss
Closes #3972 
This PR centers the icon in the middle of the `expand metadata` focus ring. I've also removed the `EXPAND_BTN_TEMPLATE` constant because it was not used anywhere.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3972/samples/index-samples.html?sample=50).
To test this PR, open the sample link above and open the `Metadata` panel for the layer. Try tabbing to the `expand metadata` button in the panel header and ensure that the icon is centered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4007)
> fix(ui): center icon in expand metadata button

- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/content/samples/config/config-many-1.json
- packages/ramp-core/src/content/samples/config/config-many-2.json
- packages/ramp-core/src/content/samples/config/config-many-3.json
- packages/ramp-core/src/content/samples/index-many-2.tpl
Closes https://github.com/ramp4-pcar4/story-ramp/issues/16. Race conditions are fun.
You can find some extra info on this issue [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3911). The issue is caused by the symbology auto-expand code being called before the DOM elements are fully loaded. The code being called early means that the calculated height is not correct, and causes the elements to overlap or not expand at all. To solve this issue, I've moved the code that does the expanding so that it is run whenever the symbology stack is updated (instead of just being called once on creation in the `link` function). I've also added a short timeout to ensure that the checkboxes are loaded if necessary. Adding a timeout here ensures that the DOM elements have properly loaded before …
> fix(legend): add timeout before auto expand to prevent race condition

- packages/ramp-core/src/app/core/formatters.filter.js
Closes #4001 
This PR adds a validate function to the linkifyjs formatter to ensure that domain names are at least two characters long (as is required to be a valid domain name) in order to prevent it from converting `p.id` to a hyperlink.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4001/samples/index-samples.html). I'm not able to load the service linked in the initial issue but just ensure that the details panel is still working as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008)
> fix(details): add validate function to autolink function

- packages/ramp-core/src/app/focus-manager.js
- packages/ramp-core/src/app/ui/common/keyboard-instructions.html
Closes #4004
Made some changes to focus manager behavior when viewer is in waiting state and user backtabs to prevent focus from being stuck on keyboard instructions button.
Services currently down but should still be able to test basic navigation. In particular, test out cases when focus is on keyboard instructions button. Shift-tab when focus is on button should remove focus, tabbing when focus is on button should move focus past viewer as expected. Another test is to enter the viewer and try leaving with `esc + tab` and see that the behavior around the keyboard instructions button remains consistent. 
[Demo](http://ramp4-app.azureedge.net/legacy/users/yileifeng/4004-keyboard-nav-stuck/samples/index-samples.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> fix(toc): keyboard navigation stuck on keyboard instructions

- packages/ramp-core/src/app/ui/export/export-generators.service.js
- packages/ramp-core/src/content/samples/config/config-many-1.json
Closes https://github.com/ramp4-pcar4/story-ramp/issues/67
The export service was grabbing the map element using `document.querySelector`, which always took the map element from the first map instance on the page. This doesn't work for pages that have multiple map instances, so I've modified this section of the code to search within the angular root element instead, which should keep each RAMP instance separate.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-export-bug/samples/index-many-2.html).
To test this PR, wait for all three maps on the demo page to load and then try to export one of the bottom two maps. The export image should only contain the layers for that particular map instance.
--- …
> fix(export): fix export service on multi-RAMP pages

- packages/ramp-core/package.json
- packages/ramp-core/schema.json
- packages/ramp-core/src/app/core/config.class.js
- packages/ramp-core/src/app/core/config.service.js
- packages/ramp-core/src/app/geo/layer-blueprint.class.ts
- packages/ramp-core/src/app/global-registry.js
Allows a GeoJSON object to be tacked onto a layer config. Means you no longer require a pre-existing file, can construct in memory or define in config file.  Utilize via new `rawFile` property on `geojson` config.
Also updates ESRI API to `v3.41`.
Demo builds are currently broken, but here is console code sample one can use against `index-fgp-en.html`.
```text
var map = RAMP.mapById('fgpmap');
var layer = map.layers.addLayer({
"layerType": "esriFeature",
"fileType": "geojson",
"id": "raw_happy",
"name": "Raw Happy",
"nameField": "name",
"url": "",
"rawFile": {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": { "name": "Right Eye" },
"geometry": {
"type": "Polygon",
"coordinates": [
[
[-90.3515, 53.7357],
[-92.1313, 53.1994],
[-91.2963, 51.9307],
[-88.9453, …
```
> Load Raw GeoJSON Layer

- common/config/rush/pnpm-lock.yaml
- packages/ramp-core/package.json
This PR removes the `caniuse-lite` dependency that was causing issues with the build. It doesn't seem like it was being used anywhere so I don't think this should break anything.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-build/samples/index-samples.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4031)
> fix(build): remove caniuse-lite dependency

- packages/ramp-core/src/app/focus-manager.js
- packages/ramp-core/src/content/samples/iframe-map.tpl
- packages/ramp-core/src/content/samples/index-iframe.tpl
Closes #4024 
This PR fixes the issue that caused focus to get stuck in the viewer when using RAMP inside of an iframe. This PR also re-adds the `index-iframe` test page, and adds some content below the viewer to ensure you can tab past it.
[You can find a demo for this PR here.](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4024/samples/index-iframe.html)
To test this PR, ensure that:
1. You can tab straight past the viewer without activating keyboard mode (just keep pressing tab, ignore keyboard instruction button)
2. You can activate keyboard mode, escape from it (esc + tab), and then tab past the viewer afterwards.
The `index-iframe.html` test page will be helpful for testing this PR.
- - - …
> fix(wcag): fix focus getting stuck in viewer when using iframe

- packages/ramp-geoapi/src/layer.js
- packages/ramp-geoapi/src/layer/layerRec/graphicsRecord.js
Closes #4017 
Added support for GeoJSON with a geometry collection at geometry level by cleaning up and converting the geometry set to a single supported geometry structure (`Point` --> `MultiPoint`, `LineString` --> `MultiLineString`, `Polygon` --> `MultiPolygon`). Multiple error checks added to ensure geometry type is consistent through the collection as well as the entire file. 
**Testing** (IPR):
- add https://raw.githubusercontent.com/jolevesq/contributed-plugins/OSDP/osdp/src/samples/geoJSON/polygons.json as GeoJSON layer and ensure no errors
- all other layer behavior should remain unchanged 
[Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/4017-geometry-collection/samples/index-samples.html)
- - - …
> Add support for geojson geometry collection

- packages/ramp-core/schema.json
- packages/ramp-core/src/app/core/config.class.js
- packages/ramp-core/src/app/ui/toc/legend-block.directive.js
- packages/ramp-core/src/app/ui/toc/templates/legend-node.html
- packages/ramp-core/src/app/ui/toc/toc.html
- packages/ramp-core/src/content/samples/config/config-sample-83.json
Closes #4011
Adds config option solution proposed in [comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/4011#issuecomment-1104338415) to turn off dynamic sublayers children remove control when flag is set to `false`, applying to all dynamic layers on the page. All other layer types remains unaffected. 
Since there may already be a workaround for the original issue, this can be closed if not needed.
[Demo](http://ramp4-app.azureedge.net/legacy/users/yileifeng/4011-sublayer-remove/samples/index-samples.html?sample=83)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4030)
> Add configurable option for turning off dynamic sublayers removal

- packages/ramp-core/src/app/ui/toc/templates/legend-error.html
- packages/ramp-core/src/app/ui/toc/templates/legend-node.html
- packages/ramp-core/src/content/styles/modules/_buttons.scss
- packages/ramp-core/src/locales/translations.csv
- packages/ramp-core/src/material/angular-material.scss
Closes #4022
This PR adds a new focusable element to the legend entries that have names that are too long to be displayed. 
Focusing on this new element will display the full name of the layer as a tooltip. This PR also makes it so a tooltip displaying the layer's name appears when hovering over entries that have a data grid (as it already does for legend groups).
--- 
This PR doesn't have to be the final version. If anyone has better ideas for displaying the full name of layers that are cut-off through keyboard navigation, or if you don't like the placement of the new element on the legend, I'm very much open to feedback.
You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4022/samples/index-samples.html).
- - - …
> feat(toc): add focusable element to see full layer name

- packages/ramp-geoapi/src/attribute.js
- packages/ramp-geoapi/src/layer/layerRec/attribFC.js
- packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js
- packages/ramp-geoapi/src/layer/layerRec/layerRecord.js
Closes #4020 
Layers that do not have a visibility defined in their configuration will now set their default visibility to the value retrieved from the server.
I tested this for both dynamic and feature layers by forcing defaultVisibility to false in the source code, but if anyone knows any layers that actually have defaultVisibility set to false for testing, please post below!
You can find a demo for this PR [here](https://fgpv-vpgf.github.io/fgpv-vpgf/fix-4020/samples/index-samples.html?sample=6).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)
>  layers respect defaultVisibility if not defined in config

- packages/ramp-core/src/app/core/core.run.js
- packages/ramp-core/src/app/ui/basemap/basemap.service.js
- packages/ramp-core/src/app/ui/sidenav/sidenav.directive.js
- packages/ramp-core/src/app/ui/sidenav/sidenav.html
- packages/ramp-core/src/app/ui/sidenav/sidenav.service.js
- packages/ramp-core/src/content/samples/index-many-2.tpl
Closes https://github.com/ramp4-pcar4/story-ramp/issues/202
Fixes Storylines issue where page jumps to a previous map (with side menu already open) after opening side menu for a different map on the page. This is due to sidemenu IDs named the same so we end up calling `rvFocus` on the first element found. Instead, using `$rootElement.find()` should find the correct menu. Changes to sample page can be discarded after demo if needed.
[Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/multi-instance-sidemenu/samples/index-many-2.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)
> Fix opening side menu on multiple instances

- packages/ramp-core/src/app/core/core.run.js
- packages/ramp-core/src/app/ui/basemap/basemap.service.js
- packages/ramp-core/src/app/ui/sidenav/sidenav.directive.js
- packages/ramp-core/src/app/ui/sidenav/sidenav.html
- packages/ramp-core/src/app/ui/sidenav/sidenav.service.js
- packages/ramp-core/src/content/samples/index-many-2.tpl
Same PR as #4045
Fixes Storylines issue where page jumps to a previous map (with side menu already open) after opening side menu for a different map on the page. This is due to sidemenu IDs named the same so we end up calling `rvFocus` on the first element found. Instead, using `$rootElement.find()` should find the correct menu. Changes to sample page can be discarded after demo if needed.
[Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/multi-instance-sidemenu/samples/index-many-2.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)
> Fix opening side menu on multiple instances (RE-PR)

- packages/ramp-core/src/app/core/bookmark.service.js
Corrects #4016 
Just a boolean swap, tested live by hacking the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4048)
> Bookmark state flag bug fix

- packages/ramp-core/src/app/ui/common/full-screen.service.js
Closes #4059
Accidentally removed a line of code in my previous fullscreen PR. I've re-added it and this issue is now fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4060)
> fix(ui): page content does not disappear when exiting fullscreen

- packages/ramp-core/api/src/geometry.ts
- packages/ramp-core/api/src/map.ts
- packages/ramp-core/src/content/samples/index-fgp-en.tpl
- packages/ramp-core/src/content/samples/index-fgp-fr.tpl
Donethankses #4061
The map API `.center` now returns the center of the map, not the center of the extent after being modified to be orthoganal in lat/long projection. 
Also adds `https` to some WET script tags which hopefully will make the fgp demo page look less horrendous.
To test, go to the [Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/goodcent/samples/index-fgp-en.html), zoom somewhere fun, open the console, and paste this line
```text
RV.getMap("fgpmap").centerAndZoom(RAMP.mapInstances[0].center.x, RAMP.mapInstances[0].center.y, 4326, RAMP.mapInstances[0].zoom);
```
The map extent should remain the same, not jump to an offset view.
- - - …
> Proper map center

- packages/ramp-core/schema.json
- packages/ramp-core/src/app/core/config.class.js
Donethankses #4066
Makes the config defaulter pass along the filter value so the layer can use it. Also added the property to the schema.
[Demo page](https://fgpv-vpgf.github.io/fgpv-vpgf/defexp/samples/index-fgp-en.html)
Then paste into console
```text
var map = RAMP.mapInstances[0];
var lconf = {
"id": "funtimes",
"layerType": "esriFeature",
"state":{"visibility": true},
"url": "https://maps-cartes.ec.gc.ca/arcgis/rest/services/EcoGeo/EcoGeo/MapServer/6",
"initialFilteredQuery": "Year_='2009'"
}
map.layers.addLayer(lconf)
```
When the layer draws, there will be less points than usual.
As is tradition, it appears the original specs of this item are lost, but seems to me this filter only gets applied initially; any subsequent filter stuff erases it. So you can toggle visibility and get …
> Feature layer filter fix

- packages/ramp-core/src/app/core/formatters.filter.js
Trailing spaces in data was breaking embedding images in the details panel. Added a trim in the regex match in our `picture` filter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4068)
> Fix whitespace breaking embedded images

- packages/ramp-core/src/app/core/formatters.filter.js
Added `target: "_blank"` to the linkify default options
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4071)
> Details links open in new tab

- packages/ramp-core/src/app/ui/common/full-screen.service.js
#4126 
We were applying fullscreen styles to all `rv-shell`s on the page, now it will only style the one under the specific instance getting fullscreened.
Checked in our `many` sample and in storylines and fullscreen seems to be working as intended everywhere now.
I would recommend using https://fgpv-vpgf.github.io/fgpv-vpgf/fullscreen-fix/samples/index-many.html to verify that fullscreen is working on different RAMP instances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4127)
> Fix fullscreen applying styles to all instance shells

- packages/ramp-core/src/app/ui/loader/layer-source.service.js
- packages/ramp-core/src/content/samples/config/config-sample-94.json
- packages/ramp-core/src/content/samples/index-samples.tpl
Donethankses #4122.
Dynamic layers with reordered indexes should now work for layers in the config as well as imported layers. [This service](https://maps.ottawa.ca/arcgis/rest/services/CyclingMap/MapServer) can be used to test that it works for imported layers. Additionally, sample 94 can be viewed to test that it works for the config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4124)
> Fix dynamic layers with reordered indexes failing

- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/content/samples/config/config-sample-95.json
- packages/ramp-core/src/content/samples/index-samples.tpl
fix for storylines issue where initial filter query was not being respected on visibility change
problem was in the code we have `change all symbology stack to toggled/untoggled if top layer is visible/invisible`, and technically if we disable individual toggling of symbology (which is a config option i set to false in sample 95), then it shouldn't be messing with the individual symbology visibilities at all.
now, since that portion is irrelevant in this case, we want to disable that block of code from executing. 
i also modified some of the table stuff to show only the relevant entries (especially on visibility change if table remains open), but that part is a bit confusing and im not sure if im breaking other edge cases.
- - - …
> fix(layer): storylines fix for filter query visibility

- packages/ramp-core/src/app/core/formatters.filter.js
- packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js
- packages/ramp-core/src/app/ui/toc/templates/symbology-stack.html
Fixes multiple issues from Storylines testing party last week: 
*Issue*: **Hovering doesn't work**
1. On a map open the Layers menu
2. Hover over a layer text
*Expected behaviour*: Because the layer names are long, I expect to hover over layer text and see full layer name
*Changes*: Added tooltips to truncated names in symbology items, one concern is that we can't trigger these tooltips via keyboard. Could turn the parent div container into a `<md-button role="presentation">` if that is more appealing, but there is nothing clickable. 
*Issue*: **If data in cell of data table is larger than column width, user cannot hover to see all text**
1. Open any map, then the web table
2. Scroll to 'REFERENCE DOCUMENT' column
3. Try and hover text
*Expected behaviour*: I expect when I try to hover …
> Add tooltips for symbology stack and fix details formatting

- packages/ramp-core/src/app/api-loader.ts
*Issue*: Maps: cannot open Layers panel in full-screen mode
1. Open Boreal Caribou chapter
2. Maximize the map
3. Try and click 'Layers' icon
*Expected behaviour*: I expect Layers to show and I should be able to open the data table
*Changes*: JQuery was targeting `rv-shell` for first map on the page, changed to closest.
[Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/multi-RAMP-offscreen/samples/index-many.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4130)
> Fix offscreen check targeting wrong shell for multi RAMP instances

- packages/ramp-core/src/app/geo/layer-blueprint.class.ts
#4133 
WFS api changed to `offset`, as far as I can tell just swapping all instances of `startindex` to `offset` has done the trick.
Testing;
1. Go to any sample where you can add layers
2. Add https://api.weather.gc.ca/collections/ltce-stations/items?ELEMENT_NAME_E=TEMPERATURE as WFS 3
3. There should be dots all over Canada
Old:
New:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4134)
> fix(geo): wfs uses offset instead of startindex
